[BE] refactor: 카페 별 고객 목록 조회, 현재 카페의 스탬프 모으고 있는 고객 쿠폰 조회 리팩터링
woowacourse-teams/2023-stamp-crush pull request #126
Opened 2023-07-17 14:32 UTC by youngh0

## 주요 변경사항

- 메서드 네이밍, 컨벤션 지키는 방향으로 수정했습니다.
- 현재 고객의 쿠폰이 예전 정책인지 확인하는 부분 createdAt을 비교하는 방향으로 구현했습니다. (댓글 달아놓을게요. 테스트도 작성했습니다)

## 리뷰어에게...

## 관련 이슈

closes #108 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-17 14:35 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +    private boolean isPrevious(Coupon coupon) {
cafe의 couponPolicy중 coupon의 createdAt보다 큰게 있다면 쿠폰 발급 이후 정책이 새로운 정책이 생긴것이기 때문에 해당 쿠폰은 예전 정책의 쿠폰입니다.

findByCafeAndCreatedAtGreaterThan()의 결과값이 비었다면 최신 정책 쿠폰이고, 비어있지 않다면 예전 정책 쿠폰이라고 판단하게 했습니다.

2023-07-17 14:35 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
> +    List<CafePolicy> findByCafeAndCreatedAtGreaterThan(Cafe cafe, LocalDateTime createdAt);
이 부분이 Cafe와 coupon의 createdAt으로 조회하는 쿼리입니다

2023-07-18 13:30 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
> +    List<CafePolicy> findByCafeAndCreatedAtGreaterThan(Cafe cafe, LocalDateTime createdAt);
GreaterThan 이런 메서드 네임을 사용할수도 있군요 JPA 신기하네요

2023-07-18 13:44 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +            visitCount += coupon.calculateVisitCount();
방문횟수 구하는 방식 얘기 필요 .. ! 😵‍💫

2023-07-19 08:49 UTC, eunkeeee approved these changes

2023-07-19 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +            CustomerInfo customerInfo = statisticsCustomerByCoupons(coupons);
와우 아주 깔끔하네요~

2023-07-19 09:07 UTC, jundonghyuk approved these changes
고생하셨어요 ^^ 리뷰남긴거 봐주세요 !

2023-07-19 09:07 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
> +    @JsonFormat(pattern = "yyyy:MM:dd")
서비스 반환 `dto`에서 빼주세요 ><

2023-07-19 09:07 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
> +    public static CustomerAccumulatingCouponFindResultDto of(Coupon coupon, Customer customer, boolean isPrevious) {
`good`

2023-07-19 09:07 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    public LocalDateTime compareCreatedAtReturnFaster(LocalDateTime visitTime) {
`And`를 붙여주세요. 
`Faster`는 분노의질주도 아니고 좀 그렇지 않을까요 ?

2023-07-19 09:08 UTC, jundonghyuk requested changes

2023-07-19 09:08 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
> +    public static CustomerAccumulatingCouponFindResultDto of(Coupon coupon, Customer customer, boolean isPrevious) {
네이밍 컨벤션이 좋네요

2023-07-19 09:28 UTC, youngh0 commented
@jundonghyuk 리뷰 반영했습니다 하디씨 ㅎ_ㅎ

2023-07-20 01:02 UTC, merged