[BE] refactor: 2차 데모데이까지의 코드를 리팩터링한다.
woowacourse-teams/2023-stamp-crush pull request #190
Opened 2023-07-21 03:35 UTC by eunkeeee

## 주요 변경사항

- Service 계층: 메서드 분리 통해서 복잡한 로직은 최대한 가독성 있게 수정함.
- test 코드: 가능한 만큼 Fixture 분리함.
- 매 commit 전에 전체 테스트코드 통과하는지 확인했습니다. 

## 리뷰어에게...

- 본인 코드인 부분에 대해서 마음에 안드는 수정이 있다면 댓글로 말해주세요!
- 3차 데모데이 코드 시작 전에 반드시 merge해야 합니다.

## 관련 이슈

closes #171 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-23 08:40 UTC, youngh0 approved these changes
리팩터링 해주셔서 감사합니다 ㅎㅎ

메서드 추출하면서 static붙은 것과, List<Coupon>을 통해 통계 데이터를 찾는 부분 말고는 딱히 이견 없습니다!!

CustomerCouponStatistics에 부여된 책임을 Coupons라는 일급컬렉션으로 옮기는 방법 반영할지 한 번 고려해주시면 감사하겠습니다 ㅎㅎ

전 이번 주는 일과시간에 바로바로 확인하기 어려우니까 어프루브 하겠습니다

고생하셨어요👍😎

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/coupon/CouponApiController.java
> +        List<CafeCustomerFindResultDto> coupons = couponService.findCouponsByCafe(cafeId);
serviceDto한 번 풀어서 주는거 전 좋다고 생각합니다~ 👍

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeCouponSettingService.java
>          Optional<Cafe> findCafe = cafeRepository.findById(cafeId);
orElseThrow로 바꿔도 될 것 같은데, 이건 지금 코드 그대로 가도 전 상관없습니다!!(기능상의 차이는 없으니까요!)

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponStatistics.java
> +    public static CustomerCouponStatistics produceFrom(List<Coupon> coupons) {
static메서드를 사용하게 되면 entity에서도 application layer에 존재하는 entity에서도 해당 메서드에 접근이 가능하게 되면서 양방향 의존이 생길 것 같아요.

그래서 이런 양방향 의존을 피하기 위해서 일급컬렉션을 적용하고 static을 제거함으로써 양방향 의존을 피할 수 있을 것 같아요!

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponStatistics.java
> +public class CustomerCouponStatistics {
통계를 내는 클래스 같은데 이 책임을 Coupons라는 일급컬렉션을 만들어서 Coupons에 할당 후 통계 정보를 담은 StatisticsDto라는 데이터 dto를 반환하도록 하는건 어떨까요?

제가 짠 부분이지만, 당시에는 급하게 짜르나 일급컬렉션을 생각하지 못했는데, 다시 생각해보니 coupon들을 통해 통계 데이터를 내는 것이니 일급컬렉션에서 수행하는 것도 자연스럽다고 생각합니다!

Service -> Coupons -> Coupon
Coupons는 StatisticsDto반환

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
> +    public static CustomerAccumulatingCouponFindResultDto from(Coupon coupon, Customer customer, boolean isPrevious) {
parameter가 여러개인 정팩메는 of로 네이밍 해주세요~~

2023-07-23 08:40 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
> +    private static String formatNicknameFromPhoneNumber(String phoneNumber) {
불필요한 static인 것 같습니다!

메서드 추출하다보면 자꾸 static붙더라구요

2023-07-23 08:40 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +    private TemporaryCustomer temporaryCustomer1;
데미데이터가 너무 많아서 저도 모르게 축약어를 썼네요..

수정해주셔서 감사합니다 ㅎㅎ

2023-07-23 08:40 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +        temporaryCustomer1 = temporaryCustomerRepository.save(TEMPORARY_CUSTOMER_1);
FIXTURE👍

2023-07-23 08:40 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +        temporaryCustomer1 = temporaryCustomerRepository.save(TEMPORARY_CUSTOMER_1);
FIXTURE👍

2023-07-24 06:02 UTC, yenawee approved these changes
깃짱 리팩터링 하느라 수고많았어요 👍

고친 부분이 깔끔깔끔해졌네요

2023-07-24 06:02 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
> +    private CustomerFixture() {
Fixture 에 기본 생성자가 필요한가여 ??

2023-07-24 06:04 UTC, jundonghyuk requested changes
안녕하세요 깃짱 리팩토링 잘해주셨네요

코멘트 그 부분에 각각 남겼습니다 ! 고생하셨어요

2023-07-24 06:04 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
> +        String nickname = formatNicknameFromPhoneNumber(phoneNumber);
저는 무엇인가 이 닉네임을 정하는 건 `temporaryCustomer`내부에서 처리해도 될 것 같다는 생각이 들어요.
임시회원의 닉네임을 정하는 규칙은 임시회원객체에서 정하는게 자연스러워 보입니다

2023-07-24 06:04 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
> +    private static String formatNicknameFromPhoneNumber(String phoneNumber) {
저도 동의합니다 :)

2023-07-24 06:04 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +    private TemporaryCustomer temporaryCustomer3;
`good`

2023-07-24 06:39 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/fixture/CouponPolicyFixture.java
> +    public static final CouponPolicy COUPON_POLICY_1 = new CouponPolicy(10, "아메리카노", 8);
매번 new로 만들지 않으면 jpa로 저장이 따로따로 안되더라고요

2023-07-24 06:47 UTC, eunkeeee reviewed
답변 남겼습니다!
공통적으로 답변은
- 이 브랜치에서 레오가 새 기능을 만들어서, 먼저 머지 후에 다같이 리뷰 반영하면 좋을 것 같습니다.

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/fixture/CustomerFixture.java
> +    private CustomerFixture() {
fixture로 클래스 만드는 일 없게 하려고 일부러 private로 별도로 넣어놨습니당

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeCouponSettingService.java
>          }
이건 취향 차이인거같은데 저는 메서드 떼는게 좀더 가독성이 좋은 것 같아요!

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +    }
그런가요! 전 뜯은게 나은 것 같아서 메서드 추출했어요

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +    }
좋은 것 같아요! 
레오가 여기서부터 브랜치를 얻었기 때문에 반영하더라도 머지 후에 반영하는게 좋을 것 같아요!

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +        Cafe cafe = findExistingCafe(cafeId);
넹 ㅎㅎ 
기존에는 response랑 dto 형태를 너무 똑같이 가져가려고 한 것 같아서 이렇게 수정했어요

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                .orElseThrow(() -> new CafeNotFoundException("존재하지 않는 카페 입니다."));
저는 솔직히 빼는게 더 좋은 것 같은데, 이부분은 하디가 원래 작성했던 부분이니깐 머지 후에 바꿔도 될 것 같아요

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
>                          isPrevious(coupon)))
오 거꾸로 생각해서 잠시 착각했슴다. 
이따 바꾸죠

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponStatistics.java
> +public class CustomerCouponStatistics {
좋은 방법인 것 같네요!

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
> +    public static CustomerAccumulatingCouponFindResultDto from(Coupon coupon, Customer customer, boolean isPrevious) {
ㅎㅎ넹~

2023-07-24 06:47 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/customer/CustomerService.java
> +        String nickname = formatNicknameFromPhoneNumber(phoneNumber);
동의합니당

2023-07-24 06:51 UTC, jundonghyuk approved these changes

2023-07-24 06:53 UTC, merged