[BE] feat: 인수 테스트 격리 템플릿을 작성한다
woowacourse-teams/2023-stamp-crush pull request #219
Opened 2023-07-25 05:09 UTC by yenawee

## 주요 변경사항

- 이전에 함께 작성했던 DataCleaner, DataClearExtension, AcceptanceTest 코드 입니다.

## 리뷰어에게...

- 이때는 인수 테스트들이 작성되어 있지 않았어서 현재 있는 인수테스트들에 이 템플릿 적용하려면 우선 머지가 되야 할 필요성이 있어서 PR 작성합니다.
- 이 템플릿 적용 시 인수 테스트 실행 시 데이터베이스 초기화되어서 테스트 격리 잘 되는거 확인했습니다. 초기에 Table 생성 안되었다고 Error 나는거는 추가 확인이 필요합니다.

## 관련 이슈

closes #77 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-25 05:16 UTC, eunkeeee requested changes
한번 이렇게 해보는거 어떨까요?!

2023-07-25 05:16 UTC, eunkeeee commented on backend/src/main/resources/application-test.yml
> +
여기 불필요한 개행은 없애주시면 좋을 것 같아요!

2023-07-25 05:16 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/AcceptanceTest.java
> +        cleaner.clear();
이 부분을 BeforeEach가 아니라 AfterEach에 넣어놓으면 잘 안될까요?!!

2023-07-25 05:16 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/AcceptanceTest.java
> +        cleaner.clear();
```suggestion
        }
        
        @AfterEach
        void clear() {
            cleaner.clear()
```

2023-07-25 05:35 UTC, eunkeeee reviewed
간단한 코멘트 남겼습니다!
제나 땡큐!

2023-07-25 05:35 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/BackendApplicationTests.java
> +@ActiveProfiles("test")
이거 꼭 필요한 어노테이션인가요!!

2023-07-25 05:35 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/common/DataCleaner.java
> +    @SuppressWarnings("unchecked")
이 어노테이션을 붙인 이유는 뭔가요??

2023-07-25 05:35 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/common/StampCrushTest.java
> +public @interface StampCrushTest {
이 어노테이션 사용 예정이 아니라면 없애도 괜찮을 것 같아요!

2023-07-25 07:51 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/common/StampCrushTest.java
> +public @interface StampCrushTest {
이거 삭제했어요 나중에 공통으로 뺄 어노테이션 생기면 그때 만들기로 ~

2023-07-25 07:54 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/common/DataCleaner.java
> +    @SuppressWarnings("unchecked")
이거 그때 같이 작성한 코드 그대로긴 한데.... 
사실 지금 발생하는 에러가 너무 많아서 어떤 워닝을 안보이게 하는지 모르겠는데 우선 놔둘게요 !

나중에 머지할때 같이 보고 지우는걸로

2023-07-25 08:29 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/BackendApplicationTests.java
> +@ActiveProfiles("test")
없앳숨다

2023-07-26 06:32 UTC, eunkeeee approved these changes
제나, 하디 열심히 디버깅하느라 정말정말 수고했습니다!
어푸루부 하겠습니당

2023-07-26 06:32 UTC, eunkeeee commented on backend/src/main/resources/application-test.yml
> +    database-platform: org.hibernate.dialect.H2Dialect
이부분을 수정하니깐 통과하는거군요!

2023-07-26 06:36 UTC, jundonghyuk approved these changes
고생하셨습니다 :)

2023-07-26 06:36 UTC, merged