[FE] feat: 커스텀 쿠폰 기능을 구현한다.
woowacourse-teams/2023-stamp-crush pull request #224
Opened 2023-07-25 15:22 UTC by regularPark

## 주요 변경사항

- 사용자가 선택한 스탬프 위치에 대한 좌표를 수집하여 payload에 싣는 기능을 구현하였습니다.
- 피그마의 가이드라인을 준수하기 위해 `StampCustomModal` 컴포넌트를 생성하여 모달 내부에서 스탬프 위치 커스텀을 설정할 수 있도록 하였습니다.
- 모달에 삽입된 div 태그 내부에서의 상대좌표를 구하기 위해서 모달의 x, y좌표가 필요했는데, 도출과정에서 필요한 `getBindingClientRect()` 메서드를 사용하기 위해 모달을 `ref`로 변환하는 과정을 거쳤습니다.

## 리뷰어에게...

실행 화면
<img width="779" alt="스크린샷 2023-07-26 오전 12 10 42" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/bcf825a5-e454-40a1-9840-7de7ad091a9c">

좌표 도출 결과
<img width="626" alt="스크린샷 2023-07-26 오전 12 11 41" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/c101a740-ca05-43ff-953b-bf0dd1b7449f">

## 관련 이슈

closes #210 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-26 10:18 UTC, 2yunseong requested changes
레고 고생하셨습니다!! ㅎㅎ 리뷰 한번 확인해주세요~~ 몸은 꽤 괜찮아졌답니다!!

2023-07-26 10:18 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +
<img width="1054" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/3fe3c877-bfb2-4c11-b91a-0aafaeae2301">

길이 체크를 length 보다 크거나 같을 때로 변경해야 될거같아요! 하나가 더찍히는 이슈가 있네요

2023-07-26 10:18 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomCouponDesign/index.tsx
> +
추가로 이미지가 업로드 되지않는다면 모달진입을 제한하는 로직도 있다면 좋겠군요!!

2023-07-27 01:46 UTC, regularPark commented on frontend/src/pages/Admin/CustomCouponDesign/index.tsx
> +
좋은 피드백 감사합니다! 반영하였습니다.

[02fb285](https://github.com/woowacourse-teams/2023-stamp-crush/pull/224/commits/02fb285c6a1b992c4f019136c0c3e4349c83bf5f)

2023-07-27 01:46 UTC, regularPark commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +
해당 부분 수정하였습니다😭

[e6c31d3](https://github.com/woowacourse-teams/2023-stamp-crush/pull/224/commits/e6c31d3e76e3d61466b3986e043bb37915f49aa2)

2023-07-27 07:56 UTC, kangyeongmin approved these changes
와... 정말*10000
수고하셨어요!!!!! 
리뷰 남긴것들 확인해주세요~!

2023-07-27 07:56 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +  };
event -> e로 통일하는 것이 어떤가요?

e로 적는 방안이 코드가 짧아져서 가독성이 좋은 것 같아요!

2023-07-27 07:56 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +    setStampPos(updatedStampPos);
명령형보다 선언형을 지향하는 것이 어떨까요?!

2023-07-27 07:56 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/style.tsx
> +};
1. 왜 type으로 선언하셨나요?
2. Styled관련 props는 $를 붙인다와 네이밍에 Styled를 붙이자는 컨벤션이 안지켜진거 같아요!

2023-07-27 08:05 UTC, regularPark commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +    setStampPos(updatedStampPos);
코드의 길이가 길어서 setStateAction 넣어야 할 것 같다는 생각에는 동의합니다. 굳이 할당할 필요가 없으니까요?
그런데 명령형 선언형 중에서는 명령형에 가깝지 않나 싶어요? (정확히 잘 모르겠지만?) 암튼 그렇슴당

[8ad02d3](https://github.com/woowacourse-teams/2023-stamp-crush/pull/224/commits/8ad02d3d6b733ac14e54d6385c868110d116e95e)

2023-07-27 08:29 UTC, regularPark commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/style.tsx
> +};
코드 컨벤션 준수!

[2347645](https://github.com/woowacourse-teams/2023-stamp-crush/pull/224/commits/2347645c33ad3ed81f8fba3e26ff8e9e6e0ddff7)

2023-07-27 08:32 UTC, regularPark commented on frontend/src/pages/Admin/CustomCouponDesign/StampCustomModal/index.tsx
> +  };
`event` => `e`로 변경하였읍니다!

[199ef4a](https://github.com/woowacourse-teams/2023-stamp-crush/pull/224/commits/199ef4a068f6fa6f76e352163931699d93c7c398)

2023-07-27 10:23 UTC, 2yunseong approved these changes
굿굿!!

2023-07-27 18:04 UTC, merged