[BE] feat: 카페 정보 수정 API를 구현한다.
woowacourse-teams/2023-stamp-crush pull request #243
Opened 2023-07-26 13:50 UTC by youngh0

## 주요 변경사항

- cafe controller, service에 기능 관련된 코드가 추가 됐습니다.
- update는 변경감지를 통해 진행했고, Cafe엔티티 안에 update메서드를 만들었습니다.
- update메서드에서 dto참조는 일부러 안했습니다! 도메인이 dto를 참조하는게 좋다고 생각하지 않기 때문입니다.

## 리뷰어에게...

- 제가 구현한 API스펙의 introduction이 현재 Cafe엔티티에는 없습니다. 추가를 할까 하다가 테이블을 건드리는 일이라 정확한 진행상황을 모르는 제가 추가하기엔 애매하다고 판단되어 우선 introduction을 빼고 진행했습니다.

- 인수 테스트 역시 템플릿 등 인수 테스트를 어떻게 진행하기로 했는지 파악하지 못하고 있기 때문에, 생략했습니다. 이 부분은 파악하는대로 제가 코드 작성하겠습니다.

## 관련 이슈

- openTime, closeTime관련 유효성 검증을 어떤 방식으로 하는게 좋을지 얘기해보면 좋을 것 같아요. 제가 생각한 유효성 검증이 필요한 것은 1. Null인지 2. hour(0~24), minute(0~60)의 범위 검증 3. closeTime이 openTime보다 늦는지. 이 정도가 있는 것 같아요. 이걸 커스텀 어노테이션으로 할 수도 있고, 생성자 안에서 할 수도 있을 것 같은데 어디서 하는게 괜찮다고 생각하시나요?

정해지는대로 코드 치겠습니다!

유효성 검증과, 인수 테스트를 제외하니 코드는 얼마 안되네요.. 배려해주셔서 감사합니다 ㅎㅎ
내일 일과시간에 리뷰 해주시면 예비군 끝나고 수정하기 위해서 미리 PR올리겠습니다! 

closes #231 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-27 06:28 UTC, yenawee requested changes
예비군 갔다와서도 코드 구현해주느라 수고하셨습니당 레오 👏

유효성 검사랑 Cafe 엔티티에 소개글 필드 추가해야 하니까 Request Changes 합니당

2023-07-27 06:28 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +public class CafeUpdateRequest {
저는 openTIme, closeTime 관련

1. null 검사
2. 올바른 분, 초 값인지
3. closeTime 이 openTime 보다 뒤의 시간이어야 하는지

에 대한 검증은 이 객체에서 커스텀 어노테이션으로 하는게 더 좋다고 생각합니다

저 3개의 검증은 비지니스 로직이 아닌거같아서요!

2023-07-27 06:28 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
> +    private LocalTime openTime;
얘네들 값 바뀔일 없을거같은데 final 해도 되지 않을까여 ??

2023-07-27 08:03 UTC, jundonghyuk requested changes
각 코드 부분에 커멘트 남겼습니다 ~!

2023-07-27 08:03 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
> +        this.openTime = openTime;
좀 더 괜찮은 네이밍은 없을까요 ?

사실 들어온건 부가적인 정보인데 `update`라고만 하면 어느정보를 업데이트해야하는지 헷갈린다 ? 느낌이 있습니다.

2023-07-27 08:03 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +}
이미지 url 등 다른 정보들 중에 선택사항이 있는걸로 알고 있는데, 꼭 모든 필드가 들어와야되는 정보인가여 ?

2023-07-27 08:49 UTC, eunkeeee requested changes
레오 예비군 와중에도 수고하셨습니다!_!_!
몇 가지 수정 요청했는데 반영하고 다시 알려주세요!

cf. 저번에 봤던 것 같은데 hadi 아니고 hardy 아니었나요?
하디가 서운해할듯 ㅎ

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        );
이 부분을 `CafeUpdateRequest ` 내부에서 만들어서 반환하는건 어떨까요?

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +            @RequestBody @Valid CafeUpdateRequest cafeUpdateRequest
사소한 건데 다른 컨트롤러에서 파라미터 이름은 `request`로 쓰고있어요! 
(딱 정한건 아닌데 어쩌다보니..? 한 번 말은 나왔던 듯)
취향이 확고한거 아니라면 통일 하는것도 괜찮을 지도?!

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +public class CafeUpdateRequest {
1.은 이미 되고 있는 것 같고
3.은 말도안되는 상황인건 동의하는데 어노테이션으로 검증 가능한 내용일까요?!

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
> +    private LocalTime openTime;
동의! DTO 불변 객체로 만들어도 좋을 것 같슴니당

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
> +    // introduction이 현재 Cafe엔티티에 없음
introduction을 Cafe entity에 추가하는게 좋을까요? 
점점 정보가 무거워져서 나중에 CafeInfo같은 테이블로 분리하게 될 수도 있을 것 같다고 생각함니당

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
> +        this.openTime = openTime;
제안 하나 해보겠습니다

사업자등록번호 등등 진짜 좀 법적으로 중요한 것들을 keyInformation,
고객에게 보여지는 이런 잘못썼다고 고소 안당하는 내용들을 additionalInformation이라고 하는거 어떨까요?

`updateAdditionalInformation`으로 제안합니다!

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
> +        this.openTime = openTime;
(혼란스러울 수 있어서 일단 다른 사람들과 모두 이야기해보면 좋을 것 같은데)

Cafe Information을 일부 수정할 때, 
soft delete하고 insert VS 지금처럼 일부만 update 
저희가 소프트 딜리트를 가져가기로 했어도 이정도는 괜찮은 걸까요?

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
>                          "하디까페",
까페... 카페 가능할까요? @jundonghyuk 이 쓴거지만..

2023-07-27 08:49 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
> +        assertThat(hadiCafe.getCafeImageUrl()).isEqualTo(cafeUpdateDto.getCafeImageUrl());
여러 개 중에 이 한가지만 테스트해볼건가요?!! 
나머지도 다 테스트해보는건 어떤가요!

2023-07-30 13:00 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        );
그렇게 되면 serviceDTO가 controller dto를 알게 되어서 일부러 풀어서 작성했습니다!

CafeUpdateDto.from(request); 형태로 이해하고 답변했습니다. 제가 잘못 이해한거면 말씀해주십셔~

2023-07-30 13:03 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +}
노션 API문서에 해당 내용이 없더라구요. 제가 회의할 때 예비군이라 내용 숙지가 안되어있어서 일단 다 저렇게 했는데 월욜에 물어보고 수정하겠습니다~

2023-07-31 03:31 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        );
노놉!

`CafeUpdateDto.toServiceDto()` 이 형태를 말한 겁니당!

2023-07-31 03:32 UTC, eunkeeee requested changes
답글임당! 
나머지 대댓 남겨주거나 사소한 수정 하면 바로 어푸루부 하겠습니당!

2023-07-31 03:34 UTC, yenawee approved these changes
어푸룹

2023-07-31 05:49 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        );
반영했습니다~

2023-07-31 05:50 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +public class CafeUpdateRequest {
아까 얘기한 결과 따로 검증 안하기로 해서 그대로 냅뒀습니다

2023-07-31 05:50 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +    private LocalTime closeTime;
빈 값이 없어야하는건데 string에만 적용되는 것 같기도 해서 제거 했습니다~

2023-07-31 05:50 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
> +    private LocalTime openTime;
반영했습니다~

2023-07-31 05:51 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeUpdateDto.java
> +    // introduction이 현재 Cafe엔티티에 없음
음 그럼 지금 당장은 따로 분리하긴 애매한 것 같은데 그냥 Cafe에 넣는거 어떠신가요?

2023-07-31 05:51 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/Cafe.java
> +        this.openTime = openTime;
부가 정보가 additional infomation이니 깃짱의견 반영하겠습니다!

2023-07-31 05:51 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
> +        assertThat(hadiCafe.getCafeImageUrl()).isEqualTo(cafeUpdateDto.getCafeImageUrl());
나머지 값 테스트 완료했습니다!

2023-07-31 06:59 UTC, eunkeeee approved these changes
굿입니다 굿굿굿~

2023-07-31 06:59 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/request/CafeUpdateRequest.java
> +    public CafeUpdateDto toServiceDto() {
👍

2023-07-31 07:07 UTC, jundonghyuk approved these changes

2023-07-31 07:09 UTC, merged