[BE] feat: 2차 데모데이 구현 코드에서 사장님 인증이 필요한 API Controller 에 Basic 인증을 추가한다(임시)
woowacourse-teams/2023-stamp-crush pull request #249
Opened 2023-07-27 04:30 UTC by yenawee

## 주요 변경사항

- 2차 데모데이 구현 코드 중에 사장님 인증이 필요한 API Controller 에 Basic 인증을 추가한다
- 현재 구현되어있는 인수테스트, 통합테스트에 헤더 인증을 추가합니다

## 리뷰어에게...

- 꼼꼼히 봐주시면 감사하겠습니다 🙇‍♀️ (ArgumentResolver 너무 오랜만에 구현해봐서 미심쩍어요....)
- 추가 얘기나누고 싶은 부분은 코드 리뷰에 남겨두겠습니다

## 관련 이슈

closes #230 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-27 04:40 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +    ResponseEntity<CafesFindResponse> findAllCafes(Owner owner, @PathVariable Long ownerId) {
이제 PathVariable 로 들어오는 ownerId 를 제거해야 할텐데 지금은 우선 Basic 인증만 추가하는 PR 이라 수정하지 않았습니다

2023-07-27 04:40 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeCouponSettingApiController.java
> +                                                        @RequestParam("cafe-id") Long cafeId,
@RequestParam 으로 들어오는 cafeId 가 owner 의 것인지 확인하는 코드 추가가 필요한데 Basic 인증만 추가하는 PR 이라 
서비스 코드까지 수정하면 너무 범위가 넓어질거같아 (제가 아직 완벽하게 로직을 파악하지 못하고 있어서)
수정하지 않았습니다

2023-07-27 04:40 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/config/OwnerArgumentResolver.java
> +        String encryptedPassword = credentials[1];
Owner 는 암호화된 비밀번호를 가지고 있을텐데 입력해주는 비밀번호는 암호화되지 않았을 때라서 어떻게 할지 생각하다가 우선 암호화 관련한 로직은 제외하고 작성했습니다

2023-07-27 04:40 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeCouponSettingIntegrationTest.java
> +                "gitchan",
loginId 와 password 가 한글로 되있으면 Base64 인코딩이 제대로 먹지가 않아서 (UTF-8 설정 해줘도)
우선 영어로 고쳐놨는데 동일한 문제를 경험해보신 분 계실까요 🤔

2023-07-27 07:34 UTC, jundonghyuk requested changes
코멘트 남겼습니다 ! 

DIspatcherServlet에서 -> Controller로 들어오는 과정을 테스트하기 위한 컨트롤러 단위 테스트도 있으면 더욱 좋을 것 같네여

2023-07-27 07:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/config/OwnerArgumentResolver.java
> +            return null;
해당작업은 Header정보가 있냐를 판별하는 것 같은데요, 이 로직은 저는 개인적으로 이보다 더 앞단에서 처리하는게 어떨까 싶어요.
`ArgumentResolver`의 역할에서 조금 벗어난것 같습니다.

그리고 헤더정보가 없으면 `null`을 리턴하는데, 이러면 컨트롤러에 `Owner`에 null이 들어가는것인가요 ?

애초에 이런상황이면 예외를 터트려서 핸들링 해주는건 어떻게 생각하시는지요

2023-07-27 07:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/config/OwnerArgumentResolver.java
> +        return owner;
로그인 관련되어 구체적인 예외메시지를 전달하면 조금 보안상의 이슈가 있을것같아요.

`회원정보가 잘못되었습니다.`라는 좀 더 넓은 메시지를 전달해도 될 것 같아요.

2023-07-27 07:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
> +        }
비밀번호가 일치하지 않다는 예외메시지는 조금 위험한 메시지라고 생각합니다.

인증이 안되었으면 그냥 모든 예외메시지를 `아이디와 패스워드를 다시 확인 후 로그인해주세요.`라든지 일반적인 메시지를 던지는게 더 

좋아보여요.

2023-07-27 07:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/config/CustomerArgumentResolver.java
> +        String authorization = webRequest.getHeader(HttpHeaders.AUTHORIZATION);
커스토머도 똑같으니 `OwnerArgumentResolver`에서 남긴 커멘트로 대체하겠습니다 !

2023-07-27 07:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/customer/CustomerApiController.java
> +    public ResponseEntity<CustomersFindResponse> findCustomer(Owner owner, @RequestParam("phone-number") String phoneNumber) {
한 곳만 남기겠습니다 !

엔티티를 그대로 받는 것 보다 OwnerRequestDto등 Dto로 받는건 어떻게 생각하시나요 ?

2023-07-27 09:00 UTC, eunkeeee requested changes
제나 수고했슴당!
코멘트 남겼어요 ㅎㅎㅎ

2023-07-27 09:00 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +        owner = ownerRepository.save(new Owner("jena", "jenaId", "jnpw1234", "01098765432"));
OwnerFixture 쓰고있는데, 가능하면 이 내용으로 픽스쳐 추가하거나 옮겨도 좋을 것 같아용

2023-07-27 09:00 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/SampleCouponIntegrationTest.java
> +        owner = ownerRepository.save(new Owner("jena", "jenaId", "jnpw1234", "01098765432"));
픽스쳐 가능??

2023-07-29 03:38 UTC, youngh0 requested changes
고생하셨습니다 제나!

예비군 때문에 바로 리뷰 못해서 죄송합니다🥲
이미 다른 크루분들이 리뷰 해주셔서 제가 새롭게 드릴 리뷰가 없네요.. 다른 크루분들의 의견에 동의하는 정도입니다!!

고생하셨어요😎

2023-07-29 03:38 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/OwnerArgumentResolver.java
> +            return null;
저도 이 부분은 예외처리를 하는게 확실할 것 같아요

2023-07-29 03:38 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/customer/CustomerApiController.java
> +    public ResponseEntity<CustomersFindResponse> findCustomer(Owner owner, @RequestParam("phone-number") String phoneNumber) {
api -> application -> entity 이런 식으로 의존성 흐름을 철저하게 지킬거면 dto로 받는게 좋아보입니다!

2023-07-29 03:38 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/CustomerArgumentResolver.java
> +        String authorization = webRequest.getHeader(HttpHeaders.AUTHORIZATION);
궁금하긴 하네요

2023-07-29 03:38 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/OwnerArgumentResolver.java
> +        Owner owner = ownerRepository.findByLoginId(loginId).orElseThrow(() -> new OwnerUnAuthorizationException("카페 사장님 계정으로 로그인이 필요합니다"));
이 윗 부분 까지는 owner, customer모두 인증하기 위해 동일한 로직이 수행되어야 하기 때문에 깃짱과, 하디 의견처럼 interceptor로 빼는 것도 좋아보입니다!

2023-07-29 13:52 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/config/CustomerArgumentResolver.java
> +        String authorization = webRequest.getHeader(HttpHeaders.AUTHORIZATION);
`supportParameter`가 아마 그역할을 하지 않을까싶어요

2023-07-31 07:02 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/config/CustomerArgumentResolver.java
> +        String authorization = webRequest.getHeader(HttpHeaders.AUTHORIZATION);
@yenawee 

처음에 내가 리뷰했을 때 OwnerAuth, CustomerAuth 분리 안되어있다가
나중에 만든거 맞죠!?!?!?!

2023-07-31 07:03 UTC, eunkeeee approved these changes
수고했슴당 제나! 
쾌유하시길

2023-07-31 07:42 UTC, youngh0 approved these changes

2023-08-01 01:33 UTC, merged