[BE][미완성] feat: 쿠폰 리스트(고객 모드)를 조회한다.
woowacourse-teams/2023-stamp-crush pull request #250
Opened 2023-07-27 04:35 UTC by eunkeeee

## 주요 변경사항

- 고객 모드에서 자신이 가지고 있는 쿠폰을 스크롤해서 볼 수 있는 메인 페이지

### Request

**Header** 

```http
GET /api/coupons

Authorization: username@password Base64 (customer)
```

### Response

**Header** 

```http
HTTP/1.1 200 OK
```

**Body**

```json
{
	"coupons" : [ 
		{
			"cafeInfo": {
				"id": 1,
			        "name": "우아한카페",
				           },
			"couponInfos": [ 
				{
                                         "id": 1,
					"isFavorites": true,
					"status": "ACCUMULATING" ("REWARDED", "EXPIRED"),
					"stampCount" : 3,
					"maxStampCount" : 8,
					"rewardName": "아메리카노",
					"frontImageUrl": "http://localhost:3000",
					"backImageUrl" : "http://localhost:3000",
					"stampImageUrl" : "http://localhost:3000",
					"coordinates" : [
							{
								"order" : 1,
								"xCoordinate" : 2,
								"yCoordinate" : 5
							},
							{
								"order" : 2,
								"xCoordinate" : 5,
								"yCoordinate" : 5
							}
			                   ],
		                 }
                          ] // 쿠폰은 일단 ACCUMULATING인 것 1장만 
	],
        // 카페 여러 개 가능...
}
```

- 상세페이지 이동시 `cafeId`로 카페 정보 조회할 것

<br/>

## 작업 내용

- 한 번의 요청으로 이 페이지에 대한 모든 내용을 받아오기로 함.
- 현재 즐겨찾기 관련 테이블이 없어서 우선은 `false`를 넣어두겠음.

## 리뷰어에게...

## 관련 이슈

closes #228

## 체크리스트

- [ ] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-27 07:24 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +    void 쿠폰_디자인에_읽기_전용인_좌표를_조회한다() {
@jundonghyuk 
@youngh0 

여기있슴다!

![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/15c3cf97-fc5c-4428-8126-0ac45645622a)

2023-07-27 08:00 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
> +    @Disabled
coupon.accumulate()하는 과정에서 읽기 전용인 stamps 사용해서 일어나는 문제인 것 같습니다!

2023-07-28 06:09 UTC, yenawee requested changes

2023-07-28 07:06 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        sampleStampCoordinateRepository.save(new SampleStampCoordinate(1, 100, 100, defaultSampleBackImage));
맞아요..! 일단 테스트용으로 이렇게 넣어놨는데, 필요하면 변경하도록 할게요

2023-07-28 07:06 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/step/CafeCreateStep.java
> +public class CafeCreateStep {
인수테스트는 step이라고 빼는게 국룰(?)이라고 하더라고요

2023-07-29 04:53 UTC, youngh0 approved these changes
안녕하세요 깃짱! 구현하시느라 고생하셨습니다👍

service로직에선 특별히 리뷰할게 없네요 ㅎㅎ
테스트에서 양방향 못 불러오는건 제가 직접 돌려보고 제 생각을 적어놨는데 확인 부탁드립니다!
그래서 이번건 바로 어프루브 하겠습니다!! 고생하셨어요😎

2023-07-29 04:53 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponFindService.java
> +        if (findCustomer.isEmpty()) {
혹시 orElseThrow어떠신지요..?

2023-07-29 04:53 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerCouponFindResultDto.java
> +        public static CafeInfoDto of(Cafe cafe) {
파라미터가 하나인 정팩메는 of대신 from으로 부탁드립니다!

2023-07-29 04:53 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +    private void getAddCouponStampCoordinate(List<CouponStampCoordinate> coordinates, CouponDesign couponDesign) {
그냥 addCoupon~~ 네이밍은 어떨까요??

반환타입이 void라 get이 조금 어색하네여

2023-07-29 04:53 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +                () -> assertThat(couponStampCoordinates).isNotEmpty(),
이건 성공

2023-07-29 04:53 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +                () -> assertThat(couponStampCoordinates).containsExactlyInAnyOrder(coordinates)
이건 실패

2023-07-29 04:53 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +    void 쿠폰_디자인에_읽기_전용인_좌표를_조회한다() {
제가 직접 해당 테스트 돌려보고 실패하는 이유를 보니까 2개의 assertThat중 `assertThat(couponStampCoordinates).containsExactlyInAnyOrder(coordinates)`이게 실패하고 `assertThat(couponStampCoordinates).isNotEmpty()`이건 성공하네요.

양방향으로 걸려있는 애들을 못 읽어오는 문제는 아닌 것 같아요.

추가적으로 제 추측으론 em.clear()로 인해 jpa가 동일성을 보장해주지 않기 때문인 것 같아요. 실제 id값은 coordinates와   List< CouponStampCoordinate>안에 있는 객체의 id가 동일합니다.

em.clear를 하기전에 61라인에서 `getAddCouponStampCoordinate()`호출을 통해 coordinate를 save합니다. 이후 em.clear를 하고 `couponRepository.findById.getCouponDesign().getCouponStampCoordinates()`을 호출 하면서 동일성 보장을 안해주기 때문에 `containsExactlyInAnyOrder`테스트만 실패하고 있는 것 같아요.

2023-07-29 06:21 UTC, eunkeeee reviewed
레오 꼼꼼한 코멘트 감사합니당
덕분에 JPA에 대한 학습도 동시에 되고 있는 늣김〰️

2023-07-29 06:21 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponFindService.java
> +        if (findCustomer.isEmpty()) {
난 지금 이게 좋슴다!

2023-07-29 06:21 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerCouponFindResultDto.java
> +        public static CafeInfoDto of(Cafe cafe) {
맨날 헷갈리는데 
파라미터 하나면 from, 
여러개면 of인건가요?!!

2023-07-29 06:21 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +    void 쿠폰_디자인에_읽기_전용인_좌표를_조회한다() {
지난번에 하디랑 한 번 말했었는데,

양방향 매핑이 내가 지금 계속 헷갈려서..ㅋㅋㅌㅌ
지금 생각하고 있는 개념으로는

- 조회는 가능. 단지 lazy 하게 로딩되기 때문에 단지 getter로 호출할 때는 안되지만, 이후에 가져온 List로 다른 로직을 진행하면 그제서야 불러옴
- MappedBy로 설정해둔 쪽에만 추가할 경우에는 jpa에서 변경을 감지하지 않기 때문에 update하고 싶으면, 연관관계의 주인 쪽에 변경을 줘야함.

현재 이렇게 이해하고 있는데 레오가 생각하는거랑 동일한가요??

> 추가적으로 제 추측으론 em.clear()로 인해 jpa가 동일성을 보장해주지 않기 때문인 것 같아요. 실제 id값은 coordinates와 List< CouponStampCoordinate>안에 있는 객체의 id가 동일합니다.

맞습니당 
clear 이전까지는 영속성 컨텍스트에서 1차 캐시해둔 객체를 바로 불러와서 객체의 참조값까지 같은 상태지만, 
clear 이후에는 데이터베이스에서 직접 가져오기 때문에 참조값이 달라져서 List.contains는 equals가 재정의되지 않은 상태에서는 참조값이 동일한지를 보기 때문에 실패합니다! 

레오가 생각한 이유가 정확한게, equals를 재정의하는 경우에는 테스트가 통과함니다

2023-07-29 07:20 UTC, yenawee commented
고생햇아여 깃짱

2023-07-29 07:21 UTC, yenawee approved these changes
고생햇어요 깃짱

2023-07-29 07:34 UTC, youngh0 requested changes
반영이 상당히 빠르시네요. 정신을 못 차리겠습니다 ㅎ

테스트 코드 통과를 위해 equals재정의 하신 것 같은데, 저는 해당 코드가 너무 테스트만을 위한 코드라고 생각합니다! 그래서 그냥 제가 생각한 코드를 적어봤는데 한 번만 확인해주세요!!

리퀘스트 체인지 해야하나 어프루브 해야하나 고민되는데 일단 리퀘스트 체인지 할게요 ㅎㅎ 해당 부분 확인 해주시고 깃짱 의견만 말씀해주시면 바로 어프루브 날리겠습니다~

2023-07-29 07:34 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CustomerCouponFindService.java
> +        if (findCustomer.isEmpty()) {
오케이~ 문제있는건 아니니깐 좋아요~

2023-07-29 07:34 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +    void 쿠폰_디자인에_읽기_전용인_좌표를_조회한다() {
음 일단 저도 양방향 매핑으로 된 경우 프록시로 조회하는지에 대해서는 파보지 않아서 뭐라 말하기가 좀 그렇네요.. 저도 잘 몰라서 하하 공부하고 공유해보죠 ㅎ

2023-07-29 07:34 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerCouponFindResultDto.java
> +        public static CafeInfoDto of(Cafe cafe) {
예압 이그잭틀리

2023-07-29 07:34 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +
제 의견을 한 가지만 더 얘기하자면 테스트를 위한 equlas, hashcode재정의 보단 
`CouponStampCoordinate findCoordinates = couponStampCoordinateRepository.findById(coordinates.getId()).get();`이렇게 찾아오고 assertThat의 `containsExactlyInAnyOrder(findCoordinates)`는 어떨까요?

너무 테스트를 위한 equals재정의인 것 같아요!

2023-07-29 14:03 UTC, jundonghyuk requested changes
주로 테스팅에 관련해 리뷰남겼습니다~_~ 고생하셨어여

2023-07-29 14:03 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
> +        Cafe jenaCafe = cafeRepository.findById(jenaCafeId).get();
아마 이 카페도 레포지토리를 통해 조회해왔으므로, jenaCafe.getCafePolicy. ~~를 해서 접근을하려하면 레이지로딩 익셉션이 날 것 같네요.

그래서저는 조회또한 api 요청을 통해서 해야한다고 생각합니다.

만약 레포지토리를 통해서 조회해 오고 싶다면, 트랜잭셔널을 걸어야 로딩이 잘 될것 같은데요.

그런데, 현재 `Owner`를 삽입하는 api가 존재하지 않아 막막한것 같습니다.

2023-07-31 03:08 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerCouponFindResultDto.java
> +        public static CafeInfoDto of(Cafe cafe) {
앞으로 좀 외우두겠슴다 맨날 반대로 하는듯

2023-07-31 03:10 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/repository/coupon/CouponRepositoryTest2.java
> +
테스트 위해서 equals 재정의한건 이 브랜치가 아니라 여기서 나온 다른 브랜치임다! 걱정하지 않아도 됩니당
한번 레오가 말해준 방법대로 현재 브랜치에서 테스트 통과하도록 업데이트할게요

2023-07-31 06:16 UTC, eunkeeee reviewed
이거좀도와줘여

2023-07-31 06:16 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
> +        // given
깨닫. 

아래 내용 맞나요? 
![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/774f4c5a-5a40-4415-977b-63616f4e4891)

2023-07-31 06:30 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerCouponFindAcceptanceTest.java
> +        // given
지금

1. Transactional 어노테이션 붙이면 -> LazyLoading 관련 문제는 해결되는데, owner가 저장이 안되고 있어서 ownerId 관련 검증에서 에러 남.
2. Transactional 어노테이션 안붙이면 -> LazyLoading 관련 문제 남

2023-07-31 07:15 UTC, jundonghyuk approved these changes

2023-07-31 07:16 UTC, youngh0 approved these changes

2023-07-31 07:16 UTC, merged