[BE] feat: 고객 모드에서 카페 정보를 조회하는 API 를 구현한다
woowacourse-teams/2023-stamp-crush pull request #255
Opened 2023-07-27 08:13 UTC by yenawee

## 주요 변경사항

- 고객 모드에서 카페 정보를 조회하는 API 를 구현했습니다 

## 리뷰어에게...

- 단순 카페 정보를 조회해오는 API 라서 도메인, 레포지토리, 서비스 테스트 코드를 어떻게 구현해야 할지 모르겠어서 통합테스트만 있습니다

## 관련 이슈

- 기존 CafeApiController 가 있는데 해당 컨트롤러는 /api/admin 으로 사장님 모드일때의 API 를 모아둬서 고객 모드일때는 따로 객체를 빼야 할 거 같아 우선 CafeController 를 하나 만들었습니다 (머지 컨플릭트도 안나게 하려고)
- DTO 네이밍도 기존 사장님 모드의 내 카페 조회와 이름이 겹쳐서 짓기 어려웠습니다,,  사장님 모드일때와 고객 모드일때의 분리가 필요해보입니다 
- 코드 리뷰 잘 부탁드려용

closes #227 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-27 09:33 UTC, eunkeeee requested changes
코드가 엄청 깔끔하네요! 
간단한 코멘트 남겨놨습니당! 확인해주세요

2023-07-27 09:33 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/response/CafeInfoFindResponse.java
> +public class CafeInfoFindResponse {
나는 앞에 Customer를 붙여서 일단 구분해놨어요
`CustomerCafeInfoFindResponse`

2023-07-27 09:33 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeInfoFindByCustomerResultDto.java
> +//  private final String introduction;
introduction도 entity에 추가해서 넣으면 좋을 것 같아요!

2023-07-27 09:33 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +                .get("/api/cafes/" + 1)
1을 지역변수로 넣어서 설명을 좀 넣어줘도 좋을 것 같아요!

2023-07-29 07:18 UTC, youngh0 approved these changes
고생하셨습니다!!

PR본문에 써주신 패키지 분리는 금요일에 논의한 내용이라 별도의 리뷰는 하지 않았습니다! 그러다 보니 리뷰할게 없더라구요 하하. service로직도 막 복잡하지 않고, dto간 변환도 정팩메로 깔끔하게 작성해주신 것 같아요 ㅎ

다만, 테스트 코드에서 restassured부분을 별도의 private메서드로 추출한거에 대해 제 생각을 남겼는데 확인해주시면 감사하겠습니다!!

별다른 리뷰 내용이 없어서 어푸르브 할게요!! 고생하셨습니다👍

2023-07-29 07:18 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +    private ExtractableResponse<Response> requestFindCafeByCustomer(Long cafeId) {
실질적으로 restassured를 이용해 요청을 보내는 부분인데 별도의 private메서드로 빼는게 테스트 내용을 직관적으로 파악하기에는 조금 더 안좋을 수도 있을 것 같아요!
실제 조회 테스트를 하기 위한 더미데이터 생성 같은 경우는 별도의 메서드로 추출하는게 더 좋을 수 있지만, 실제 테스트 로직을 별도의 메서드를 추출하면 해당 메서드를 봐야 테스트 내용을 알 수 있기 때문에 가독성 측면에서 조금 불리하다고 생각합니다!

이건 다른 분들 의견도 들어보고 과반수에 따르겠습니다! 치명적인건 아니니깐요😎

2023-07-29 14:09 UTC, jundonghyuk requested changes
제나 깔끔하게 구현해주신것같아여 한개의 코멘트 남겼습니다.

2023-07-29 14:09 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        return CafeInfoFindByCustomerResultDto.from(cafe);
깔끔하네요..!

2023-07-29 14:09 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +                "10-222-333",
레포지토리로 세이브한건, 현재 `Owner`회원가입 기능 및 api가 없어서 일까요 ?

2023-07-31 05:15 UTC, yenawee reviewed
리뷰 반영햇습니다

2023-07-31 05:15 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +                "10-222-333",
네엡.. 카페 저장하려면 Owner 가 필요한데 Repository 로 save 하는 방법밖에 없었어요

2023-07-31 05:15 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +                .get("/api/cafes/" + 1)
좋은 발견이에요

2023-07-31 05:15 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CafeIntegrationTest.java
> +    private ExtractableResponse<Response> requestFindCafeByCustomer(Long cafeId) {
아 보통 E2E 테스트 작성할때 이렇게 private 메서드로 빼서 여러번 사용해서 습관적으로 private 으로 뺐는데 테스트 한개밖에 없어서 가독성이 오히려 안좋아졌을수도 있겠네여....

이거 근데 나중에 다른데서 쓰일 수도 있어서 우선 다시 합쳐놓진 않을게용..

2023-07-31 06:56 UTC, eunkeeee approved these changes

2023-07-31 07:17 UTC, jundonghyuk approved these changes

2023-07-31 07:25 UTC, merged