[FE] 사장님 페이지 헤더 컴포넌트 구현
woowacourse-teams/2023-stamp-crush pull request #32
Opened 2023-07-10 10:34 UTC by 2yunseong

## 주요 변경사항
close #6
- 사장님 페이지 로고를 추가했습니다.
- 현재는 로그인 상태가 없으므로 로그인Link를 고정해두었습니다. 추후 로그인 상태에 따라 컴포넌트를 다르게 하면 될 것 같습니다
## 리뷰어에게...
아래 사진 첨부합니다.
<img width="1675" alt="Screenshot 2023-07-10 at 19 30 58" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/243fcbfc-81e9-437a-b6f8-743019062ebb">

2023-07-11 01:20 UTC, kangyeongmin requested changes

2023-07-11 01:20 UTC, kangyeongmin commented on frontend/src/components/Header.tsx
> +      <LoginLink to="/login">로그인</LoginLink>
헤더에서 보여야하는 것은 '로그아웃' 아닐까요?

현재 로그인 상태가 되지 않으면 아예 페이지 진입이 되지 않는 것으로 시안이 되어 있는 것 같아요~

2023-07-11 05:32 UTC, 2yunseong commented on frontend/src/components/Header.tsx
> +      <LoginLink to="/login">로그인</LoginLink>
확인했습니다~~!! 일단은 로그아웃에 관한 자세한 사항이 없으므로 더미 컴포넌트를 넣어두겠습니다!

2023-07-11 06:02 UTC, regularPark approved these changes

2023-07-12 04:21 UTC, kangyeongmin approved these changes

2023-07-12 06:41 UTC, regularPark approved these changes

2023-07-12 06:42 UTC, merged