feat: `Input` 컴포넌트 생성
woowacourse-teams/2023-stamp-crush pull request #35
Opened 2023-07-11 01:19 UTC by regularPark

## 주요 변경사항

- `Input` 컴포넌트 생성하였습니다.
- 입력값 검사는 일단 maxLength에 대해서만 하도록 하였습니다.
- 스타일은 `basic`과 `underlined` 두 가지로 프리셋을 구성해두었습니다.

## 리뷰어에게...

2023-07-11 01:29 UTC, kangyeongmin requested changes

2023-07-11 01:29 UTC, kangyeongmin commented on frontend/src/components/Input.tsx
> +  const handleInputChange: ChangeEventHandler<HTMLInputElement> = (event) => {
현재 함수가 길이를 검사하고 있는 것 같은데
컨벤션에서 정한 대로, 핸들러 네이밍을 바꿔보면 어떨까요? (ex. checkValueLength)

그리고 현재 조건문의 return 역할은 무엇일까요?

2023-07-11 01:43 UTC, regularPark commented on frontend/src/components/Input.tsx
> +  const handleInputChange: ChangeEventHandler<HTMLInputElement> = (event) => {
해당 함수는 다시 동작시켜보니 제가 만든 함수가 아닌 html 요소의 기능으로 maxLength가 동작하고 있는 것을 확인하고 제거하였습니다😭

[0f56abb](https://github.com/woowacourse-teams/2023-stamp-crush/pull/35/commits/0f56abb9daff62695b52f709261c2fac3c107f38)

2023-07-11 01:54 UTC, regularPark commented on frontend/src/components/Input.tsx
> +Input.displayName = 'Input';
eslint에서 `forwardRef`를 사용하면 missing displayName 오류가 발생하여서 넣어주었는데요. `forwardRef()` 내부에 익명함수를 넘겨주어서 그렇다는 것 같네요. 이 방법 말고도 

```typescript
export default Input = forwardRef({ref 관련 함수})
```

이런식으로도 구현할 수 있는데 라잇은 어떤 방식이 더 나아 보이나요?

참고한 자료
https://stackoverflow.com/questions/67992894/component-definition-is-missing-display-name-for-forwardref

2023-07-11 07:57 UTC, 2yunseong approved these changes
👍 스타일 컴포넌트만 손봐주세용

2023-07-11 07:57 UTC, 2yunseong commented on frontend/src/components/Input/index.tsx
> +    <InputWrapper>
InputContainer 로 변경부탁드립니당

2023-07-11 08:48 UTC, regularPark commented on frontend/src/components/Input/index.tsx
> +    <InputWrapper>
수정 완료했습니다😄 

[6400a84](https://github.com/woowacourse-teams/2023-stamp-crush/pull/35/commits/6400a842315617732e414ff8d7f009dc1989c214)

2023-07-12 04:22 UTC, kangyeongmin approved these changes

2023-07-12 06:39 UTC, 2yunseong approved these changes

2023-07-12 06:41 UTC, merged