[FE] Button 컴포넌트 구현
woowacourse-teams/2023-stamp-crush pull request #36
Opened 2023-07-11 04:10 UTC by kangyeongmin

## 주요 변경사항
sub -> secondary 로 버튼 명칭을 변경하였습니다.

## 리뷰어에게...

2023-07-11 09:22 UTC, 2yunseong requested changes
themeProvider 적용하실건가요?? 적용 이후 다시 알람주세요!!

2023-07-11 09:27 UTC, 2yunseong requested changes
코멘트 한번만 확인 부탁드려요~~

2023-07-11 09:27 UTC, 2yunseong commented on frontend/src/components/Button/Button.style.tsx
> +export const BaseButton = styled.button<{ $variant: string; $size: string }>`
BaseButtonProps로 따로 타입을 빼는건 어떤가요?

2023-07-11 09:27 UTC, 2yunseong commented on frontend/src/index.tsx
> +    <GlobalStyle />
GlobalStyle은 App에 넣는건 어떤가요??

2023-07-12 02:14 UTC, kangyeongmin commented on frontend/src/index.tsx
> +    <GlobalStyle />
아 App에 넣어야 했는데 실수로 저기 넣어버렸네요.
수정하겠습니다!

2023-07-12 06:44 UTC, regularPark approved these changes

2023-07-12 07:37 UTC, 2yunseong approved these changes
👍

2023-07-12 08:22 UTC, merged