[BE] refactor: coupon관련 service테스트 수정
woowacourse-teams/2023-stamp-crush pull request #368
Opened 2023-08-07 06:41 UTC by youngh0

## 주요 변경사항

- 테스트 컨벤션에 맞게 수정했습니다.

## 리뷰어에게...

## 관련 이슈

close #336 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-07 07:55 UTC, yenawee approved these changes

2023-08-07 07:55 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/application/coupon/ManageCouponCommandServiceTest.java
> +public class ManageCouponCommandServiceTest {
레포지토리 모킹이 10개나 필요하네요....🤭

고생이많았습니다 레오,,,,

2023-08-07 07:55 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/manager/coupon/dto/CustomerAccumulatingCouponFindResultDto.java
>  @EqualsAndHashCode
테스트코드에서 Dto 동등성 비교할때 @EqualsAndHashCode 말고
usingRecursiveComparison() 쓰는건 어떨까요 ??

2023-08-07 08:09 UTC, eunkeeee requested changes
간단한 코멘트 달았습니다! 답변 주세용

2023-08-07 08:25 UTC, jundonghyuk approved these changes
코드 가독성이 좋네요 !

커스토머 관련 리뷰만 남겼습니당

2023-08-07 08:25 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/TemporaryCustomer.java
> +
수정 부탁드릴게요

2023-08-08 07:52 UTC, eunkeeee commented
머지됐다고 리뷰 무시하지 마세요.

2023-08-08 07:52 UTC, merged