[FE] fix: ModifyCouponPolicy 페이지에 등록된 버그들을 해결한다.
woowacourse-teams/2023-stamp-crush pull request #385
Opened 2023-08-08 02:04 UTC by kangyeongmin

## 주요 변경사항

- placeholder가 짤려보이는 문제 및 다양한 입력을 4번에 걸쳐서 나누어 받도록 리팩토링하였습니다. 
![d](https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/e9e9ae52-c9c3-4a86-ace4-ab58476b3c2c)

## 리뷰어에게...

## 관련 이슈

closes #369
closes #355 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-08 02:09 UTC, yenawee commented
4번에 걸쳐 입력받는거 넘 좋네여 👀👏

2023-08-08 02:13 UTC, kangyeongmin commented
@2yunseong !!
expireSelect -> 변수명을 더 명확한 expirePeriod로 변경하였습니다. 백엔드의 용어와도 동일하고 더 명확한 네이밍이라 생각이 들었기 때문입니다!!
현재 사용처에서 다 변경해놓은 상태이긴한데, 추후에 CustomCouponDesign 작업에서 충돌이 날까봐 미리 말씀드립니다!!

2023-08-08 02:22 UTC, regularPark reviewed
고생하셨슴당

2023-08-08 02:22 UTC, regularPark commented on frontend/src/pages/Admin/ModifyCouponPolicy/style.tsx
> +  height: 60%;
태블릿에서 다르게 보이던 문제를 해곃하셨네요 굿

2023-08-08 02:22 UTC, regularPark commented on frontend/src/pages/Admin/ModifyCouponPolicy/ExpirePeriod/index.tsx
> +      <Text>* 유효기간이 지나면 해당 쿠폰의 스탬프가 모두 소멸됩니다.</Text>
사용해보니 문구를 못보고 지나칠 수도 있을 것 같아요! 다른 색상으로 표현해도 좋을 듯 싶어용

2023-08-08 04:24 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/ExpirePeriod/index.tsx
> +      <Text>* 유효기간이 지나면 해당 쿠폰의 스탬프가 모두 소멸됩니다.</Text>
오호~ 수정해보겠습니다!

2023-08-08 06:30 UTC, 2yunseong requested changes
고생하셨습니다~~~ 커맨드 한번 확인해주세욥

2023-08-08 06:30 UTC, 2yunseong commented on frontend/src/pages/Admin/ModifyCouponPolicy/CreatedType/index.tsx
> +  setValue: Dispatch<React.SetStateAction<CouponCreated>>;
React 제외해도 좋을 것 같습니다!!

2023-08-08 06:30 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomCouponDesign/index.tsx
> +      expirePeriod: parseExpireDate(location.state.expirePeriod.value),
다시 보니 expirePeriod 보단 expireDate 가 맞겠네요..!
(이 부분은 애초에 제가 쓴거니 괜찮으시다면 추후에 고칠께요)

2023-08-08 06:30 UTC, 2yunseong commented on frontend/src/pages/Admin/ModifyCouponPolicy/CreatedType/index.tsx
> +          </TypeDescription>
디자인 이쁘네요 👍

2023-08-08 06:30 UTC, 2yunseong commented on frontend/src/pages/Admin/ModifyCouponPolicy/RadioInput/index.tsx
지워버렸군요..

2023-08-08 06:30 UTC, 2yunseong commented on frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
> +              case 1:
숫자를 페이지에 맞게 상수화 해도 좋을 듯 합니다

2023-08-08 06:41 UTC, 2yunseong commented
> expireSelect -> 변수명을 더 명확한 expirePeriod로 변경하였습니다. 백엔드의 용어와도 동일하고 더 명확한 네이밍이라 생각이 들었기 때문입니다!!
현재 사용처에서 다 변경해놓은 상태이긴한데, 추후에 CustomCouponDesign 작업에서 충돌이 날까봐 미리 말씀드립니다!!
@kangyeongmin 확인했습니다~! 관련 코드 고쳐놓을테니 제꺼 나중에 머지 하면 한번 확인해주세요!!

2023-08-08 07:59 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/RadioInput/index.tsx
ㅋㅋㅋ이거 CreatedType폴더로 고대로 이사했슴니다~~😅

2023-08-08 08:03 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomCouponDesign/index.tsx
> +      expirePeriod: parseExpireDate(location.state.expirePeriod.value),
화긴~~

2023-08-08 08:07 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
> +              case 1:
아주 좋은 의견입니다요~👍🏻

2023-08-08 08:09 UTC, kangyeongmin commented on frontend/src/constants/index.ts
> +
확인했습니다~~ 나중에 윤생 작업 내용 머지되면
그 후에 이 코드에도 타입을 부여하는 것이 좋을 것 같아요!! (충돌 우려)

2023-08-09 01:14 UTC, regularPark approved these changes
어푸루부🫡

2023-08-09 05:14 UTC, 2yunseong approved these changes

2023-08-09 05:18 UTC, merged