[BE] feat: 고객 모드 리워드 상세내역 조회
woowacourse-teams/2023-stamp-crush pull request #420
Opened 2023-08-09 07:10 UTC by eunkeeee

## 주요 변경사항

## 리워드 조회

- used queryParam으로 사용 여부를 구분한다.
- used=false: 사용 가능한 리워드
- used=true: 사용 완료한 리워드

### Request

**Header**

```http
GET /api/rewards?used=false

Authorization: username@password Base64 (customer)
```

**Body**

None

### Response

**Header** 

```http
HTTP/1.1 200 OK
```

**Body**

```json
"rewards": [
	{
		"id": 1,
		"rewardName": "아메리카노",
		"cafeName": "우아한카페",
		"createdAt": "yyyy:mm:dd",
		"usedAt": "yyyy:mm:dd",
	}, // ...	
]
```

- 사용 가능한 리워드의 경우 usedAt을 null로 보낸다. 

## 리뷰어에게...

## 관련 이슈

closes #408 

## 체크리스트

- [] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-10 09:08 UTC, yenawee approved these changes
고생햇습니다 깃짱~

2023-08-10 09:08 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +                .andExpect(jsonPath("rewards").isNotEmpty());
내용물도 검증해주면 더 좋을거같아요 ~~

2023-08-10 09:08 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/fixture/RewardFixture.java
> +public final class RewardFixture {
다른 픽스처 객체처럼 통일성을 위해 얘도 private 생성자 있으면 좋겟어요~

2023-08-10 13:31 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
> +        Cafe cafe = createCafe(OwnerFixture.GITCHAN);
테스트명이랑 테스트의 의도가 잘 맞지 않는것같아요.

`Used`가 `True`인 리워드를 조회하는건 어떨까요

2023-08-11 04:55 UTC, youngh0 requested changes
테스트 관련해서 코멘트 남겼습니다!

추가적으로, 제가 확인한 결과 데이터 insert시 updatedAt이 createdAt과 동일하게 생성됩니다. 그래서 dto변환 과정에서 dto.updatedAt == null 이렇게 하면 안될 것 같아요!

관련 내용 테스트가 없어서 놓친 것 같습니다! 확인부탁드려요

2023-08-11 04:55 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +    void 고객모드에서_리워드를_조회한다() throws Exception {
리워드 사용한 내역, 리워드 보유 내역에 대한 테스트를 분리하는거 어떨까요?  `when(visitorRewardsFindService.findRewards(null, false))`와 `when(visitorRewardsFindService.findRewards(null, true))`는 성격이 다르다고 생각합니다

2023-08-11 04:55 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/visitor/reward/VisitorRewardsFindServiceTest.java
> +        given(rewardRepository.findAllByCustomerAndUsed(any(RegisterCustomer.class), eq(false)))
이 부분도 리워드 사용내역 조회, 리워드 보유내역 조회 이렇게 2개의 테스트로 분리하면 좋을 것 같은데 어떻게 생각하시나요?

2023-08-11 04:55 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
> +        Cafe cafe = createCafe(OwnerFixture.GITCHAN);
동의합니다

2023-08-11 05:05 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/reward/Reward.java
> +    public Reward(
맞슴니당! 
리워드도 시간 가지고 조회해야 하는 로직이 포함되어 있어서 불가피하게 추가했어요

2023-08-11 05:06 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +    void 고객모드에서_리워드를_조회한다() throws Exception {
ㅇㅋ!

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +        when(visitorRewardsFindService.findRewards(null, false))
any() 역시 실패하네요...
어째선지 받아오지를 못해요 데이터를

![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/606af394-43ef-4c6a-beb7-e3cbfc5a9245)

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +                .andExpect(jsonPath("rewards").isNotEmpty());
추가설명ㄱㄴ??

여러 가지 섞여있을 때 걔네만 가져오는지를 말하시는건가요??

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/api/visitor/reward/VisitorRewardsFindControllerTest.java
> +                .andExpect(jsonPath("rewards").isNotEmpty());
내용물 검증 테스뚜 추가 완료요

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/application/visitor/reward/VisitorRewardsFindServiceTest.java
> +    void 리워드를_조회할_때_해당_고객이_존재하지_않으면_예외처리한다() {
i forgot oh my

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
> +@KorNamingConverter
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ드디어 해냈습니다

2023-08-11 05:59 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/repository/reward/RewardRepositoryTest.java
> +        Cafe cafe = createCafe(OwnerFixture.GITCHAN);
used = true가 사용 완료한 리워드란 뜻인데 뭐가 문젤까요!??!

2023-08-11 06:06 UTC, youngh0 approved these changes

2023-08-11 06:07 UTC, merged