[FE] refactor: 카페 등록 페이지의 사이드바를 렌더링하지 않는다.
woowacourse-teams/2023-stamp-crush pull request #433
Opened 2023-08-10 03:07 UTC by regularPark

## 주요 변경사항

- 변경된 디자인에서는 사이드바를 렌더링하지 않는 편이 UI가 자연스러운 것으로 판단하여 카페 등록 페이지에 진입시 사이드바를 렌더링하지 않도록 하였습니다.
- 추후에 카페 등록 옵션을 사이드바에 추가하는 것도 괜찮아 보입니다.

## 리뷰어에게...

## 관련 이슈

closes #275 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-10 09:35 UTC, 2yunseong approved these changes
완벽하네욥 ㅎㅎ

2023-08-10 14:16 UTC, kangyeongmin requested changes
수고하셨슴미다!! 코멘트 하나만 확인해주세용

2023-08-10 14:16 UTC, kangyeongmin commented on frontend/src/components/SideBar/PageSideBar.tsx
>  };
컴포넌트 내의 return에서, 완전히 반대되는 내용이라면, early return을 하는 것은 어떨까요?

```javascript
if(current === ROUTER_PATH.registerCafe) return <></>

return (
<PageSideBarWrapper>
...
```

2023-08-11 01:00 UTC, regularPark commented on frontend/src/components/SideBar/PageSideBar.tsx
>  };
early return! 반영 완🫡

2023-08-11 01:26 UTC, kangyeongmin approved these changes
완료!

2023-08-11 01:26 UTC, merged