[FE] refactor: 작성되지 않은 Request/Response의 타입을 작성한다.
woowacourse-teams/2023-stamp-crush pull request #435
Opened 2023-08-10 05:53 UTC by regularPark

## 주요 변경사항

- 통신 관련 코드들의 타입 지정 후 msw를 통한 통신 테스트는 마쳤고, 백엔드 서버가 어떤지 어제 이후로 최신화된 소식이 없어서 무리하게 통신을 해보진 않았습니다.
- 모든 통신 코드의 타입을 작성한 것은 아니며, 스탬프 적립 + 리워드 사용 관련 로직들의 타입과 useQuery 코드들을 수정하였습니다.

## 리뷰어에게...

## 관련 이슈

closes #334 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-10 07:12 UTC, 2yunseong requested changes
지금 타입 선언을 사용처와 가까운 부분에 지정해주었는데요, 상위에서 제네릭으로 지정해주어야 될 것 같습니다.
실제로 아래 그림처럼 `api.get`에서는 any 타입을 리턴하고 있으므로 사용처에서 타입을 지정해주는 것은 타입 단언과 같습니다. 타입 안정성을 사용처에서는 보장할 수 있겠지만, 실제로 api 명세를 작성하는 사람이 의도치 않게 데이터 타입을 잘못 넣게되어도 동작하게 되고, 사용처에서 문제가 발생할 수 있습니다.
<img width="755" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/e94eff1d-35f2-45e8-bfaf-f9ede988ab08">
즉, 추상화된 api 객체에 대한 타입을 지정해주어야 하는데, `api` 객체도 추상화된 request를 사용하고 있으므로 request부터 추상화를 해주어야 된다고 생각합니다.
fetch에 어떻게 타입을 부여할지는 구글에 자료가 많은 걸로 아는데, 금요일날 같이 이야기 나눠봐도 좋을 것 같습니다 ~

2023-08-10 10:07 UTC, regularPark commented
> 지금 타입 선언을 사용처와 가까운 부분에 지정해주었는데요, 상위에서 제네릭으로 지정해주어야 될 것 같습니다. 실제로 아래 그림처럼 `api.get`에서는 any 타입을 리턴하고 있으므로 사용처에서 타입을 지정해주는 것은 타입 단언과 같습니다. 타입 안정성을 사용처에서는 보장할 수 있겠지만, 실제로 api 명세를 작성하는 사람이 의도치 않게 데이터 타입을 잘못 넣게되어도 동작하게 되고, 사용처에서 문제가 발생할 수 있습니다. 

해당부분에 대한 사이드 이펙트는 생각지 못했네요. 안그래도 어느 부분에서 타입을 지정해야하는지 대한 고민이 있었는데요. 현재는 윤생의 피드백을 반영하여 리액트 쿼리를 사용하는 곳(페이지단)에서 사용하도록 변경해보았습니다. 그리고 아무래도 저희의 코드가 통신 코드로 인해 상당히 길어지고 있다보니 커스텀 훅으로 분리하는 절차를 밟아보는 것도 좋다고 생각합니다.😄

2023-08-10 11:24 UTC, 2yunseong commented
제 말은 `api/index.ts` 의 `request` 부분이나 `api`객체의 `get/post` 등등에 제네릭을 부여하자는 의미였습니다!
그러면 아마 사용단(useQuery)에서는 부여하지 않아도 자동으로 추론할 수 있을거에요!

2023-08-11 04:36 UTC, 2yunseong approved these changes

2023-08-11 06:04 UTC, merged