[FE] DialPad component 구현
woowacourse-teams/2023-stamp-crush pull request #45
Opened 2023-07-11 12:32 UTC by kangyeongmin

## 주요 변경사항
close #15

## 리뷰어에게...

2023-07-12 06:53 UTC, regularPark commented on frontend/src/hooks/useDialPad.ts
> +    if (!REGEX.number.test(e.target.value.replaceAll('-', ''))) return;
이렇게 하면 hypen이 입력되지 않나요??🤪

2023-07-12 07:06 UTC, kangyeongmin commented on frontend/src/hooks/useDialPad.ts
> +    if (!REGEX.number.test(e.target.value.replaceAll('-', ''))) return;
^^ 버그 찾아주셔서 감사합니다 🤗

2023-07-12 07:08 UTC, kangyeongmin commented
⭐️ handle로 시작하는 의미없는 핸들러함수 네이밍을 하지말자라고 컨벤션을 지었는데
이번 onChange와 onKeyDown의 handle 메소드 로직은 정말 각각 phoneNumber와 Backspace를handle하는 자잘한 로직들이 담겨있는 메소드라 handlePhoneNumber, handleBackspace로 짓게 되었습니다...

2023-07-12 14:02 UTC, 2yunseong requested changes
라잇 오늘도 고생하셨습니다~~ 리뷰 남길테니 내일 확인해주세요.

2023-07-13 02:14 UTC, kangyeongmin commented on frontend/src/hooks/useDialPad.ts
> +    // 추후에 모달이 열리게 구현 예정
와우~! 바로 설치 들어가겠습니다.

2023-07-13 02:16 UTC, kangyeongmin commented on frontend/src/components/Dialpad/index.tsx
> +        ))}
오호 그런 이슈가 있군요 수정하겠습니다!!

2023-07-13 02:17 UTC, kangyeongmin commented on frontend/src/hooks/useDialPad.ts
> +    if (e.target.value.length > 4 && e.target.value[e.target.value.length - 1] === '-')
god,,,

2023-07-13 02:33 UTC, kangyeongmin commented on frontend/src/hooks/useDialPad.ts
> +  const pressPad = (dialKey: string, index: number) => () => {
좋은 아이디어네요.
DialKeyType 을 선언하여 리팩토링 해보았습니다~

2023-07-13 04:02 UTC, regularPark approved these changes

2023-07-13 04:05 UTC, 2yunseong approved these changes
👍

2023-07-13 04:05 UTC, merged