[FE] refactor: 사장모드 디자인 2차 개선
woowacourse-teams/2023-stamp-crush pull request #450
Opened 2023-08-12 08:37 UTC by kangyeongmin

## 주요 변경사항

* 레고의 푸쉬를 위한 pr이므로 아직 리뷰해주지 않으셔도 됩니다!

- PageSideBar와 SideBar가 관심사가 엮어있어서, components/ 폴더는 해당 프로젝트 내에서 자주 쓰이는 컴포넌트라는 기준 하에, 두 파일을 합쳐서 함께 리팩토링했습니다.
- sidebar의 index가 1일때, border가 위에만 적용되지 않는 문제를 해결하였습니다.
- 간단한 Footer를 구현하였습니다.

## 리뷰어에게...

- @regularPark 금요일에 작업한 레고의 배경색 그라데이션, 커피 든 캐릭터 이미지 파일 추가 등을 해당 브랜치에 함께 푸쉬해주시길 부탁드립니다!
## 관련 이슈

closes #445

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2023-08-12 13:16 UTC, 2yunseong commented
오케이~~ PR 읽었습니다

2023-08-15 06:05 UTC, 2yunseong requested changes
고생하셨습니다!! 리뷰가 늦었네요 😂 내일 봐요 여러분

2023-08-15 06:05 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/index.tsx
> +          }: Customer) => (
여기 타입 선언은 필요없을 것 같습니다! 우리가 api 타입을 잘 지정해줬기 때문에 이제 타입스크립트가 잘 추론해줄것 같아요!!

2023-08-15 06:05 UTC, 2yunseong commented on frontend/webpack.common.js
> +      },
이거 저번에 급하게 넣었긴한데, 합쳐도 될 것 같아요
```suggestion
        test: /\.(jpg|png|gif|svg|woff|woff2|eot|ttf|otf)$/,
        type: 'asset/resource',
      },

```

2023-08-15 07:11 UTC, kangyeongmin commented on frontend/src/components/SideBar/index.tsx
> +  const options = SIDE_BAR_OPTIONS;
아마 레고가 작업한 부분이라서 이유는 잘 모르겠지만, 아래에서 자주 쓰이는 값이라 할당해서 사용한 것 같습니다!
근데 그냥 바로 사용하는 것이 가독성 측면에서 좋아보여 수정하도록 하겠습니다!

2023-08-15 07:12 UTC, kangyeongmin commented on frontend/src/components/SideBar/style.tsx
> +  border-radius: ${({ $currentIndex }) => ($currentIndex === 2 ? '0 0 40px 0' : '0')};
사이드바 디자인로직(border-radius) 부분이 복잡해서 이런 하드코딩적인 부분이 많긴 한데,
현재의 로직을 바꿀 수 있는 방법이 떠올라서, 추후에 완전히 바꾸도록 하게씁니다!

2023-08-15 13:05 UTC, 2yunseong approved these changes
어프루브~~ 내일 봅시다~

2023-08-16 00:56 UTC, merged