[FE] feat: 마이페이지의 스탬프 적립내역 페이지를 구현한다.
woowacourse-teams/2023-stamp-crush pull request #453
Opened 2023-08-12 13:14 UTC by 2yunseong

## 주요 변경사항
- RewardHistory 와 비슷한 로직은 최대한 재사용 해보려했으나.. 서로 데이터 구조가 살짝식 달라서 같은 타입으로 상속하려다가 일단은 분리해서 적었습니다. (RewardHistoryType, StampHistoryType) 두 타입이 비슷한 속성을 공유해서 상속해서 하면 재사용할 수 있을 것 같아요.

- Reward가 두개가 있더군요..? 그래서 타입이름을 일단 임의로 지어서 고쳐놓았습니다. 맘에 안드시면 리뷰 남겨주세요.

- if(status === 'loading') .. 할 때 라잇이 제작한 SubHeader는 남긴채로 내용만 바뀌면 좋을 것 같아서 HistoryPage를 만들었어요

- 마이페이지의 스탬프 적립 내역/리워드 적립 내역 링크를 구현한 페이지와 이어지도록 구현하였습니다.

- 스탬프적립내역/리워드적립내역이 동일한 디자인을 공유하므로 한 디렉토리로 묶었습니다.

## 리뷰어에게...

## 관련 이슈

closes #390 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-12 13:16 UTC, 2yunseong reviewed
리뷰하실 때 참고하세요!!

2023-08-12 13:16 UTC, 2yunseong commented on frontend/src/Router.tsx
> +import StampHistoryPage from './pages/HistoryPage/StampHistory';
타입명이랑 처음에 겹쳐서, 명시적으로 Page임을 표현하려고 해당 네이밍을 사용하였습니다.

2023-08-12 13:16 UTC, 2yunseong commented on frontend/src/Router.tsx
> +          element: <TemplateCouponDesign />,
이부분이 CustomCouponDesign 이 아니라서, 변경했어요.

2023-08-13 06:36 UTC, kangyeongmin requested changes
sort로직이 꽤 복잡한데, 수고하셨습니다 윤생!!!👍🏻

몇가지 코멘트 남겼으니 확인 부탁드립니다~

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/Router.tsx
> +import StampHistoryPage from './pages/HistoryPage/StampHistory';
컴포넌트와 타입명, 페이지와 타입명 겹치는 경우가 점점 많아지는 것 같은데
어떻게 해결하면 현명할까요?

레벨4때 고민해보면 좋을 것 같아요~

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/pages/HistoryPage/HistoryPage.tsx
> +const HistoryPage = ({ title, children }: HistoryPageProps) => {
PropsWithChildren 사용방식을 컨벤션과 맞추면 어떨까요?

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +export function transformRewardsToMap(
요부분의 함수들만 화살표 함수가 아닌 function 키워드를 사용하여 선언하신 이유가 있을까요?

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +      </div>
저번에 리뷰드린 시멘틱태그 사용 부분이 다시 누락된 것 같아요!
확인 부탁드립니당

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/pages/HistoryPage/StampHistory/index.tsx
> +      </div>
요기도!

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +    <HistoryPage title="리워드 사용 내역">
이부분도 위에서 선언한 title 변수를 사용하면 될 것 같아요!

2023-08-13 06:36 UTC, kangyeongmin commented on frontend/src/utils/index.ts
> +  arr: T[],
여기도 function으로 선언하신 이유가 궁금하네요

2023-08-13 07:32 UTC, regularPark reviewed
라잇이 리뷰를 많이 주셔서 제가 따로 피드백드릴 게 많이 없었네요. 고생하셨습니다.💪

2023-08-13 07:32 UTC, regularPark commented on frontend/src/pages/HistoryPage/StampHistory/index.tsx
> +  });
위와 동일합니다. Histories~

2023-08-13 07:32 UTC, regularPark commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +  propertyName: RewardHistoryDatePropertys,
제가 코드를 직접 pull하여 이리저리 코드를 만져봤는데 `propertyName`이 가리키는 것들이 createdAt과 useAt이더라구요. 그런 점에서 이 네이밍이 직관적이지 않은 것 같아요.🥲 시간을 지칭하는 단어를 쓰면 나중에 리팩토링할 때도 더 좋지 않을까하는 생각이 드네요.🤔

2023-08-13 10:56 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/HistoryPage.tsx
> +const HistoryPage = ({ title, children }: HistoryPageProps) => {
감사합니다~

2023-08-13 10:58 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +export function transformRewardsToMap(
얘들 재사용하려고 구현해볼 때 제네릭을 썼었는데, tsx 파일에서는 제가 제네릭을 잘못선언해서인가 화살표함수로 선언하면 제네릭이 컴포넌트로 잡더라구요? 그래서 고쳐놓아야 하는데 안고쳐놨네욥

2023-08-13 11:01 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +
오 문법 굿 감사합니다

2023-08-13 11:01 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +    <HistoryPage title="리워드 사용 내역">
헉 이걸 빼먹다니

2023-08-13 11:03 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +
추가로 타입으로 뺄께욥

2023-08-13 11:04 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/StampHistory/index.tsx
> +  });
thank~

2023-08-13 11:05 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +  propertyName: RewardHistoryDatePropertys,
네이밍 안좋은거 너무 인정합니다 혹시 마땅한 네이밍을 추천해주실 수 있나요?

2023-08-13 11:08 UTC, 2yunseong commented on frontend/src/pages/HistoryPage/RewardHistory/index.tsx
> +      </div>
최상단을 빼먹었네요 ㅠㅠ 감사합니다

2023-08-13 11:09 UTC, 2yunseong commented
여러분 부족한 코드 리뷰해주셔서 감사합니당
빼먹은게 많네요 ㅠ
내일 저는 못가지만 OAuth 화이팅입니다(도울수 있는건 도울테니 언제든 연락주세여)
그럼 다시 요청드립니다!

2023-08-16 01:51 UTC, merged