[BE] refactor: 이전 정책의 쿠폰인지 확인하는 로직을 수정한다
woowacourse-teams/2023-stamp-crush pull request #454
Opened 2023-08-12 13:47 UTC by yenawee

## 주요 변경사항

- 이전 정책의 쿠폰인지 확인하는 책임을 Coupon 객체에 넘겼습니다
- 처음에는 쿠폰 객체의 CouponPolicy 의 createdAt 과 쿠폰 객체가 참조하는 Cafe 의 CafePolicy 의 createdAt 을 비교해서 둘이 다르면 이전 정책이라고 판단하려고 했습니다
- 그런데 Coupon 을 발급할때 CouponPolicy 를 CafePolicy.copy() 로 만들고 그때 CouponPolicyRepository 에 save() 를 해서 위의 로직을 사용할 수 없었습니다
- 그래서 CouponPolicy 와 CafePolicy 의 리워드 이름, 최대 스탬프 개수, 유효기간을 각각 비교해서 다르면 이전 정책의 쿠폰인 것으로 판단하도록 했습니다

## 리뷰어에게...

-  정책에 다른 필드가 추가된다면 그 필드도 비교하도록 코드를 추가해야 해서 확장성은 좀 없는데.... 제 최선이었어요

## 관련 이슈

closes #452

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-08-12 13:49 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +        CafePolicy currentCafePolicy = cafe.getPolicies().get(0);
이거 CafePolicy 가 @Where(clause = "deleted = false") 로 조회조건 걸려있어서 한개 조회될거라서 .get(0) 사용했습니다!

2023-08-12 13:52 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindServiceTest.java
> +        cafe.getPolicies().clear();
이거 cafe 를 static 객체를 사용해서  

쿠폰_정책이_쿠폰의_카페의_정책과_내용이_같지_않으면_예전_정책의_쿠폰이다, 쿠폰_정책이_쿠폰의_카페의_정책과_내용이_같으면_현재_정책의_쿠폰이다 

이거 두개가 서로 영향 줘서 clear() 하는거 추가햇습니다 
이 두개만 사용해서 @AfterEach 하는거도 좀 그래서..

2023-08-14 04:21 UTC, youngh0 approved these changes
고생하셨습니다!!

저희 ERD상에서 복사본이 꼭 필요할지 얘기해보고 싶네요

2023-08-14 04:21 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +        return !Objects.equals(currentCafePolicy.getMaxStampCount(), couponPolicy.getMaxStampCount())
복사본으로 로직이 조금 복잡하고 어색? 하네요..

현재 상황에서는 최선인 것 같아요!

2023-08-14 13:52 UTC, jundonghyuk requested changes
고생하셨슴다 !

커멘트 남겼어요 ㅎㅎ

2023-08-14 13:52 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/manager/coupon/ManagerCouponFindService.java
> +        return coupon.isPrevious();
따로 함수로 안빼어도 될것같은..? 취향차이지만요 ㅎㅎ

2023-08-14 13:52 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +        CafePolicy currentCafePolicy = cafe.getPolicies().get(0);
`CafePolicy`가 무조건 한개는 존재한다. 라는 가정하에 로직이 짜여진것같은데요 !

만약 `CafePolicy`를 설정하는 쪽에서 잘못된 로직이 돌아 `CafePolicy`가 한개도 존재하지 않는다면 여기서 `NPE`가 날 것 같아요!

`NPE`가 터지면 디버깅이 어려우니 `cafe.getPolices`의 사이즈가 0일 때 저희가 디버깅 하기 쉽게 예외를 터트려줘도 괜찮을 것 같아요 ㅎㅎ

2023-08-15 04:27 UTC, eunkeeee approved these changes
확인했고, isPrevious 코드를 CouponPolicy 객체에 메세지를 던지도록 리팩터링해서 추가했어요!

2023-08-15 04:27 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +        CafePolicy currentCafePolicy = cafe.getPolicies().get(0);
저도 동의합니다! 
근데 처음에도 cafe policy를 무조건 넣어주기 때문에 우려하는 상황은 잘 발생하진 않을 것 같긴 하지만..
그래도 이렇게 하는게 좀더 안정적일 것 같아요!

2023-08-16 05:29 UTC, merged