[FE] feat: Stepper 구현
woowacourse-teams/2023-stamp-crush pull request #48
Opened 2023-07-12 07:34 UTC by 2yunseong

## 주요 변경사항
- Stepper 를 구현하였습니다. 피그마 시안대로 구현하려고 노력하였습니돠~
![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/8e5539c4-d8cf-4d2e-8521-50d9402f9eb9)
close #20 
## 리뷰어에게...

### Stepper 컴포넌트 API
```typescript
interface StepperProps {
  minValue: number;
  maxValue: number;
  step: number;
  value: number;
  setValue: React.Dispatch<React.SetStateAction<number>>;
  height: number;
}
```

`minValue`: Stepper가 가질 수 있는 최소값입니다.
`maxValue`: Stepper가 가질 수 있는 최대값입니다.
`step` : 증감버튼을 누를 때 마다 증가/감소하는 수치입니다.
`value` : 현재 Stepper의 값입니다. 리액트의 상태값입니다.
`setValue` : Stepper 값을 바꾸기 위한 useState Setter입니다.
`height`: Stepper의 높이를 설정합니다. Stepper는 디자인 상 크기조절할 때 비율을 맞추어야 되어 height만 받아 커스텀할 수 있게 구현하였습니다.

2023-07-12 08:20 UTC, kangyeongmin requested changes

2023-07-12 08:20 UTC, kangyeongmin commented on frontend/src/components/Stepper/index.tsx
> +  const onDecreaseNumber = () => {
`on`prefix를 붙이신 이유가 있을까요?

increase, decrease로 시작하는 메소드명이 더 명확한 것 같기도 해요!

2023-07-12 08:20 UTC, kangyeongmin commented on frontend/src/components/Stepper/index.tsx
> +const Stepper = ({ minValue, maxValue, step, value, setValue, height }: StepperProps) => {
현재 시안 stepper들이 모두 minValue, maxValue, step, value, height들이 동일한 것 같은데 props를 옵셔널로 받고

```javascript
({ minValue=0, maxValue=10, step=1, value=1, setValue, 
height=20px }: StepperProps)
```

이런식으로 default value를 넣어주는 것 어떤가요?

2023-07-12 14:36 UTC, 2yunseong commented on frontend/src/components/Stepper/index.tsx
> +  const onDecreaseNumber = () => {
습관적으로 붙였던 것 같습니다!! 반영하겠씁니다 감사합니다~

2023-07-12 14:38 UTC, 2yunseong commented on frontend/src/components/Stepper/index.tsx
> +const Stepper = ({ minValue, maxValue, step, value, setValue, height }: StepperProps) => {
좋아요~~

2023-07-13 06:00 UTC, kangyeongmin approved these changes

2023-07-13 10:24 UTC, regularPark approved these changes

2023-07-13 10:25 UTC, regularPark commented on frontend/src/components/Stepper/index.tsx
> +      </RightStepperButton>
Right, Left도 좋지만 버튼의 역할을 드러내는 다른 네이밍은 없을까요? children으로 +,-가 명시적으로 들어가 있는 상황이니까요.

2023-07-15 08:14 UTC, 2yunseong commented on frontend/src/components/Stepper/index.tsx
> +      </RightStepperButton>
리팩터링이 늦어졌네용~~ 한번 변경해보았는데 확인부탁드려요 레고 @regularPark

2023-07-15 13:16 UTC, regularPark commented on frontend/src/components/Stepper/index.tsx
> +      </RightStepperButton>
props로 left, right 구분 + 스타일링까지..! 너무 좋네요! 👍👍 역시 윤생🫢

2023-07-15 13:17 UTC, regularPark approved these changes
주말까지 고생많으셨습니다!

2023-07-16 11:02 UTC, merged