[FE] 로그인 페이지를 개선한다.
woowacourse-teams/2023-stamp-crush pull request #624
Opened 2023-09-06 07:52 UTC by 2yunseong

## 주요 변경사항
고객 로그인 페이지
<img width="381" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/45785e75-0618-4ae1-bae7-67ae95e77bb9">
사장님 로그인 페이지
<img width="1680" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/90a94282-ff70-4d87-a49b-3327aa205d29">

## 리뷰어에게...

## 관련 이슈

closes #620 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-06 08:34 UTC, regularPark approved these changes
리뷰할만한 게 안보이네요. 로그인화면이 너무 예뻐졌어요 윤생!🥹

2023-09-07 01:22 UTC, kangyeongmin requested changes
드뎌 진짜 서비스다운 로그인 페이지가 탄생햇네요,,
수고하셨습니다 윤생~

2023-09-07 01:22 UTC, kangyeongmin commented on frontend/src/pages/Admin/AdminLogin/index.tsx
> +        <Title>안녕하세요 사장님!:{')'}</Title>
`<Title>안녕하세요 사장님! :)</Title>`
이어도 될거 같아요~

2023-09-07 01:22 UTC, kangyeongmin commented on frontend/src/pages/Admin/AdminLogin/style.tsx
> +export const LoginLink = styled.a``;
사용처에서 그냥 a 태그를 사용하는 것은 어떤가용?

2023-09-08 04:49 UTC, 2yunseong commented on frontend/src/pages/Admin/AdminLogin/style.tsx
> +export const LoginLink = styled.a``;
오 좋습니다!!

2023-09-08 06:51 UTC, kangyeongmin approved these changes

2023-09-08 06:51 UTC, merged