[BE] feat: Customer 엔티티 구조를 단일 테이블 구조로 변경한다.
woowacourse-teams/2023-stamp-crush pull request #633
Opened 2023-09-07 07:06 UTC by youngh0

## 주요 변경사항

- 기존 Customer 상속 구조를 제거했습니다.
- 이에 따른 테스트 코드를 수정했습니다.
- 현재 Customer를 생성하는 코드가 모두 제각각인데 빌더를 사용하도록 수정했습니다.
    - Builder 로 생성 시 임시회원이면 `temporaryCustomerBuilder`, 정식 회원 생성이면 `registeredCustomerBuilder` 를 사용하도록 수정했습니다.

## 리뷰어에게...

## 관련 이슈

closes #631 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-07 07:14 UTC, eunkeeee reviewed
테스트

2023-09-07 07:14 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    private String encryptedPassword;
변화 범위가 너무 크면 힘드니껜...
일단은 enum으로의 변화만 따지도록 할게요

2023-09-07 07:25 UTC, eunkeeee requested changes
레오 수고 많았습니당! 
사소한 수정사항 몇개 있어요

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/initializer/DataInitializer.java
> +                .build();
바꾸느라 진짜 수고 많았네요..

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
> +    Optional<Customer> findByNickname(String nickname);
이 메서드는 사용하고 있지 않는걸로 아는데 삭제해도 좋을 것 같아요!

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
> +                .encryptedPassword(null)
특별히 null 명시할 필요는 없을 것 같아요! (반영 안해도 됨)

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
> +                .oAuthId(123L)
123L 대신 oAuthId 넣어주세요!

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/auth/application/VisitorAuthService.java
> +                .oAuthProvider(OAuthProvider.KAKAO)
이것도
.oAuthProvider(oAuthProvider)
그대로 해주세요!
테스트용 API 코드에요

2023-09-07 07:25 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCouponFindStep.java
> +    public static List<CustomerAccumulatingCouponFindResponse> 고객의_쿠폰_조회하고_결과_반환(Owner owner, Long savedCafeId, Customer savedCustomer) {
테스트는 다 통과하니깐 그냥 잘 고쳤다고 생각할게요...

2023-09-07 13:10 UTC, jundonghyuk approved these changes
레오 대규모 작업을 마쳐주셨네요..

대단합니다..따봉..

몇개만 고치면 될것같아여 한 번봐주시고 고쳐주세용

2023-09-07 15:29 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
> +    Optional<Customer> findByNickname(String nickname);
제거했슴다~

2023-09-07 15:36 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/visitor/profile/dto/VisitorProfileFindByPhoneNumberResultDto.java
> +        return "temporary";
굿! 수정했어요

2023-09-07 15:37 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    }
지웠는데 푸시를 안했네요 ㅎ.. 제거했습니다

2023-09-08 00:59 UTC, yenawee approved these changes
레오 고생이 많앗네여....

매우빠르게 진행했네요 대단합니다....👍

2023-09-08 00:59 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    public Customer(
이렇게 할 수 가 있네요 신기하네요

2023-09-08 04:47 UTC, merged