[FE]refactor: 커스텀 쿠폰 페이지의 관심사를 분리한다.
woowacourse-teams/2023-stamp-crush pull request #642
Opened 2023-09-08 14:34 UTC by 2yunseong

## 주요 변경사항
- 서버 상태를 사용하는 컴포넌트만 따로 분리해 작업하였습니다.
- 템플릿이 존재하지 않을 시 경고 문구를 추가했습니다.
<img width="385" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/119da604-a74d-4693-9b88-270b2db9840d">

- 이펙티브 TS(아이템 33) 를 참고해 string 타입을 좁혔습니다. 

## 리뷰어에게...
- 모든 작업을 한번에 올리면 리뷰하기 피곤할 것 같아 페이지 별로 올리겠습니다~~!

## 관련 이슈
 #456  
## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-09 09:56 UTC, regularPark approved these changes
아무래도 관심사 분리 코드이다보니 딱히 피드백 드릴게 보이지는 않네요 고생하셨슴다~

2023-09-09 09:56 UTC, regularPark commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/index.tsx
> +
분리하신거 굿 👍

2023-09-09 09:56 UTC, regularPark commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/SampleImageList.tsx
> +  }
템플릿 없을 때 대처하신거 👍

2023-09-12 04:43 UTC, kangyeongmin requested changes
윤생~ 수고하셨슴니다!!

2023-09-12 04:43 UTC, kangyeongmin commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/hooks/useSampleImages.tsx
> +};
저도 훅 분리할때 했던 고민인데, 훅을 분리할 때 네이밍에 컨벤션을 주는 것은 어떨까요?
예를들어, getCouponSamples라면 useCouponSamples로 네이밍을 동일하게 하는거요!

비슷한 이름을 가진 api 메소드기 너무 많아서, 이렇게나마 규율을 주는 것도 좋아보여요!

2023-09-12 04:43 UTC, kangyeongmin commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/SampleImageList.tsx
> +          onClick={() => clickSampleImage(element)}
clickSampleImage 를 커링함수로 만들어주어서
`onClick={clickSampleImage(element)}`로 써주는 것은 어떨까요?

onClick 함수내에 인라인으로 선언하는 경우 해당 컴포넌트가 새로 렌더링 될때마다 함수가 새로 생성이 되기 때문에 위 방식을 좀 더 지향하는 것으로 알고 있어요!

2023-09-12 04:43 UTC, kangyeongmin commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/index.tsx
> +
else 사용보단 ealry return 하는 것은 어떨까요?

2023-09-12 09:57 UTC, 2yunseong commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/hooks/useSampleImages.tsx
> +};
#658 에서 결정되는 내용으로 반영하겠습니다~

2023-09-12 09:58 UTC, 2yunseong commented on frontend/src/pages/Admin/CouponDesign/ChoiceTemplate/SampleImageList.tsx
> +          onClick={() => clickSampleImage(element)}
오 좋은 접근이네요! 수정하겠습니다

2023-09-13 07:37 UTC, kangyeongmin approved these changes

2023-09-13 09:48 UTC, merged