[FE] refactor: 전화번호로 고객 조회 로직을 전화번호 입력페이지로 이동시킨다.
woowacourse-teams/2023-stamp-crush pull request #643
Opened 2023-09-09 06:55 UTC by kangyeongmin

## 주요 변경사항

- 전화번호 입력 페이지 `EnterPhoneNumber`에서 전화번호로 고객 조회 실패 시 alert를 띄우고(이전 pr 작업내용)
- 후에 해당 전화번호로 임시 가입 고객을 생성하여 다음 페이지 `SelectCoupon`에 state를 넘겨주는 작업을 진행하였습니다.

## 리뷰어에게...

## 관련 이슈

closes

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-09 10:31 UTC, regularPark requested changes
라잇 고생하셨슴당~

2023-09-09 10:31 UTC, regularPark commented on frontend/src/hooks/useDialPad.ts
>      }
`customerState`가 왜 `CustomerPhoneNumber`인가 했더니 타입에 정의된 `id`, `nickname`, `phoneNumber`를 가진 녀석이 `CustomerPhoneNumber`네요? ㅎㅎ 얼른 타입 정리를 좀 해야겠네요🥲

2023-09-09 10:31 UTC, regularPark commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
라잇이 작성한 통신 코드의 구조를 보니  `useQuery`, `useMutation` 두 로직 모두 별개로 `DialPad`에서 분리해도 괜찮을 것 같다는 생각이 드네요🥹 아무래도 제가 작성한 코드에서는 전화번호도 location에서 넘어온 것을 사용하다보니 결합도가 높아졌던건지 분리하기 어려워보였는데😭💦💦

2023-09-11 05:22 UTC, 2yunseong requested changes
고생하셨습니다~~ 리뷰 몇개만 확인 부탁드려요

2023-09-11 05:22 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
> +    },
저도 최근에 안건데 refetch 대신 invaildate Queries 를 사용하는 것이 더 좋아보여요! refetch같은 경우 query가 observing 할 수 없다고 하네요~!

https://github.com/TanStack/query/discussions/2468
https://tanstack.com/query/v4/docs/react/guides/invalidations-from-mutations

2023-09-11 05:22 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
> +    },
추가 하자면, 다음과 같이 변경할 수 있을 것 같아요. 쿼리를 무효화한다고 동기적으로 알려줄 수 있고, 이 후 무효화에 관한 refetch는 query가 알아서 해줄 듯 합니다!!
```suggestion
  const { mutate: mutateTemporaryCustomer } = useMutation({
    mutationFn: postTemporaryCustomer,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['customer'] }); // 위에서 useQueryClient의 선언 필요
      if (customers?.customer[0]) navigateNextPage(customers.customer[0]);
    },
```

2023-09-11 05:22 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
> +    mutateTemporaryCustomer({ body: { phoneNumber: phoneNumber.replaceAll('-', '') } });
phoneNumber.replaceAll( ... ) 을 상수화 하는건 어떨까요 ?

2023-09-11 05:47 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
> +    mutateTemporaryCustomer({ body: { phoneNumber: phoneNumber.replaceAll('-', '') } });
다른곳에도 같은 로직이 있길래 유틸함수를 만들어서 적용해주었습니다~

2023-09-11 05:50 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/Dialpad/index.tsx
> +    },
아 새로 요청하기보다 이전의 쿼리를 무효화한다고 알려주는거군요! 수정하겠습니다~

2023-09-11 06:53 UTC, regularPark approved these changes
고생하셨슴다 라잇~

2023-09-11 08:43 UTC, kangyeongmin commented
실수로 누른 revert로 feature/639-back-up pr에 작업 상황을 다시 올렸습니다.

2023-09-11 08:43 UTC, closed without merging