[BE] feat: Interceptor, ArgumentResolver를 새로 만들고 모든 인증과정을 Bearer로 변경한다.
woowacourse-teams/2023-stamp-crush pull request #654
Opened 2023-09-11 17:21 UTC by jundonghyuk

## 주요 변경사항
- Interceptor, ArgumentResolver 수정
- 모든 테스트 인증을 `basic` -> `bearer`로 변경

## 리뷰어에게...
- 인증 방식을 바꾸니.. 테스트가 다깨져버려서 그냥 다 고쳐봤습니다..
- 제나가 작성해준 `ArgumentResolver`는 주석처리해서 살려놨으니 이에 대해 논의해봐도 좋습니다 !

- 테스트도 봐주시면 감사하나.. 그러지 못한 분들은 `interceptor`, `argumentResolver`, `webConfig`을 중점적으로 봐주세요 !

## 관련 이슈

closes #652 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-12 08:48 UTC, yenawee approved these changes
하디 새벽까지 고생이 많으셧네요!! 👏

Bearer 로 테스트 코드 바뀐거 보니까 좋네요....
카페 인가는 지금 상태로 가도 될거같아요!!

코드 수정하면서 주석처리한 코드들이랑 안쓰는 클래스들만 지워주면 좋을거같아요~~

2023-09-12 08:48 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/config/WebMvcConfig.java
> +                .excludePathPatterns("/api/admin/**")
이거 .excludePathPatterns() 메서드 하나에 다 넣는건어떠신가여 매개변수 가변인자로 받는디

2023-09-12 12:30 UTC, youngh0 requested changes
하디씨 리뷰 하다보니 매우 고생하신게 보여서 눈물이 앞을 가리네요..🥲
정말 고생하셨습니다!!

util 클래스 활용해서 interceptor 로직이 많이 깔끔해진 것 같아요! 사소한 부분에만 코멘트 남겼는데 확인부탁드려요!! 확인 해주시면 바로 어프루브 하겠습니다!!
 ㄴ 그냥 어프루브 하겠습니다. 생각해보니 너무 사소하네요 ㅎ

테스트 코드도 변경된 프로덕션 코드에 맞춘 변경이 상당히 많아 보이는데 고생하셨어요!!👏👏

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/interceptor/CustomerAuthInterceptor.java
> +        if (!BearerParser.isBearerAuthType(authorization)) {
사소한거긴 한데 부정문 안쓰는 방향으로 수정해도 좋을듯요!

아래 모두 ditto~

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/auth/application/util/BearerParser.java
> +public class BearerParser {
parsing 유틸 클래스 좋네용 👍

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/auth/application/util/BearerParser.java
> +        return authorization.split(DELIMITER).length == 2;
2 도 마저 상수화 하면 좋을듯요!

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/interceptor/CustomerAuthInterceptor.java
> +            throw new UnAuthorizationException("인증할 수 없습니다.");
이제 예외 로그 처리 해놔서 예외메시지에 id 정도라도 추가해주면 좋을듯합니다!!

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/interceptor/OwnerAuthInterceptor.java
> +            throw new UnAuthorizationException("인증할 수 없습니다.");
여기도 예외 메시지 ditto~

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/auth/application/util/JwtTokenProvider.java
> +            log.info("Invalid JWT Token", e);
코딩하면서 확인하려고 info 로그 찍은걸까요??

만약 맞다면 예외 던지는것도 좋을듯요!

2023-09-12 12:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/config/resolver/CustomerAuthArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
깔쌈하네요!!

2023-09-12 12:30 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/acceptance/step/ManagerCafeCouponSettingFindStep.java
> +//                .basic(owner.getLoginId(), owner.getEncryptedPassword())
삭제해도 괜찮을듯요!

2023-09-12 12:31 UTC, youngh0 approved these changes

2023-09-13 08:40 UTC, eunkeeee approved these changes
approve

2023-09-13 08:40 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/manager/cafe/ManagerCafeCommandService.java
> +                .orElseThrow(() -> new OwnerNotFoundException("존재하지 않는 사장입니다."));
해당 내용은 로그로 그대로 내보낼텐데, id도 함께 로그에 포함시켜주면 더 좋을 것 같아요

2023-09-13 08:40 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/auth/application/util/BearerParser.java
> +public class BearerParser {
final 클래스로 가능하면 만들어도 좋을 것 같아요

2023-09-14 03:17 UTC, merged