[FE] refactor: 쿠폰 제작 및 변경 페이지의 관심사를 분리한다.
woowacourse-teams/2023-stamp-crush pull request #655
Opened 2023-09-12 00:52 UTC by 2yunseong

## 주요 변경사항

- #456 
    - step과 관련된 로직을 분리하였습니다. 
- #647 
    - defaultChecked를 빼주었더니 해결하였습니다. 아마 상태로 관리하는 check값이랑 충돌된게 아닐까 생각이 드네욥

## 리뷰어에게...

## 관련 이슈
- #456 
- closed #647 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-12 04:34 UTC, regularPark approved these changes
야무지게 분리하셨네요 굿👍

2023-09-12 04:50 UTC, kangyeongmin requested changes
페이지 폴더내에 hooks와 components 폴더 이외의 다른 폴더들(common, logic)의 생성은 조금 더 토의해보면 좋을 것 같아요!!

프로젝트의 복잡성이 너무 높아질 것같고, 아주 결이 다른 것이 아니라면 공통 utils 혹은 constants 폴더에 두고, 너무 결이 다르다면 그냥 사용처에서 정의해두고 쓰는 것이 좋아보여요. 

윤생은 어떻게 생각하시나요??

2023-09-12 04:50 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/hooks/useStep.ts
> +  createdType: CouponCreated,
단계로직을 훅으로 분리하셨네요!! 👍🏻

2023-09-12 09:55 UTC, 2yunseong commented
@kangyeongmin 
저도 동의합니다~! 다만 어제 어떻게 분리하려다가 이건 팀원끼리 논의가 필요하다고 생각했어요.
혼자 고민하는 시간이 길어져서 일단 만들어서 냈긴한데, discussion으로 한 뒤 수정해도 좋을 것 같습니다~!

2023-09-13 04:25 UTC, kangyeongmin approved these changes

2023-09-13 09:53 UTC, merged