[FE] refactor: react-query 로직 훅으로 분리
woowacourse-teams/2023-stamp-crush pull request #671
Opened 2023-09-13 08:35 UTC by kangyeongmin

## 주요 변경사항

## 리뷰어에게...

## 관련 이슈

closes

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-13 11:31 UTC, regularPark requested changes
고생하셨어요 라잇~

2023-09-13 11:31 UTC, regularPark commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useGetCustomer.ts
> +  });
`enabled`의 조건을 변경하신 이유가 뭔가요?🤔

2023-09-13 11:31 UTC, regularPark commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +  const { data: customer } = useGetCustomer(phoneNumber);
코드를 쭉 읽다보니 `customer.customer.~`가 반복되네요.

https://velog.io/@apro_xo/ReactQuery-useQuery-select-%EC%98%B5%EC%85%98

그래서 가져와봤습니다. `useQuery`의 `select` 옵션!

2023-09-13 15:39 UTC, 2yunseong commented on frontend/src/hooks/useDialPad.ts
useDialPad가 중복되어 있는 것 같은데 사용하지 않는 건 지워야 할 것 같습니다!

2023-09-13 15:42 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +    }
시간 나시면 상수화해서 안전하게 사용해도 좋을듯 합니다. 코드 수정이 번거롭겠지만요..?ㅠ

2023-09-13 15:49 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/usePostTemporaryCustomer.ts
> +    },
지금보니 에러를 최상단 request가 던지긴 하는데 어디서 던져야할지 고민해봐야겠네요.

2023-09-14 01:40 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useGetCustomer.ts
> +  });
enabled의 상태값(isDone)을 useState로 관리했었는데, setState가 비동기적으로 동작하다보니 
query가 실행되는 시점과 그 다음 queryData가 필요한 함수 호출 실행과 관련하여 에러가 있었습니다. 
따라서 위와 같이 변경하였습니다! 전화번호의 길이만으로도 판별이 가능하더라구요 😊

2023-09-14 02:10 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +  const { data: customer } = useGetCustomer(phoneNumber);
오!!! 저런 옵션이 있군요. 바로 적용하겠습니다~

2023-09-14 02:10 UTC, kangyeongmin commented on frontend/src/hooks/useDialPad.ts
헉 지웠었는데 중간에 develop rebase 하면서 생겼나봐요 😅 나이스캐치입니다 윤생~

2023-09-14 03:37 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +    }
좋은 의견이에요~!

2023-09-14 03:45 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/usePostTemporaryCustomer.ts
> +    },
그러게요 전에 있던 코드인데, 에러 세분화를 어떻게 할지 논의해봐야할거 같아요!

2023-09-14 04:13 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +  if (phoneNumber.length === 10) return phoneNumber.substring(0, 8);
흠, 현재 utils안에 있는 함수들도 매직넘버가 많은데 비슷한 결인것 같아서 이 부분은 좀 더 고민해볼게요!

또한, 현재로서는 addHypen 영역의 매직넘버까지 총 5,8,9,10이 각각의 의미가 불분명해서
4개의 각 숫자들에게 이름을 붙여주기 보다는 함수의 네이밍을 더욱 분명하게 바꿔보도록 할게요!

2023-09-14 04:20 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +  if (phoneNumber.length === 10) return phoneNumber.substring(0, 8);
넵~! 👍

2023-09-14 04:20 UTC, 2yunseong approved these changes

2023-09-14 04:21 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/hooks/useDialPad.ts
> +  if (phoneNumber.length === 10) return phoneNumber.substring(0, 8);
+ 추가)
두 가지 모두 Hyphen 분기점에 따라서 추가하거나 같이 삭제하기 때문에 매직넘버가 많이 생성이 되어서
`addHyphen` -> `addHyphenToPhoneNumber`
`removeNumber` -> `erasePhoneNumberWithHyphen` 로 함수의 네이밍을 구체적으로 변경해보았습니다!

2023-09-15 01:54 UTC, regularPark approved these changes
어푸루부~

2023-09-15 07:18 UTC, merged