[FE] refactor: `manageCafe` 페이지의 관심사를 분리한다.
woowacourse-teams/2023-stamp-crush pull request #672
Opened 2023-09-13 11:08 UTC by regularPark

## 주요 변경사항

- `manageCafe`를 훅과 컴포넌트로 최대한 잘게 분리하려 노력했습니다.

## 리뷰어에게...

## 관련 이슈

closes #657 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-13 16:05 UTC, 2yunseong requested changes
오늘도 고생하셨습니다!

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/components/CafeTimePicker/index.tsx
> +  setCloseTime: React.Dispatch<React.SetStateAction<Time>>;
React 없이 import!

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/components/PreviewContent/index.tsx
> +        {cafeInfo.roadAddress + ' ' + cafeInfo.detailAddress}
개인적으로는 Template Literal을 좋아합니다

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/components/PreviewCoupon/index.tsx
> +      )}
이것도 될것 같다는 생각입니다!
```suggestion
      {!!couponDesignData.backImageUrl ? (
        <PreviewBackImage src={couponDesignData.backImageUrl} />
      ) : (
        <p>쿠폰 뒷면 이미지가 들어갈 공간입니다.</p>
      )}
```

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/hooks/useManageCafe.ts
> +
라잇이 만든 유틸이 있는 걸로 알고 있는데 둘다 Merge 이후에 생각해보죳

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/hooks/usePatchCafeInfo.ts
> +    },
https://github.com/woowacourse-teams/2023-stamp-crush/pull/671#discussion_r1324729406

2023-09-13 16:05 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/index.tsx
와 .. 이전 파일 import만 40줄 ㄷㄷ

2023-09-14 01:41 UTC, regularPark commented on frontend/src/pages/Admin/ManageCafe/components/CafeIntroduction/index.tsx
> +        {!introduction ? '0/150' : `${introduction.length}/150`}
상수화 및 삼항연산자 적용 완료😄

[d2dc15e](https://github.com/woowacourse-teams/2023-stamp-crush/pull/672/commits/d2dc15ee8419a829cccfae1365740f1b9c9ee5b9)

2023-09-14 01:47 UTC, regularPark commented on frontend/src/pages/Admin/ManageCafe/components/CafePhoneNumber/index.tsx
> +        pattern="[0-9]{2,3}-[0-9]{3,4}-[0-9]{4}"
상수화 완🤓

[4b05e30](https://github.com/woowacourse-teams/2023-stamp-crush/pull/672/commits/4b05e3002bf293b8e568ad6e92f56ac946d5a9ff)

2023-09-14 01:57 UTC, regularPark commented on frontend/src/pages/Admin/ManageCafe/components/PreviewCoupon/index.tsx
> +      )}
해당 표현은 eslint에서 redundant double negation (불필요한 이중 부정)으로 캐치하네요. `!`으로 하고 삼항연산자 내부의 순서를 바꾼다거나 하는 방법도 있겠네요.혹은 

```suggestion
      {couponDesignData.backImageUrl ? (
        <PreviewBackImage src={couponDesignData.backImageUrl} />
      ) : (
        <p>쿠폰 뒷면 이미지가 들어갈 공간입니다.</p>
      )}
```

그냥 이런 식으로 표현해도 좋을 것 같습니다

2023-09-14 01:59 UTC, regularPark commented on frontend/src/pages/Admin/ManageCafe/components/PreviewContent/index.tsx
> +        {cafeInfo.roadAddress + ' ' + cafeInfo.detailAddress}
저도 그렇습니다. 
[87f89d0](https://github.com/woowacourse-teams/2023-stamp-crush/pull/672/commits/87f89d003e0444f5dfaf12c2fcaf8d720a76542f)

2023-09-14 04:41 UTC, kangyeongmin approved these changes
> manageCafe/index.tsx 파일은 235라인에서 87줄로 감소했으나 그 결과 8개의 컴포넌트와 4개의 훅으로 번식하였습니다🤣

ㅋㅋㅋㅋ 와우 정말 다양한 자손들이 생겨났네요
수고하셨습니다 레고!!

간단한 리뷰들이라서 바로 어프루브 할게요~

2023-09-14 04:41 UTC, kangyeongmin commented on frontend/src/pages/Admin/ManageCafe/components/PreviewCafeImage/index.tsx
> +  cafeImage: string;
cafeImageUrl이라는 이름은 어떨까요? 😄

2023-09-14 04:41 UTC, kangyeongmin commented on frontend/src/pages/Admin/ManageCafe/components/PreviewContent/style.tsx
> +    flex-direction: row;
필요없는 속성인 것 같아요~

2023-09-14 04:41 UTC, kangyeongmin commented on frontend/src/pages/Admin/ManageCafe/index.tsx
> +import PreviewOverview from './components/PreviewOverview';
👍🏻
나중에 일괄적으로 페이지 단의 component들 components 폴더에 넣는 작업 진행하면 좋을 것 같네요~

2023-09-15 02:47 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/components/PreviewCoupon/index.tsx
> +      )}
오호!! 그렇군요~ 훨 깔끔합니다요

2023-09-15 02:47 UTC, 2yunseong approved these changes

2023-09-15 06:02 UTC, merged