[FE] refactor: 카페 등록 페이지에서 사업자등록번호 입력 단계를 제거한다.
woowacourse-teams/2023-stamp-crush pull request #692
Opened 2023-09-16 09:37 UTC by regularPark

## 주요 변경사항

- 프로젝트토의 결과 사업자등록번호는 그대로 입력받는 방향으로 가고 인증하기 버튼만을 없앴습니다.
- 동시에 `RegisterCafe` 코드의 리팩터링도 진행하였습니다. 해당부분에 대한 리뷰 부탁드립니다.

## 리뷰어에게...

## 관련 이슈

closes #691 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-17 06:51 UTC, kangyeongmin requested changes
레고렉오 수고하셨습미다!

2023-09-17 06:51 UTC, kangyeongmin commented on frontend/src/pages/Admin/RegisterCafe/hooks/usePostRegisterCafe.ts
> +    },
refetch 사용과 관련해서는 이전 저와 윤생의 리뷰 코멘트를 하나 남겨놓겠습니당!! https://github.com/woowacourse-teams/2023-stamp-crush/pull/643#discussion_r1321003298

2023-09-17 06:51 UTC, kangyeongmin commented on frontend/src/pages/Admin/RegisterCafe/index.tsx
> +};
input 태그 자체에 다른 width를 지정해주고, 중복되는 props을 객체 하나로 빼주는것이 어떨까요?

2023-09-17 06:51 UTC, kangyeongmin commented on frontend/src/pages/Admin/RegisterCafe/index.tsx
> +};
단순 저의 의견이지만 객체로 따로 뺴주지 않아도 
그냥 써주는 방안이 코드 가독성이 더 높아질 것 같아요~

2023-09-17 08:21 UTC, regularPark commented on frontend/src/pages/Admin/RegisterCafe/index.tsx
> +};
위 세 가지가 공통적으로 반복되는 부분이어서 리팩토링을 해주고 싶었는데, 해당 옵션들을 `Input` 내부로 옮기거나 라잇의 `Button`처럼 높은 자유도를 주지 않는 방향으로 변경해보면 어떨까해서 리팩토링 진행해보았습니다.😄

[884c714](https://github.com/woowacourse-teams/2023-stamp-crush/pull/692/commits/884c7146f2cb69ef41c74a1bf6b7328074abcbfb)

2023-09-17 08:42 UTC, regularPark commented on frontend/src/pages/Admin/RegisterCafe/hooks/usePostRegisterCafe.ts
> +    },
기존의 코드를 분리하다보니 `refetch`를 신경쓰지 못했네요😭 `invalidateQueries`로 변경하였습니다. 정상 동작하는지에 대해서도 테스트를 좀 하고 싶은데 등록된 카페를 삭제해야하다보니 현재로써는 확인이 불가하네요🥲

[ff46fbc](https://github.com/woowacourse-teams/2023-stamp-crush/pull/692/commits/ff46fbcf0a15abcfd258408ccf9da842836eb617)

2023-09-18 10:58 UTC, 2yunseong requested changes
타입관련 리뷰 몇개만 남깁니다!! 고생하셨어요~!

2023-09-18 10:58 UTC, 2yunseong commented on frontend/src/components/Input/index.tsx
> +    { id, label, type, width = 'fill', placeholder, maxLength, required = false }: InputProps,
` InputHTMLAttribute`를 사용하면 label 이나 type같은 선언을 해줄 필요 없지 않나요?? (궁금)

2023-09-18 10:58 UTC, 2yunseong commented on frontend/src/components/Input/style.tsx
> +};
추가로 TYPE이라는 이름이 범용적인 것 같아요
```suggestion
const TYPE: Record<InputWidth, string> = {
  small: '410px',
  medium: '550px',
  fill: '100%',
};
```

2023-09-20 04:14 UTC, regularPark commented on frontend/src/components/Input/index.tsx
> +    { id, label, type, width = 'fill', placeholder, maxLength, required = false }: InputProps,
윤생의 말을 듣고 확인해본 결과 label 빼고 전부 제거 가능했습니다🤣

[64ece6b](https://github.com/woowacourse-teams/2023-stamp-crush/pull/692/commits/64ece6b5990e935537edfa61c5bf6de5716e8774)

2023-09-20 04:16 UTC, regularPark commented on frontend/src/components/Input/style.tsx
> +};
`SIZE`로 변경했습니다🥲

[fba642f](https://github.com/woowacourse-teams/2023-stamp-crush/pull/692/commits/fba642f3ac2262dc75b1d8df20252e752a6f70ce)

2023-09-20 10:35 UTC, 2yunseong commented on frontend/src/components/Input/style.tsx
> +};
타입보단 낫네용

2023-09-20 10:36 UTC, 2yunseong approved these changes

2023-09-22 06:02 UTC, kangyeongmin approved these changes
굿굿!!!!

2023-09-22 06:06 UTC, merged