[FE] refactor: 사용자 유치 전 다양한 버그를 해결한다.
woowacourse-teams/2023-stamp-crush pull request #695
Opened 2023-09-17 08:08 UTC by kangyeongmin

## 주요 변경사항

1. 사장모드 메인로고 클릭시 고객리스트 페이지로 이동
2. 사장모드 고객리스트 페이지 검색 기능 제거, 정렬 기능 오류(한박자씩 늦게 정렬되는 문제) 해결 
3. 고객리스트 페이지 useQuery 훅으로 분리
4. 고객모드 TabBar 생성에 따른 subHeader 라우팅 로직 수정

## 리뷰어에게...

## 관련 이슈

closes #685

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-18 07:50 UTC, regularPark approved these changes
주말 동안 고생하셨어요 라잇~

2023-09-18 07:50 UTC, regularPark commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +      }),
select를 통한 정렬! 아주 야무지게 쓰셨네요. 역시 롸잍👍👍👍

2023-09-18 07:50 UTC, regularPark commented on frontend/src/components/Header/SubHeader/index.tsx
> +  onClickBack?: () => void;
왜 optional로 하셨나용?

2023-09-18 07:59 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +      }),
ㅋㅋ 뢱오레고 고마워요 😄

2023-09-18 08:01 UTC, kangyeongmin commented on frontend/src/components/Header/SubHeader/index.tsx
> +  onClickBack?: () => void;
탭바가 생김에 따라 subHeader에 뒤로가기가 필요하지 않는 경우(내 리워드페이지)가 생겨서 
옵셔널로 수정하였습니다!!

2023-09-18 11:05 UTC, 2yunseong requested changes
라잇 고생하셨슴다 👍

2023-09-18 11:05 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +      }),
이렇게 쓰는거군요 저번에 레고가 알려주고 알아보진 않았는데 이번에 하나 알아갑니다!!

2023-09-18 11:05 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/index.tsx
> +  const { data: customers, status } = useGetCustomers(cafeId, orderOption);
코드가 깔끔해졌어요 👍

2023-09-18 11:05 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +        return a[orderOption.key as keyof Customer] < b[orderOption.key as keyof Customer] ? 1 : -1;
orderOptions의 단언보다 Option을 상속하는 타입을 하나 만들어줘도 좋을 것 같습니다!!

일단은 어렵다면 orderOption.key를 변수로 선언해 단언하는 건 어떨까요? 인덱스에 넣는 부분이 너무 길어지는 것 같아요!

2023-09-19 04:53 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +        return a[orderOption.key as keyof Customer] < b[orderOption.key as keyof Customer] ? 1 : -1;
[e4fce6f](https://github.com/woowacourse-teams/2023-stamp-crush/pull/695/commits/e4fce6fc1fbb2728141e2f8d4248c2d5308ce313)

윤생의 리뷰를 반영하니 
코드가 훨씬 가독성이 높아지고 타입 체크가 더욱 뾰족한 방식으로 리팩토링 된 것 같아요!!! 구웃입니다

2023-09-19 10:54 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +        return a[orderOption.key as keyof Customer] < b[orderOption.key as keyof Customer] ? 1 : -1;
very good입니당

2023-09-19 10:54 UTC, 2yunseong approved these changes

2023-09-20 01:44 UTC, merged