[FE] refactor: `CouponList` 페이지를 리팩토링한다.
woowacourse-teams/2023-stamp-crush pull request #712
Opened 2023-09-19 07:57 UTC by regularPark

## 주요 변경사항

- refetch 제거, 파일 분리 등
- 아쉽게도 드라마틱하게 짧아지진 않았네요.
- `InputPhoneNumber` 디렉터리 변경

## 리뷰어에게...

## 관련 이슈

closes #680 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-20 10:47 UTC, 2yunseong requested changes
고생하셨습니다!

2023-09-20 10:47 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/components/CafeInfo/index.tsx
> +  const { stampCount, maxStampCount, frontImageUrl } = couponInfo;
이름이 중복되는 부분이 있네요..! 이 코드가 될까요 ?
```suggestion
const CafeInfo = ({ cafeInfo: { cafeInfo }, couponInfo, onClickStar }: CafeInfoProps) => {
  const { name: cafeName, isFavorites } = cafeInfo;
  const { stampCount, maxStampCount, frontImageUrl } = couponInfo;
```

2023-09-20 10:47 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/components/CouponDetail/index.tsx
> +      queryClient.invalidateQueries(['coupons']);
👍 👍 👍

2023-09-20 10:47 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/components/HomeTemplate/index.tsx
> +const HomeTemplate = ({ children }: HomeTemplateProps) => {
현재 적용된 방안 vs PropsWithChildren 무엇을 쓰는게 괜찮을까요? (급 디스커션)

2023-09-22 06:16 UTC, regularPark commented on frontend/src/pages/Customer/CouponList/components/HomeTemplate/index.tsx
> +const HomeTemplate = ({ children }: HomeTemplateProps) => {
굳이 interface를 설정해주지 않아도 된다는 점에서 `PropsWithChildren`이 나은 것 같네요. 다른 props 타입이 없다면 현재와 같은 상황에서는 PropsWithChildren을 쓰는 게 나아보입니다.

해당 사항 수정하였습니다.

[8889adb](https://github.com/woowacourse-teams/2023-stamp-crush/pull/712/commits/8889adb4ac8a8019739786cd0497cf6002792868)

2023-09-22 06:24 UTC, regularPark commented on frontend/src/pages/Customer/CouponList/components/CafeInfo/index.tsx
> +  const { stampCount, maxStampCount, frontImageUrl } = couponInfo;
메인 화면에서 카페 정보를 보여주기 위함인데 `CouponInfo`에는 존재하지 않는 데이터인 `CafeName`, `isFavorites`를 사용하기 위해 `Coupon`의 `cafeInfo`를 사용하는 부분입니다.

 윤생이 피드백한 것처럼 구조분해 할당을 했다면 한결 보기 편하게 사용할 수 있었네요. 구조분해할당 완료하였습니다. 네이밍은 api 명세상 합의된 부분이기 때문에 데이터를 직관적으로 이해하기는 어려울 수 있습니다.

[43e44c6](https://github.com/woowacourse-teams/2023-stamp-crush/pull/712/commits/43e44c65ecb609710abf3711241643101f3faf7e)

2023-09-22 06:27 UTC, kangyeongmin approved these changes
복잡한 페이지 분리 수고하셨습니다!!

2023-09-22 06:31 UTC, regularPark commented on frontend/src/pages/Customer/CouponList/hooks/useGetCoupons.ts
> +    },
`return` 제거하는게 더 깰끔하네요. 즉 시 수 정

[9760cc3](https://github.com/woowacourse-teams/2023-stamp-crush/pull/712/commits/9760cc3ecea797eb39b225f7d12ae0c301ad0f6c)

2023-09-25 03:43 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/components/HomeTemplate/index.tsx
> +const HomeTemplate = ({ children }: HomeTemplateProps) => {
ReactNode가 들어오는 거면 저도 PropsWithChildren이 괜찮은것 같습니다~!

2023-09-25 03:43 UTC, 2yunseong approved these changes
늦어서 죄송합니다...ㅎㅎ 놓쳤네요 ㅠ

2023-09-25 05:03 UTC, merged