[FE] feat: 고객모드의 전화번호 등록페이지에서 추가된 플로우를 구현한다.
woowacourse-teams/2023-stamp-crush pull request #714
Opened 2023-09-19 08:23 UTC by kangyeongmin

## 주요 변경사항

해당 [이슈](https://github.com/woowacourse-teams/2023-stamp-crush/issues/677#issue-1895916950) 본문에 추가된 플로우에 대한 구체적인 설명을 작성했습니다.

## 리뷰어에게...

## 관련 이슈

closes #677 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-19 14:50 UTC, regularPark requested changes
고생하셨습니다 라잇✨

2023-09-19 14:50 UTC, regularPark commented on frontend/src/types/domain/customer.ts
> +export type RegisterType = 'temporary' | 'register';
`RegisterType`? 🤔 `RegisterStatus`는 어때용? 이녀석 바꾸면 전부 다 바꿔야해서 혼란하지만 일단 제안드려봅니다🤪

2023-09-19 14:50 UTC, regularPark commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +    // 임시회원이 아닌 유저가 정상적인 전화번호를 등록하려고 할때
주석 굿👍👍

2023-09-19 14:50 UTC, regularPark commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +      mutateLinkData(customerRegisterType[0].id);
깃짱의 디스커션과 타입을 보아하니 응답이 `registerType`의 배열 같은데 전화번호 하나에 대한 응답으로 customers 배열이 오는 것은 조곰 어색하긴 하네요😅 그러다보니 해당 api의 응답으로는 1명 혹은 0명에 대한 정보일 텐데 `.[0]`로 뎁스를 하나 더 들어가다보니 한번 턱! 걸리는 느낌이네욧.

2023-09-19 14:50 UTC, regularPark commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +    if (!customerRegisterType) return;
이 early return 문은 응답 자체가 안왔을 때를 대비한 건가요?

2023-09-20 01:37 UTC, kangyeongmin commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +    if (!customerRegisterType) return;
아래에서 옵셔널 사용을 피하기 위해 early return 하였어요!

2023-09-20 01:41 UTC, kangyeongmin commented on frontend/src/types/domain/customer.ts
> +export type RegisterType = 'temporary' | 'register';
api 명세상의 이름을 프론트 사용처에서도 동일하게 하는 것이 추후에 헷갈릴 일이 줄어들거라 생각하는데, 레고의 생각은 어떠세요?!

2023-09-20 01:43 UTC, kangyeongmin commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +      mutateLinkData(customerRegisterType[0].id);
맞아요.. 0명 혹은 1명일때 배열인 경우가 이 밖에도 있는데, 아직도 어색하긴하네요 😅

2023-09-20 02:27 UTC, regularPark commented on frontend/src/types/domain/customer.ts
> +export type RegisterType = 'temporary' | 'register';
명세상의 이름이라면 받아들여야겠군요😂

2023-09-20 10:53 UTC, 2yunseong reviewed
복잡한 플로우인데 고생하셨습니다~!  백엔드와 이야기할 부분한 comment로 남겨두었어요.

2023-09-20 10:53 UTC, 2yunseong commented on frontend/src/api/get.ts
> +};
다른 예외케이스로 백엔드에서 혹시 401을 반환하는 부분이 있는지 검증해봐야할 것 같습니다! (그러면 로그인 페이지로 넘어가니까요)

2023-09-20 11:08 UTC, regularPark approved these changes
굿 뜨👍

2023-09-22 01:36 UTC, merged