[FE] refactor: react-icons를 @react-icons/all-files와 svg 파일로 대체한다.
woowacourse-teams/2023-stamp-crush pull request #717
Opened 2023-09-19 12:41 UTC by regularPark

## 주요 변경사항

- `react-icons`를 `@react-icons/all-files`와 `svg`파일로 대체하였습니다.
- 그 결과 번들 파일의 크기가 기존 15.26MB에서 2.14MB로 감소하였습니다.

## 리뷰어에게...

최적화 전 - 15.26MB
<img width="1440" alt="스크린샷 2023-09-19 오후 9 22 19" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/045d7f2e-aa15-4e21-8852-79d48caeac6a">

최적화 후 - 2.14MB
<img width="1440" alt="스크린샷 2023-09-19 오후 9 17 59" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/798fefd4-34b4-44fc-b93b-67632fc85d04">

## 관련 이슈

closes #715 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-19 14:17 UTC, 2yunseong requested changes
레! 고!생하셨습니다~!! 덕분에 번들 사이즈가 시원하네요 ^^

2023-09-19 14:51 UTC, regularPark commented on frontend/webpack.common.js
>    ],
앗 테스트하다 커밋에 빨려들어갔군요! 즉시 수정하겠슴다

2023-09-20 01:45 UTC, kangyeongmin approved these changes
진짜 수고하셨네요,,,
👍🏻*100개 드릴게요!

2023-09-20 10:34 UTC, 2yunseong approved these changes

2023-09-20 10:58 UTC, merged