[BE] feat: 회원 탈퇴 기능 구현
woowacourse-teams/2023-stamp-crush pull request #771
Opened 2023-09-25 09:06 UTC by eunkeeee

## 주요 변경사항

## 리뷰어에게...

## 관련 이슈

closes

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2023-09-25 09:11 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +        customerRepository.delete(customer);
# 설명

쫄려서 일단 다 soft delete 했어요.
필요한 경우에 직접 delete하는걸로 해요.

---

soft delete 한 바람에 몇몇 엔티티에서 deleted 칼럼이 추가되었어요. 
이것도 flyway 통해서 관리해야 할 것 같은데, 이 스크립트는 내일 추가해둘게요

2023-09-25 09:11 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @OneToMany(mappedBy = "coupon", fetch = LAZY, cascade = CascadeType.ALL)
Coupon 지워질 떄 생명주기가 정확히 일치하는 
Stamp
Coupon Design
Coupon Policy

그리고 쿠폰 디자인에 얽힌 Coupon Stamp Coordinate은 
cascade all로 처리했어요

2023-09-25 09:11 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
> +    void 이것저것_많이_한_회원도_탈퇴할_수_있다() {
사실상 이 테스트가 메인이에요

2023-09-25 13:02 UTC, yenawee approved these changes
깃 쟝
수고했어요!

uri path 관련해서는 의견 함 고려해봐주세용
flyway 설정하고 개발 서버 머지되면 탈퇴 로직 함 테스트 해보죵!

2023-09-25 13:15 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
> +    void 이것저것_많이_한_회원도_탈퇴할_수_있다() {
이 테스트에 몇가지 시나리오 더 추가해놨어요

2023-09-26 00:18 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipController.java
> +    @DeleteMapping("/cancel-membership")
Url은 뭐 저도 그냥 일단 임시로 만든거라서 좋은거같은데? 오늘 가서 이야기해봐요

2023-09-26 00:19 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +        customerRepository.delete(customer);
이것도 어쩌면 스크립트 짜서 수동일수도 잇을거같아요 ㅋㅋ 업데이트드앳 기준으로 막...

2023-09-26 02:30 UTC, youngh0 requested changes
고생하셨습니다~

service 가 api 패키지에 위치하고 있는 것 같은데 확인 부탁드립니다~

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipController.java
> +    @DeleteMapping("/customers")
api 👍

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +public class VisitorCancelMembershipService {
이 친구는 application 패키지로 돌려보내주세요. api 패키지로 잘못 찾아온 것 같아요

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipController.java
> +public class VisitorCancelMembershipController {
네이밍에 Command 들어가면 컨벤션에 맞을듯합니다!

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +        couponRepository.deleteAll(coupons);
coupons 조회하고 지우는 거랑 deleteByCustomer() 이렇게 바로 couponRepo 에서 where 절에 customer 일치하는거 지우는 거랑 비교했을 때 깃짱이 써준 방식이 쿼리가 더 적게 나가나요?? 

몰라서 질문 드립니다~

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +    @NotNull
이 어노테이션은 왜 붙은걸까요??

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> -import jakarta.persistence.*;
굿~

2023-09-26 02:30 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +@ToString
쓸 일 없으면 제거해도 좋을듯합니다~

2023-09-26 02:30 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
> +class VisitorCancelMembershipAcceptanceTest extends AcceptanceTest {
꼼꼼한 테스트 좋네여

혹시 visitorAccessToken 잘못된 경우도 검증해보는거 어떻게 생각하세요?

2023-09-26 14:13 UTC, eunkeeee reviewed
레오씨 지금 말했던거중에
토큰 잘못되었을 때, 토큰이 잘못되었다고 검증이 전혀 안되고 있는 것 같아요 
한번 확인해볼게요

2023-09-26 14:13 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipService.java
> +    @NotNull
?!! 그러게요 ?? 붙인적이 없는데 ㅋㅋㅋㅌㅌㅋㅋ 날카로운 리뷰 ㄱㅅ요 !

2023-09-26 14:13 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
> +class VisitorCancelMembershipAcceptanceTest extends AcceptanceTest {
굳이요

2023-09-26 14:19 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/visitor/profile/VisitorCancelMembershipCommandController.java
> +package com.stampcrush.backend.api.visitor.profile;
여기랑 무관하긴 한데, 
flyway 패키지 잘못 잡은거 옮겨놨어요 
지피티는 이렇다고 말하긴 하는데, 아무래도 이거 잘못되더라도 진짜로 운영하기 전에 한번 바로잡아야 할 것 같아서 일단 시도해볼게요
 
<img width="521" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/72f81c0f-2766-436c-a8ef-df809d93b078">

2023-09-26 14:26 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/VisitorCancelMembershipAcceptanceTest.java
> +    @Disabled
이 테스트.... 통과가 안됩니다.... @yenawee 도와주세요...

2023-09-26 14:28 UTC, eunkeeee commented on backend/src/main/resources/db/migration/V6__delete_customer.sql
> +    ADD deleted BOOLEAN DEFAULT false;
@yenawee 
Flyway용 스크립트 추가 완료 🌟

2023-09-27 02:23 UTC, youngh0 approved these changes

2023-09-27 02:41 UTC, jundonghyuk approved these changes

2023-09-27 02:41 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @OneToMany(mappedBy = "coupon", fetch = LAZY, cascade = CascadeType.ALL)
cascade remove가 아니라 all로 따로 처리하신 이유가 있을까요 ?

2023-09-27 02:42 UTC, merged

2023-09-27 02:45 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @OneToMany(mappedBy = "coupon", fetch = LAZY, cascade = CascadeType.ALL)
깃: remove 로 바꿔도 되는데 머지를해버렷네요 다른 PR 에 remove 로 바꿔서 수정해서 올릴예정

2023-09-27 02:46 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @OneToMany(mappedBy = "coupon", fetch = LAZY, cascade = CascadeType.ALL)
깃: remove 로 해도 되는데 이미 all 로 되어있어서 그대로 놔둿슴다