[FE] feat: 회원 탈퇴 페이지를 구현한다.
woowacourse-teams/2023-stamp-crush pull request #786
Opened 2023-09-27 02:14 UTC by 2yunseong

## 주요 변경사항
- 회원 탈퇴 페이지를 만들었습니다
- 마이페이지에 넣었습니다.
## 리뷰어에게...
|마이페이지|회원탈퇴|
|--|--|
|<img width="378" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/d34a6a2a-0fb8-4e18-8a03-4d6f35993d38">|<img width="378" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/6201c36e-0376-4b68-8c8b-9bfff0e8da82">|

**조항 동의 시**
<img width="377" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/3a0a5270-4874-4d92-8bc1-7dd9b882b859">

## 관련 이슈

closes #775 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-09-27 08:39 UTC, regularPark approved these changes
well done, mate

2023-09-30 02:24 UTC, kangyeongmin requested changes
수고하셨어요 윤생!!

2023-09-30 02:24 UTC, kangyeongmin commented on frontend/src/pages/Customer/MyPage/index.tsx
로그아웃 탭을 맨 하단에 위치하는게 어떨까요??

2023-10-02 05:16 UTC, 2yunseong commented on frontend/src/pages/Customer/MyPage/index.tsx
그럴러면 현재 코드 구조를 바꿔야 해서 ㅠㅠ 다음에 바꿔보겠습니다!

2023-10-02 05:17 UTC, merged