[FE] feat: 내 정보 변경 페이지 구현 및 기타 개선
woowacourse-teams/2023-stamp-crush pull request #822
Opened 2023-10-04 10:07 UTC by kangyeongmin

## 주요 변경사항

#815 제나의 의견을 중심적으로 반영하였습니다.

<p align="center">
<img alt="스크린샷 2023-10-04 오후 7 04 38" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/e4b0a664-faaf-43dc-95a6-e60071661aa7" width="32%">
<img alt="스크린샷 2023-10-04 오후 7 05 47" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/b1f3a0eb-40cd-486f-86fa-7ef81189577d"  width="32%">
<img width="462" alt="스크린샷 2023-10-04 오후 7 07 24" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/f5f4c294-e681-4894-a7b9-66aa24db6464">
</p>

1. 회원탈퇴를 한 뎁스 숨길 수 있는 '내 정보 변경' 페이지를 구현하였습니다.
2. 추후에 api 가 구현되면 닉네임 수정, 전화번호 수정 등의 기능을 넣어도 좋을 것 같습니다.
3. 가장 최근의 내역이 앞으로 위치해야할 것 같아서 내역들을 reverse() 하였습니다.
4. `내 리워드`, `리워드 사용내역`, `스탬프 적립내역`이 아무것도 없을 때를 대응하였습니다.
5. 로그아웃이 맨 마지막에 위치하는 것이 자연스러울 것 같아 마이페이지 옵션 순서를 조정하였습니다. 

## 리뷰어에게...

## 관련 이슈

closes #815

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2023-10-04 15:50 UTC, yenawee commented
> 회원 탈퇴를 한 뎁스 숨긴 것 좋습니다👍 혹시 내 정보 변경 단계에서 회원탈퇴 말고 더 할 수 있는 일이 있을까요?

지금은 api 가 없지만 닉네임 변경이나 핸드폰 번호 변경같은거 추가해도 좋을거같고
내 정보 확인 정도는 지금 있는 프로필 조회 api 가지고 넣어놔도 좋을거같아요

2023-10-05 07:16 UTC, 2yunseong requested changes
몇개만 같이 이야기 나눠봐요!! 고생하셨습니다! 👍

2023-10-05 07:16 UTC, 2yunseong commented on frontend/src/pages/Customer/RewardList/index.tsx
> +    return (
&& 조건으로 변경되어야 할 것 같습니다..!

2023-10-05 07:16 UTC, 2yunseong commented on frontend/src/pages/Customer/MyPage/index.tsx
> +        )}
저도 고민했던 건데 FeedbackLink를 어떻게 통일시킬 방법이 없을까 고민이되네용

2023-10-06 01:45 UTC, kangyeongmin commented on frontend/src/pages/Customer/RewardList/index.tsx
> +    return (
아 저거 ui 보려고, 테스트 하다가 남겨놓은건데 삭제가 안되엇네요 !!!!
나이스 캐치입니다 👍🏻👍🏻👍🏻👍🏻

2023-10-06 01:52 UTC, kangyeongmin commented on frontend/src/pages/Customer/MyPage/index.tsx
> +        )}
그쵸.. semantic tag 측면인 점도 있고 onClick핸들러 함수의 유무가 다르니까, 현재로서는 저방법이 최선인 것 같다는 생각도 드네요..!

2023-10-06 05:29 UTC, 2yunseong commented on frontend/src/pages/Customer/MyPage/index.tsx
> +        )}
흑흑 어쩔수없죠

2023-10-06 05:29 UTC, 2yunseong approved these changes

2023-10-06 05:32 UTC, merged