[FE] bug: 전화번호 등록 성공 후 알림 메시지를 수정한다.
woowacourse-teams/2023-stamp-crush pull request #824
Opened 2023-10-05 02:27 UTC by regularPark

## 주요 변경사항

🚨[문제상황] 고객모드에서 정상적으로 전화번호를 등록한 뒤 메인페이지로 이동했을 때 전화번호를 등록해달라는 알림과 함께 잠시 동안 전화번호 등록화면으로 다시 리다이렉트되는 현상 발견했습니다😭

😞[원인] 메인페이지로 이동하였음에도 customerProfile을 최신화하지 않음. 기존 설계와는 달라진 현재 로직으로 `staleTime:infinity` 같은 속성이 `invalidateQueries`의 동작을 막는다고 판단 -> 그러나 useCustomerProfile훅을 다시 호출하지 않는 이상 `invalidateQueries`로는 원하는 타이밍(전화번호 등록 버튼을 누르는 순간)에는 전화번호가 여전히 `null`로 유지되고 있었습니다.

💉[해결방법] `staleTime` 속성 제거, 동시에 UX를 개선하기 위해 가입 환영 페이지 제작,  가입이 완료되었음을 alert로 알리는 것보다 가입 완료되었다는 페이지를 보여주는 동시에, 가입 환영페이지 단에서 customerProfile을 리페치하여, UX를 개선하도록 하였습니다.🤔

## 리뷰어에게...

대충 이런 드자인
<img width="378" alt="스크린샷 2023-10-05 오전 11 07 14" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/0744e272-0b3d-498b-a141-0fc2389c5f07">

## 관련 이슈

closes #811

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-05 06:57 UTC, kangyeongmin requested changes
레고!! 1초뒤에 이동하는 가입 환영페이지 아이디어 너무 좋아요 👍🏻

다만, 페이지 단의 useEffect에서 일일히 검사후 redirect 시켜주는것은 sideEffect가 너무 많아보입니다. 버그 추적도 어렵고, 저번에 토큰이 없을 때 로그인 페이지로 리다이렉트 시킬때 정상적으로 작동하지 않았는데 그 당시의 로직(모든 페이지 단에서 useEffect로 검증)과 똑같아서 염려되네요. 

PrivateProvider를 구현했던 방식과 동일하게 PhoneNumberRegisterProvider와 같은 것을 구현하여 CustomerRoot 단에서 한번의 useEffect로 검증해서 리다이렉트 시키는 것은 어떨까요?

특히 이부분은 저도 궁금했던 부분이라 내일 페어프로그래밍으로 함께 집중해서 하는 것도 어떨까 싶네요!!

2023-10-05 07:44 UTC, 2yunseong requested changes
고생하셨습니다~! 👍

2023-10-05 07:44 UTC, 2yunseong commented on frontend/src/hooks/useCustomerRedirectRegisterPage.ts
> +  }, [customerProfile]);
hasPhoneNumber라는 상태 필요없이 그냥 사용하는 부분에서 검사하는건 어떤가요?? 불필요한 상태가 늘어난 것 같다는 생각입니다~~

아래 사용처에서도 어차피 useEffect를 사용해서 customerProfile을 관찰하는데, hasPhoneNumber가 결국 customerProfile에서 파생할 수 있는 상태라고 생각이 들어요.

```ts
  useEffect(() => {
   /* 사용하는 상태는 hasPhoneNumber지만, 결국 useEffect는 customerProfile의 
변경만 추적하고 있음 */
    if (!hasPhoneNumber) redirectCustomerWithoutPhoneNumber();
  }, [customerProfile]);
```

혹시 이 부분에서 hasPhoneNumber를 사용해야 할 다른 문제가 있었나요?

개인적인 생각으로는 레고가 발견하신 staleTime : infinity를 없앰으로써 해결이 되지 않았을까 싶네용

2023-10-05 07:44 UTC, 2yunseong commented on frontend/src/pages/Customer/RewardList/index.tsx
> +  }, [customerProfile]);
결국 모든 사용처(인가요?) useEffect를 통해 if(hasPhone ..) 을 검사하고, redirect를 시켜주는거 같은데, 이러면 useCustomerRedirectRegisterPage 안에서 useEffect를 호출해도 될 것 같네요 !

2023-10-05 08:17 UTC, regularPark commented
> 레고!! 1초뒤에 이동하는 가입 환영페이지 아이디어 너무 좋아요 👍🏻
> 
> 다만, 페이지 단의 useEffect에서 일일히 검사후 redirect 시켜주는것은 sideEffect가 너무 많아보입니다. 버그 추적도 어렵고, 저번에 토큰이 없을 때 로그인 페이지로 리다이렉트 시킬때 정상적으로 작동하지 않았는데 그 당시의 로직(모든 페이지 단에서 useEffect로 검증)과 똑같아서 염려되네요.
> 
> PrivateProvider를 구현했던 방식과 동일하게 PhoneNumberRegisterProvider와 같은 것을 구현하여 CustomerRoot 단에서 한번의 useEffect로 검증해서 리다이렉트 시키는 것은 어떨까요?
> 
> 특히 이부분은 저도 궁금했던 부분이라 내일 페어프로그래밍으로 함께 집중해서 하는 것도 어떨까 싶네요!!

Provider를 사용하여 해당 훅을 사용하기 위해 작성했던 보일러 플레이트 (사이드 이펙트가 우려되는 `useEffect`)를 전부 제거하였습니다. 저도 이 부분이 고민이었는데, 윤생의 Provider와 GPT의 도움을 받아 구현해냈는데요. 

[75502c1](https://github.com/woowacourse-teams/2023-stamp-crush/pull/824/commits/75502c13ff2e370539d1c9d241c41df4940f5a68)

위 커밋에서 확인하실 수 있습니다.

제가 수차례 테스트를 하고서 푸쉬했습니다만, 제가 놓친 게 있을 수 있다고 생각해 내일 모두 모인 자리에서 테스트 한번 더 해보고 그때 어프루브해주시면 좋을 것 같습니다.

2023-10-05 08:18 UTC, regularPark commented on frontend/src/pages/Customer/RewardList/index.tsx
> +  }, [customerProfile]);
일단 오류를 해결하려고 주먹구구식으로 코드를 짜다보니 💩같은 보일러플레이트가 생겨버렸어요. provider 구현하여 해결하였습니다.😄

2023-10-05 08:26 UTC, 2yunseong commented
확인 완~ 내일봅시다

2023-10-06 02:08 UTC, kangyeongmin requested changes
레고~ Provider로 관리하니 useEffect도 줄어들고 관심사가 집중되어 훨씬 코드가 좋아진 것 같아요. 

그 밖의 몇가지 리뷰 남겼습니당~

2023-10-06 02:08 UTC, kangyeongmin commented on frontend/src/pages/Customer/Greeting/style.tsx
> +export const GreetingWrapper = styled.header``;
NicknameWrapper도 header인데 다른 태그를 줄 순 없을까요?
속성이 없는 styled-component라 컨벤션에도 어긋나는 것 같아요

p 태그로 변경하고 
```javascript
<GreetingWrapper>저희 스탬프크러쉬 서비스를 이용해주셔서 감사합니다!</GreetingWrapper>
      <p>잠시 후 서비스로 이동합니다.</p>
```
이부분을 하나의 태그(GreetingWrapper)로 감싸주는 것은 어떨까요?

<img width="356" alt="스크린샷 2023-10-06 오전 11 00 43" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/a4ccff77-837c-4b0c-886e-a3e0e341727d">

앗 그리고 이 부분 현재 문장 간격이 좁은 것 같아서 
`line-height: 24px` 도 추천!

2023-10-06 02:08 UTC, kangyeongmin commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
> +    e.preventDefault();
👍🏻👍🏻👍🏻👍🏻

2023-10-06 02:08 UTC, kangyeongmin commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
>      }
여기 삭제된 부분에, 추가된 `navigate(ROUTER_PATH.greeting);`를 넣는 건 어떨까요?
onSuccess는 deprecated 되어 지양하는게 좋을 것 같아요!
<img width="440" alt="스크린샷 2023-10-06 오전 11 03 17" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/d5c5748f-180f-43fd-a3d1-9754fa9574ec">

2023-10-06 02:08 UTC, kangyeongmin commented on frontend/src/provider/CustomerProfileProvider.tsx
> +    ) {
`useCustomerPropfile` 훅에서 `customerProfile`을 사용할 때, 계속 옵셔널로 뽑아쓰게 되는 것 같은데, 훅 내부에서 undefined를 막아서 옵셔널 사용을 피할 순 없을까요??

2023-10-06 02:16 UTC, regularPark commented on frontend/src/pages/Customer/InputPhoneNumber/hooks/useInputPhoneNumber.ts
>      }
[d8f1408](https://github.com/woowacourse-teams/2023-stamp-crush/pull/824/commits/d8f1408bdf3eb6033e7b279ef18def4f28ca0027)

2023-10-06 02:16 UTC, 2yunseong approved these changes
UX가 확실히 좋은 것 같아요!! 고생하셨어요 레고!

2023-10-06 02:17 UTC, regularPark commented on frontend/src/pages/Customer/CouponList/index.tsx
> +  // }, [customerProfile]);
[f0a8cd4](https://github.com/woowacourse-teams/2023-stamp-crush/pull/824/commits/f0a8cd49080d2fb4b28b29bdb07072ee86262aa2)

2023-10-06 02:18 UTC, regularPark commented on frontend/src/pages/Customer/Greeting/style.tsx
> +export const GreetingWrapper = styled.header``;
현재 컨테이너 내부의 p태그에 스타일이 들어가 있어 각각 h1, h2로 변경했습니다. (이동한다는 메시지만 p)

[89f40a0](https://github.com/woowacourse-teams/2023-stamp-crush/pull/824/commits/89f40a027d288dfa60f866a8d9af9eb3e0877ec8)

2023-10-06 04:22 UTC, kangyeongmin approved these changes
어푸룹!

2023-10-06 04:22 UTC, merged