[FE] feat: [중요도 중하] 쿠폰 제작 페이지에서 현재 쿠폰을 확인할 수 있으면 더 편리할 것 같다고 제안합니다.
woowacourse-teams/2023-stamp-crush pull request #831
Opened 2023-10-05 11:00 UTC by regularPark

## 주요 변경사항

- 크게 변경사항 없이 간단해보여 구현해봤습니다. 대충 아래 스크린샷 같은 너낌입니다.

<img width="813" alt="스크린샷 2023-10-05 오후 7 59 39" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/9d4002d1-e868-4543-aea6-e6599ca686e8">

## 리뷰어에게...

## 관련 이슈

closes #826 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-05 11:04 UTC, yenawee commented
제가 지금 알람 미어캣 상태라 레고의 피알을 바로 구경해버렸네여

현재 쿠폰 이미지 쟤를 박스테두리 치고 쪼끔만 더 작게 하고 배경색 약간만 다르게 해서 예시 이미지라는 사실을 딱 한눈에 볼수있으면 좋을거같아용

2023-10-06 00:40 UTC, 2yunseong approved these changes
👍 👍

2023-10-06 00:59 UTC, yenawee commented
코멘트 어프룹드립니다 👍

2023-10-06 02:23 UTC, kangyeongmin requested changes
렉오~  저도 원했던 기능인데, 빠른 반영 아주 굿입니다.

몇가지 리뷰 남겼습니다~ 재요청 주세용!

2023-10-06 02:23 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/components/CurrentCouponImages/index.tsx
> +      <label>뒷면</label>
```
<label> 태그는 사용자 인터페이스(UI) 요소의 라벨(label)을 정의할 때 사용합니다.
<label> 요소는 for 속성을 사용하여 다른 요소와 결합할 수 있으며, 이때 <label> 요소의 for 속성값은 결합하고자 하는 요소의 id 속성값과 같아야 합니다. 또한, <label> 요소를 결합하고자 하는 요소 내부에 위치시키면 for 속성을 사용하지 않더라도 해당 요소와 결합시킬 수 있습니다.

이러한 <label> 요소는 브라우저에 의해 일반적인 텍스트로 랜더링되지만, 사용자가 마우스로 해당 텍스트를 클릭할 경우 <label> 요소와 연결된 요소를 곧바로 선택할 수 있어 사용자의 편의성을 높일 수 있습니다.

<label> 요소를 사용할 수 있는 요소는 다음과 같습니다.
- <button>, <input>, <meter>, <output>, <progress>, <select>, <textarea>
```

`label`은 클릭되거나 입력되는 요소에 연관짓는 느낌이라 현재와는 조금 어울리지 않는 것 같기도 한것 같아요 🧐 span 태그는 어떨까용??

2023-10-06 02:23 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/components/CurrentCouponImages/style.tsx
> +  }
child 태그 자체에서 부여 가능한 속성이라면 해당 태그에 주는 것이 가독성이 더 높아질 것 같아요!!

2023-10-06 02:23 UTC, kangyeongmin commented on frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
> +                );
이거 고냥 createdType 자체에서 넣어 줄순 없을까용?? step 별로 switch문의 관심사가 집중 되어 있어도 좋을 것 같아요!

2023-10-06 04:31 UTC, regularPark commented on frontend/src/pages/Admin/ModifyCouponPolicy/index.tsx
> +                );
위 세가지 피드백에 대해서 반영하였습니다.😄

[7822268](https://github.com/woowacourse-teams/2023-stamp-crush/pull/831/commits/7822268d7671dd7526c7adf8ce7def00ed8b2696)

2023-10-06 04:33 UTC, kangyeongmin approved these changes
어프룹!

2023-10-06 04:33 UTC, merged