[BE] refactor: 카페 정책과 카페 디자인 복사 로직을 제거한다.
woowacourse-teams/2023-stamp-crush pull request #852
Opened 2023-10-08 14:17 UTC by jundonghyuk

## 주요 변경사항
자세한 내용은 이슈를 참고해주세요 ! #842 

## 리뷰어에게...
사실 테스트코드를 많이 고쳤지, 프로덕션 코드는 큰 변화가 없습니다 !

프로덕션코드의 변경 내용은 이슈를 참고해주시면 좋습니다 !
## 관련 이슈

closes #842 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-10 06:28 UTC, eunkeeee requested changes
레오하디 수고했습니다!
코드로는 딱히 고칠 부분이 없어보이는데,
머지 전에 꼭 Flyway에 스키마 변경사항을 미리 적어놓아야 데이터베이스 상에서 충돌이 안나기 때문에 스크립트 작성이 안되어있어서 Request Changes 할게요!

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @ManyToOne(fetch = LAZY, cascade = CascadeType.ALL)
확인이요!

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/cafe/CafeCouponDesignRepository.java
> +    Optional<CafeCouponDesign> findByCafeAndDeletedIsFalse(Cafe cafe);
전부 꼼꼼히 붙여줬네요!

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/cafe/CafePolicyRepository.java
> +    Optional<CafePolicy> findByCafeAndDeletedIsFalse(Cafe cafe);
굳굳

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/coupon/CouponDesignRepository.java
> -public interface CouponDesignRepository extends JpaRepository<CouponDesign, Long> {
잘가렴

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +        return cafePolicy.isPrevious();
좋네요

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
> +        return deleted;
훌륭하네요

2023-10-10 06:28 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    @JoinColumn(name = "cafe_coupon_design_id")
DDL에 대한 변경은 Flyway 통해서 배포 전에 맞춰줘야 합니다!

2023-10-11 13:53 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
> +    public void addCouponStampCoordinate(CafeStampCoordinate cafeStampCoordinate) {
양방향 연관관계 매핑할때

cafeStampCoordinate.setCafeCouponDesign(this);

이런거 해줘서 
cafeStampCoordinate 도 CafeCouponDesign 이랑 관계 맺어줘야 하지 않나여?? 

옛날에 유투브에서 봤던 기억....
https://www.youtube.com/watch?v=brE0tYOV9jQ
https://www.youtube.com/watch?v=hsSc5epPXDs

테스트 코드 문제 없으니까 괜춘한거같기도 하고 🤔

2023-10-12 02:30 UTC, youngh0 approved these changes

2023-10-12 02:41 UTC, eunkeeee approved these changes
좋네요
플라이웨이 언더바 2개 하세요

2023-10-12 04:00 UTC, yenawee approved these changes

2023-11-13 11:35 UTC, gitchannn commented
2기에서 새롭게 작성하게 되어 close하겠습니다..ㅜㅜ

2023-11-13 11:35 UTC, closed without merging