[FE] refactor: 사장모드의 반응형을 구현한다(for 글렌)
woowacourse-teams/2023-stamp-crush pull request #860
Opened 2023-10-12 07:36 UTC by regularPark

## 주요 변경사항

### 반응형에 구구절절 설명이 필요하겠습니까. 보여드리겠습니다.

<img width="348" alt="스크린샷 2023-10-12 오후 4 26 16" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/b8876417-497a-45e8-9f8f-33203a6e6dc2">
<img width="347" alt="스크린샷 2023-10-12 오후 4 13 41" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/0c04a394-dd55-403e-aa0e-a65a67a9ca62">

<img width="347" alt="스크린샷 2023-10-12 오후 4 13 57" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/1b9b8d14-5121-4dbb-bff4-af00a7ea3e6f">
<img width="346" alt="스크린샷 2023-10-12 오후 4 14 30" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/d08f77e2-acc5-43b8-b589-853008f3e31e">

## 리뷰어에게...

## 관련 이슈

closes #595 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-12 07:48 UTC, kangyeongmin commented
글렌이 반하는거 아녜요??

2023-10-12 07:48 UTC, 2yunseong commented
캬

2023-10-12 07:48 UTC, eunkeeee commented
@seokjin8678 글렌 아침에 한거 벌써 완료

2023-10-12 07:49 UTC, 2yunseong approved these changes
👍 👍 👍

2023-10-12 07:49 UTC, eunkeeee approved these changes

2023-10-12 07:51 UTC, eunkeeee approved these changes
Lego, thanks for your contribution.
It was so fast that i thought i gave this issue like several weeks ago
you are one of the best frontend developer ive ever seen!

2023-10-12 07:51 UTC, eunkeeee commented on frontend/src/components/Template/style.tsx
> +    display: flex;
역시 품절남답게 flex 하시네요

2023-10-12 07:51 UTC, eunkeeee commented on frontend/src/pages/Admin/CustomerList/style.tsx
> +    height: 100%;
이런 스펙이라면, 아이폰3도 지원하겠어요!

2023-10-12 07:56 UTC, kangyeongmin requested changes
참말로 수고하셨습니다... 두가지 코멘트만 확인 부탁드려요~

2023-10-12 07:56 UTC, kangyeongmin commented on frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
> +  const tabToShow = userType === 'admin' ? ADMIN_TABS : CUSTOMER_TABS;
tabToShow는 헷갈리는거 같은데, 그냥 간단하게 tabs 어떤가요?!

2023-10-12 07:56 UTC, kangyeongmin commented on frontend/src/components/Template/CustomerTemplate/BottomTabBar/style.tsx
> +  }
미디어쿼리 만으로 속성이 조절될 수는 없을까요? isShow로 중복 처리한 이유가 궁금합니다!

2023-10-12 08:01 UTC, regularPark commented on frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
> +  const tabToShow = userType === 'admin' ? ADMIN_TABS : CUSTOMER_TABS;
보여줄 탭이라는 의미에서 tabToShow 안괜찮나요 ㅎㅎ;

2023-10-12 08:03 UTC, regularPark commented on frontend/src/components/Template/CustomerTemplate/BottomTabBar/style.tsx
> +  }
`BottomTabBar`에서 type alias로 'customer' | 'admin'을 작성했다가 그 타입을 이용해서 구현해야겠다는 것에 좀 매몰된 것 같아요. 실수했네요😅

2023-10-12 08:04 UTC, yenawee commented
레고 진짜 대단한 인재네요....

PR 본문도 넘 멋있네요 🤗🤗
역시 프론트 피알은 구경이 넘 재밌어~~

2023-10-13 08:38 UTC, kangyeongmin commented on frontend/src/components/Template/CustomerTemplate/BottomTabBar/index.tsx
> +  const tabToShow = userType === 'admin' ? ADMIN_TABS : CUSTOMER_TABS;
ㅎㅎㅎ그럼 tabsToShow 어때요 배열이잔아요~~

2023-10-13 08:39 UTC, kangyeongmin approved these changes
옥케이~

2023-10-13 08:39 UTC, merged