[BE] feat: 리워드 사용 기능을 구현한다
woowacourse-teams/2023-stamp-crush pull request #87
Opened 2023-07-15 18:21 UTC by jundonghyuk

## 주요 변경사항
- 등록회원, 임시회원의 레포지토리 생성
- 카페, 사장 생성사 추가
- 리워드 사용 기능 구현

## 리뷰어에게...
- 아직 리워드 사용 기능 밖에 구현하지 않았습니다 ! 주기를 짧게 가져가자해서 다음 기능도 
## 관련 이슈

closes
close #82 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 00:23 UTC, eunkeeee requested changes
리뷰 남겼습니다!

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +    private boolean used;
dto 필드는 `final`로 만들어도 좋을 것 같아요!

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +@Getter
저희 저번에 `@RequiredArgsConstructor` 사용하기로 했으니 어노테이션 추가하고 아래 생성자 지워도 괜찮을 것 같슴다

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/reward/Reward.java
> +    protected Reward() {
이친구를 아래 생성자보다 아래로 내리면 좋을 것 같슴다

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    protected Customer() {
ditto

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
> +    protected Owner() {
ditto

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/user/RegisterCustomer.java
> +    protected RegisterCustomer() {
ditto

2023-07-16 00:23 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    public abstract boolean isRegistered();
(몰라서 물어보는거임)
abstract 메서드로 만들지 말고, 

dtype 기준으로 비교하는 방법은 없을까요?

2023-07-16 00:53 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/reward/RewardService.java
> +    public void updateUsed(RewardUsedUpdate rewardUsedUpdate) {
비즈니스 입장에서는 used를 업데이트하는건 너무 구체적이니깐
`useReward` 정도 어떤가요?

2023-07-16 04:14 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +    private boolean used;
`final`을 추가하고 `@RequiredArgsConstructor`를 이용해보겠습니다 !
감사합니다 ㅎㅎ

2023-07-16 04:14 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +@Getter
ditto~

2023-07-16 04:19 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/reward/Reward.java
> +    protected Reward() {
넵 :)

2023-07-16 04:19 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    protected Customer() {
넵 :)

2023-07-16 04:19 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/Owner.java
> +    protected Owner() {
넵 :)

2023-07-16 04:19 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/RegisterCustomer.java
> +    protected RegisterCustomer() {
넵 :)

2023-07-16 04:34 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/reward/RewardService.java
> +    public void updateUsed(RewardUsedUpdate rewardUsedUpdate) {
고민을 되게 많이했는데요 ! 
좋은 것 같습니다 !

2023-07-16 04:35 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +    public abstract boolean isRegistered();
dtype은 테이블내에만 있고 객체안에서는 없어서 상위 타입인 `Customer`로 받아버리면 비교하기가 힘든것같아요. (상속의 단점인가..?
옛날 체스게임의 Pawn이 생각나는군요)
한 번 다른 방법도 있나 찾아보고 공유해드릴게요 !

2023-07-16 07:51 UTC, eunkeeee requested changes

2023-07-16 07:51 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +    @AssertTrue
이 어노테이션은 뭔가요!!!

2023-07-16 07:51 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
> +        System.out.println("here");
지워주세요 ><

2023-07-16 13:04 UTC, youngh0 requested changes
코드 깔쌈하네요 ^.^

그냥 제 생각 몇개 적어봤습니다. RequestBody랑 ModelAttribute섞어서 사용하신 이유가 궁금합니다 ㅎㅎ

2023-07-16 13:04 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
> +
예외 테스트 꼼꼼하네요😎

2023-07-16 15:02 UTC, yenawee requested changes

2023-07-16 15:02 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
> +class RewardServiceTest {
테스트 꼼꼼히 작성하시는거 배워갑니다👏👏

2023-07-17 05:53 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/reward/dto/request/RewardUsedUpdateRequest.java
> +    @AssertTrue
true만 들어와야 한다는 어노테이션입니다. ~~!!

used= true여야만 하기 때문에 적용했습니다

2023-07-17 05:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
> +                                                           @ModelAttribute RewardFindRequest rewardFindRequest) {
`@ModelAttribute`는 쿼리 스트링이나 폼데이터를 받는것으로 알고있어요!

2023-07-17 06:39 UTC, eunkeeee requested changes

2023-07-17 06:39 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/reward/RewardApiController.java
> +    public ResponseEntity<Void> updateRewardUsed(@PathVariable("customerId") Long customerId,
이 로직이 잘 돌아가는지 테스트하고 싶은데, 더미 데이터도 같이 PR에 넣어주셔도 좋을 것 같아요!

2023-07-17 06:39 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFind.java
> +public class RewardFind {
이름 `RewardQueryDto` 어때요

2023-07-17 06:39 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFindResult.java
> +public class RewardFindResult {
그냥 `RewardDto`로 만들고, 
여기서는 테이블 내용 전부 보내는거 어떨까요?
서비스가 반환하는 디티오라 좀 더 재사용성 높게 가져가고,
컨트롤러에서 좀더 걸러서 Response 객체로 만들어서 반환해도 좋을 것 같아요

2023-07-17 06:39 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFindResult.java
> +public class RewardFindResult {
현재 모양은 서비스 디티오나, 리스폰스 객체나 똑같이 생겨서 나눈 의미가 없을 것 같아요!
나중에 리워드를 요래저래 더 자세히 보여줄 일이 있을 것 같으니 먼저 엔티티와 비슷한 모양으로 만들어서 서비스가 반환하도록...먼느알?

2023-07-17 06:41 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
> +        RewardUsedUpdate rewardUsedUpdate = new RewardUsedUpdate(unusedReward.getId(), registerCustomer_1.getId(), cafe_1.getId(), true);
여기도 마지막 true가 뭔지, 원시값 포장 객체 만들면 좋을 것 같아요

2023-07-17 07:45 UTC, yenawee approved these changes

2023-07-17 07:45 UTC, eunkeeee approved these changes
머지 가즈아

2023-07-17 07:45 UTC, youngh0 approved these changes

2023-07-17 07:46 UTC, merged

2023-07-17 10:33 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFind.java
> +public class RewardFind {
통일한걸로 가겠습니다 ㅎㅎ

2023-07-17 10:39 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/reward/dto/RewardFindResult.java
> +public class RewardFindResult {
저도 동의하는데요 ! 그런데 현재 
reward의 필드는 5개입니다.
1. `id`
2. `name`
3. `used
4. `customer`
5. `cafe`

그런데 지금 리워드를 찾는것은 3, 4, 5 조건으로 필터링하여 찾고 있습니다.
이미 3, 4, 5조건이 넘어왔으니 이를 반환은 안해도 되겠다 싶었어요.
그러므로 1, 2 정보만 남아있습니다  .. !

2023-07-17 10:40 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/application/reward/RewardServiceTest.java
> +        RewardUsedUpdate rewardUsedUpdate = new RewardUsedUpdate(unusedReward.getId(), registerCustomer_1.getId(), cafe_1.getId(), true);
`Dto`인데 포장객체를 써도괜찮을까요 ? 내일 같이 얘기 나눠봐도 괜찮을 것 같아요