[FE] refactor: 카페 관리, 스탬프 적립 화면의 로딩/에러 핸들링한다.
woowacourse-teams/2023-stamp-crush pull request #879
Opened 2023-10-19 08:37 UTC by regularPark

## 주요 변경사항

- 카페 관리, 스탬프 적립에서 일어나는 로딩/에러에 대한 핸들링을 구현하였습니다.
- gif의 프레임이 떨어지다보니 스켈레톤이 좀 허접스러워 보이지만 실제로 보면 저 정도는 아닙니다.

![manage_cafe_handling](https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/ca898a30-988b-4869-8f20-ad6a9e53d0a1)

![earn_stamp_handling](https://github.com/woowacourse-teams/2023-stamp-crush/assets/90092440/71abadf5-447c-4c3e-97ec-89100e6f1faf)

## 리뷰어에게...

## 관련 이슈

closes #875 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [ ] `milestone` 설정

2023-10-24 01:14 UTC, kangyeongmin requested changes
레고! 스켈레톤 처리 꼼꼼하게 하신 부분들 인상 깊었어요.

질문하나 남겼는데 확인 부탁드림미다~

2023-10-24 01:14 UTC, kangyeongmin commented on frontend/src/pages/Admin/EarnStamp/components/EarnStampSkeleton.tsx
> +const skeletonLoading = keyframes`
컨벤션과 다르게 이 컴포넌트만 style.tsx 파일 분리를 안하신 이유가 있을까요??

2023-10-24 06:58 UTC, 2yunseong requested changes
고생하셨습니다!

2023-10-24 06:58 UTC, 2yunseong commented on frontend/src/pages/Admin/ManageCafe/style.tsx
> +export const SkeletonPreview = styled(Skeleton)`
common으로 빼도 좋겠군요 저도 쓰게요 ㅋㅋ

2023-10-24 06:58 UTC, 2yunseong commented on frontend/src/pages/Admin/EarnStamp/components/CouponIndicator/index.tsx
> +  );
어쩔수 없는 부분이지만 이부분들이 다 얽혀있어서 컴포넌트가 굉장히 커지네요 ..!

2023-11-03 11:44 UTC, eunkeeee commented
멋지네용 짝짝짝

2023-11-06 11:12 UTC, regularPark commented on frontend/src/pages/Admin/ManageCafe/style.tsx
> +export const SkeletonPreview = styled(Skeleton)`
스켈레톤은 이미 common에 있답니다😄

2023-11-06 11:14 UTC, regularPark commented on frontend/src/pages/Admin/EarnStamp/components/EarnStampSkeleton.tsx
> +const skeletonLoading = keyframes`
로직 하나 없이 return하는 tsx가 UI만 7줄이기에 한 파일에 작성했는데, 수정할까요?🥲

2023-11-07 06:25 UTC, kangyeongmin commented on frontend/src/pages/Admin/EarnStamp/components/EarnStampSkeleton.tsx
> +const skeletonLoading = keyframes`
넵 저도 사실 한 파일에 작성하는 방식을 선호하긴 하지만, 코드 컨벤션에 따라 코드스타일을 일관되게 통일하는 것이 더 중요하다고 생각이 듭니다!

```javascript
const EarnStampSkeleton = () => {
  return (
    <SkeletonContainer>
      <SkeletonHeader />
      <SkeletonSubHeader />
      <SkeletonCoupon />
    </SkeletonContainer>
  );
};

export default EarnStampSkeleton;
```

요부분만 따로 빠지면 될거 같아요!

2023-11-07 12:46 UTC, 2yunseong approved these changes

2023-11-09 13:59 UTC, regularPark commented on frontend/src/pages/Admin/EarnStamp/components/EarnStampSkeleton.tsx
> +const skeletonLoading = keyframes`
수정 완

[aa353b8](https://github.com/woowacourse-teams/2023-stamp-crush/pull/879/commits/aa353b87cfc7001fa69d17d9fdcba91e514e34ea)

2023-11-13 04:56 UTC, kangyeongmin approved these changes
레고 ~ 수고하셨어요.
이만 늦은 어푸룹 하겠습니다.

2023-11-13 04:56 UTC, merged