[BE] feat: 스탬프 개수를 기준으로 쿠폰 샘플을 조회한다.
woowacourse-teams/2023-stamp-crush pull request #88
Opened 2023-07-16 00:14 UTC by eunkeeee

## 주요 변경사항

- 쿠폰 샘플 조회 API 생성
- 쿼리 파라미터 `max-stamp-count`로 뒷면에 표시될 스탬프의 최대 개수를 필터링 가능

## 리뷰어에게...

- 코드가 아직 막 깨끗하지는 않은데, 다음 API 만들기가 급해서 일단 진행하겠습니다.
- 테스트코드가 아직 없는데, 월요일에 만나서 통합테스트 템플릿, service mock 테스트 등등 테스트 룰도 정해보면 좋을듯

## 관련 이슈

closes #71 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 00:56 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +    public static SampleCouponQueryResponse from(SampleCouponsDto sampleCoupons) {
- Response DTO, Service에서 사용하는 DTO 사이 변환 코드
- 형태가 약간 달라서 변환이 다소 빡셈...

2023-07-16 00:59 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java
> +public class SampleDataInitializer implements ApplicationRunner {
- [더미데이터 추가용 빈](https://engineerinsight.tistory.com/71#%E2%9C%94%203.%C2%A0%20Spring%EC%9D%98%C2%A0%40ApplicationRunner%EB%A5%BC%20%EC%82%AC%EC%9A%A9%ED%95%B4%20%EC%B4%88%EA%B8%B0%ED%99%94-1)
- `data.sql`에 더미데이터를 넣으면 엔티티를 사용해서 create table 쿼리를 날리는 시점 이전에 실행되는데, 이걸 막으려면 별도로 설정이 필요해서 이 방식을 선호함
- 현재는 앞면 1개, 뒷면 1개, 스탬프 1개만 넣어놓았고, 뒷면은 스탬프 8개 찍을 수 있는걸로 넣어놨음

2023-07-16 01:17 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +
이 Request DTO가 매우매우 복잡해서 일단 내부에서 사용하는 DTO는 재사용 가능성이 거의 없어서 다 안에다 넣어놨슴당

2023-07-16 12:38 UTC, jundonghyuk requested changes
안녕하세요 ! 코드 잘봤습니다 ㅎㅎ

잘 구현해주신 것 같아요

개별 코멘트 남겼습니다 !

2023-07-16 12:38 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +                ))
`SampleFrontImageDto`에 `SampleFrontImage`를 통해 만드는 정적팩터리메서드를 작성할 수 있을 것 같은데 어떻게 생각하시나요 ?
저같은 경우 `도메인`이 `Dto`를 의존하는것은 위험하지만 반대는 괜찮다고 생각해서 깃짱의 의견을 듣고싶네요 !

2023-07-16 12:38 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +                                ))
이 부분도 위에서 말한 것과 똑같습니다 !

2023-07-16 12:38 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +                ))
이 부분도요 !

2023-07-16 12:38 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +                .collect(Collectors.toList());
`.toList()`가 자바17(?)부터 추가된 걸로 알고있습니다 ! 
저는 이게 가독성이 조금 더 낫더라구요 ?? (써보시고 괜찮으시면 적용해도 괜찮을 것 같아유)

2023-07-16 12:38 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +        };
`Predicate`조건을 양방향 연관관계를 통한 list의 size 조회로 하는 방법은 어떠신가요 ??

2023-07-16 13:20 UTC, youngh0 requested changes
안녕하세요 깃짱

깔쌈한 코드 잘봤습니다. 리뷰 몇 개 달았는데 확인 부탁드립니다 ㅎㅎ 고생하셨어요

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/repository/sample/SampleStampCoordinateRepository.java
> +    List<SampleStampCoordinate> findSampleStampCoordinateBySampleBackImageId(Long sampleBackImageId);
`SampleStampCoordinate`에는 SampleBackImage객체가 있어서 `find...BySampleBackImageId`보단 `find...BySampleBackImage`가 조금 더 객체지향스러운 네이밍 같아요!

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +@RequiredArgsConstructor
사소한거긴한데, 제 기억으로 @Service, @Controller, @Entity같이 해당 클래스 역할 어노테이션은 클래스 선언부 바로 위에 작성하기로 했던 것 같아요!

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +    public SampleCouponsDto findSampleCouponsBy(Integer maxStampCount) {
parameter타입에 null이 올 일이 없을 것 같은데 int는 어떠신지요..?

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +                .collect(Collectors.toList());
저도 아직 안써봤는데 써볼게유

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +        if (maxStampCount == null) {
혹시 maxStampCount가 null일 때는 8,10,12모든 이미지 뒷면을 주는걸까요??

저는 예외처리 하는게 조금 더 자연스럽다고 생각합니다! 만약 예외처리를 하기로 한다면 해당 로직은 requestDto의 @NotNull과 @Validation을 통해 null이 내부 레이어까지 안들어오게 좋아보여요ㅎ

2023-07-16 13:20 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +        };
역시 람다와 스트림 테코톡 발표자답게 자유자재로 사용하시는군요😎

2023-07-16 13:55 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/response/SampleCouponQueryResponse.java
> +                ))
오..! 그렇게 하면 코드가 좀 깔끔해질 것 같네요 ㅎㅎ 
좋은 의견 감사 내일 다른사람들 의견도 좀 물어보고, 바꿔보도록 하겠3

2023-07-16 13:56 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/sample/SampleStampCoordinateRepository.java
> +    List<SampleStampCoordinate> findSampleStampCoordinateBySampleBackImageId(Long sampleBackImageId);
오케이접수
하지만 네이밍뿐만 아니라 로직도 좀 바뀌어야겠군

2023-07-16 13:57 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/repository/sample/SampleStampCoordinateRepository.java
> +    List<SampleStampCoordinate> findSampleStampCoordinateBySampleBackImageId(Long sampleBackImageId);
JPA 정신을 잘 모르겠는데,
조회하기에는 테이블로는 `sample_back_image_id`를 갖고있을테니깐 
이게 더 낫지 않을까????
한번 sql문 어떻게 나가는지 봐볼게

2023-07-16 14:09 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +    public SampleCouponsDto findSampleCouponsBy(Integer maxStampCount) {
```http
GET http://localhost:8080/coupon-samples
GET http://localhost:8080/coupon-samples?maxStampCount=8
```

위의 경우처럼 쿼리파라미터 없이 호출하면 전체 호출로 만들어서, 
null이 올 일이 있을 것 같습니다! 

null에 대한 검사를 컨트롤러에서 하고 넘기는 게 더 좋다고 생각한다는 뜻입니까?

2023-07-16 14:11 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +        if (maxStampCount == null) {
> 혹시 maxStampCount가 null일 때는 8,10,12모든 이미지 뒷면을 주는걸까요??

정답! 맞슴다

> 저는 예외처리 하는게 조금 더 자연스럽다고 생각합니다! 만약 예외처리를 하기로 한다면 해당 로직은 requestDto의 https://github.com/NotNull과 @Validation을 통해 null이 내부 레이어까지 안들어오게 좋아보여요ㅎ

근데 request가 null이 아닐 필요가 있을까요?
일반적인 조회 로직인 GET /coupon-samples로 조회하면 전체가 나올 수도 있는거라고 생각해서....
그러면 그걸 컨트롤러에서 분기하고, 다른 서비스 로직을 호출하는게 좋다고 생각하는거야??

2023-07-16 14:13 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +                .collect(Collectors.toList());
썼다 안썼다 했는데
그냥 쓸까유??
나중에 다운그레이드할일은 없겟지??

2023-07-16 14:15 UTC, eunkeeee reviewed
@jundonghyuk 

하디씨에게...

2023-07-16 14:15 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +        };
@jundonghyuk 

하디씨 제가 이거를 진짜 오랫동안 헤맸는데,

양방향 연관관계에서 `mappedBy`를 사용한 쪽은 읽기전용이라 DB에서 데이터를 퍼왔을 때, 채워지지 않고 기본값인 `new ArrayList()`로 채워집니다.

이 부분에서 그래서 언제나 사이즈가 0이 나와서 제가 약 2시간을 헤맸었슴다.....

그래서 이부분을 그렇게 로직으로 수정하고싶으나, 못했슴니다
(이전 커밋에 하디의 로직대로 했었음)

혹시 그렇게 구현할 수 있는 방법이 있다면 알랴주세요 ><

2023-07-16 15:17 UTC, yenawee requested changes

2023-07-16 15:17 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/controller/SampleCouponController.java
> +    public SampleCouponQueryResponse findSampleCoupons(
쿼리 파라미터 

@RequestParam(value = "max-stamp-count") Long maxStampCount 

이렇게 받으면 안되나용 ?

2023-07-16 15:17 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/controller/request/SampleCouponQueryRequest.java
> +    public SampleCouponQueryRequest(Integer maxStampCount) {
@AllArgsConstructor 어때용 ?

2023-07-16 15:17 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/sample/SampleBackImage.java
> +    protected SampleBackImage() {
@NoArgsConstructor(access = PROTECTED) 어때여 ?

2023-07-16 15:17 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/initializer/SampleDataInitializer.java
> +public class SampleDataInitializer implements ApplicationRunner {
DataInitializer 👏👏
뭔가 테스트 격리할때도 DatabaseInitializer 이런거 구현해서 쓰던데.... JPA 사용하는 코드에서 많이 사용하는 방식인거같아요 공부중

2023-07-16 15:17 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +    public SampleCouponsDto findSampleCouponsBy(Integer maxStampCount) {
null 검사는 쿼리파라미터 validation 할때 하는게 좋을거같아요!! 
@RequestParams 도 @Valid 를 통해서 유효성 체크를 할수있어요!

2023-07-16 23:40 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/SampleCouponService.java
> +                .collect(Collectors.toList());
이런건 통일까지는 안해도될것같아서 ㅋㅋㅋ 취향차이인거같아요

2023-07-17 05:50 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/SampleCouponController.java
> +    public SampleCouponQueryResponse findSampleCoupons(
그렇게하니깐 max-stamp-count 자체가 필수값이 되어버려서 ... 좀더 봐야겠네요...! ㅠㅠ

2023-07-17 07:47 UTC, youngh0 approved these changes

2023-07-17 07:47 UTC, yenawee approved these changes

2023-07-17 07:48 UTC, jundonghyuk approved these changes

2023-07-17 07:48 UTC, merged

2023-07-18 00:45 UTC, eunkeeee commented
리뷰 다 확인했고, 반영할 수 있는 부분 반영했습니다! 
`max-stamp-count` 쿼리 파라미터 관련해서는 새로운 이슈 올려 놓을게요!