[FE] refactor: 내고객목록 페이지의 로딩/에러를 세분화 핸들링한다.
woowacourse-teams/2023-stamp-crush pull request #881
Opened 2023-10-19 09:15 UTC by kangyeongmin

## 주요 변경사항

1. 로딩처리가 페이지 단에 전체로 되어 있어서 고객 목록 단에서만 로딩 스켈레톤이 띄어지게 구현했습니다.
2. 탭을 이동할때마다 데이터를 새롭게 fetch 해와서, 데이터가 캐싱되기 전까지 탭을 이동할때마다 깜빡임이 존재했습니다. 깜빡임이 사라지더라고 네트워크탭에서 계속 똑같은 요청을 하고 있었습니다. 따라서 초반 페이지에 접속하였을때, `useQueries`로 요청들을 한 번에 불러와 캐싱된 데이터를 사용하고 더이상의 요청은 가지 않게 구현했습니다. 

## 리뷰어에게...

## 관련 이슈

closes #873

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-24 06:33 UTC, 2yunseong requested changes
라잇 고생하셨습니다~! 이번 스프린트 화이팅 해봐요

2023-10-24 06:33 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/components/Customers/index.tsx
> +          <Button variant="secondary">새로 고침</Button>
아직 구현되지 않은 기능인가요??

2023-10-24 06:33 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/index.tsx
> +  const { isError } = useGetCustomers(cafeId, orderOption as CustomerOrderOption);
Customers에서 fetch를 해도 상관없지 않을까요?? Customers에서 Error를 Props로 받아서 처리하는 걸로 알고 있는데, 조금 어색한 느낌이 있어서요.

2023-10-24 06:33 UTC, 2yunseong commented on frontend/src/types/utils/index.ts
> +export type Status = 'loading' | 'error' | 'success';
react query의 status를 위한 타입인가요? 기존에 있는 `QueryStatus`를 사용하는 걸 추천합니다!

2023-10-24 06:33 UTC, 2yunseong commented on frontend/src/pages/Intro/index.tsx
다른이슈의 커밋이 함께 들어왔습니다!

2023-10-25 05:13 UTC, kangyeongmin commented on frontend/src/pages/Intro/index.tsx
아하 ;;;여기잇엇군요 ㅜㅜ

2023-10-26 10:33 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomerList/components/Customers/index.tsx
> +          <Button variant="secondary">새로 고침</Button>
헉 🤭 그르네요

2023-10-26 11:03 UTC, kangyeongmin commented on frontend/src/pages/Admin/CustomerList/index.tsx
> +  const { isError } = useGetCustomers(cafeId, orderOption as CustomerOrderOption);
와우! 정렬과 탭(회원/정렬)의 상태가 page단에 얽혀있어서 분리가 어려울 거라 생각했었는데, 지금 다시 보니 리팩토링이 가능한 구조였어요. 
항상 좋은 리뷰 감사해요 윤생

2023-10-27 00:46 UTC, 2yunseong commented on frontend/src/pages/Admin/CustomerList/hooks/useGetCustomers.ts
> +    console.log(query);
console.log 지워주세욥!

2023-10-27 00:46 UTC, 2yunseong approved these changes
마지막 console.log 만 한번 확인해주세요!! 고생많으셨습니다 :)

2023-10-27 01:38 UTC, merged