[FE] feat: 전화번호 입력 페이지의 로딩/에러 핸들링을 개선한다.
woowacourse-teams/2023-stamp-crush pull request #885
Opened 2023-10-24 04:57 UTC by kangyeongmin

## 주요 변경사항

- 전화번호 입력페이지에서 사용하는 api는 2가지 입니다.
1. 전화번호로 고객 조회(GET)
2. 첫 적립일 경우 임시로 가입시킴(POST)

### 1번에서 status=='error'일 경우

![스크린샷 2023-10-24 오후 1 55 19](https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/673a5896-b277-4f9b-bc2b-78127e120042)

### 2번에서 status=='loading'일 경우
![스크린샷 2023-10-24 오후 1 56 09](https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/6e5ce44d-17ea-4025-86ce-3e160c2404b9)

### 1번에서 status=='error'일 경우
![스크린샷 2023-10-24 오후 1 57 11](https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/b0d79d38-cd92-4a50-a4ad-7e99c619bc40)

## 리뷰어에게...

## 관련 이슈

closes #884 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-24 08:40 UTC, 2yunseong requested changes
고생하셨습니다~! 코드스타일 부분에서 다른점이있어서 RC 요청드려요. 같이 이야기 해보면 좋을 것 같습니다!

2023-10-24 08:40 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/index.tsx
> +          )}
isOpen을 삼항연산자 밖으로 빼면 좋을 것 같은데, 어떻게 생각하시나요??

2023-10-24 08:40 UTC, 2yunseong commented on frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/index.tsx
> +      </>
Fragment가 필요한 이유가 있나요/?

2023-10-26 08:33 UTC, kangyeongmin commented on frontend/src/pages/Admin/EnterPhoneNumber/components/GuideAlert/index.tsx
> +      </>
발견해주셔서 감사합니다!! 쵝오!!

2023-10-27 00:48 UTC, 2yunseong approved these changes
고생하셨습니다 !!

2023-10-27 01:32 UTC, merged