[FE] refactor: 리워드 적립 페이지의 로딩/에러 핸들링을 개선한다.
woowacourse-teams/2023-stamp-crush pull request #888
Opened 2023-10-24 05:34 UTC by 2yunseong

## 주요 변경사항

## 404에러를 해결하였습니다.
현재 카페에 적립을 하지 않은 고객의 경우 404로 에러를 발생해, 해당 에러를 이 페이지 내에서 처리 하였습니다.

이 페이지에서 처리한 이유는 해당 에러를 `api/admin/customers/3/rewards?cafe-id=13&used=false`에서 내뱉기 때문에,
EnterPhoneNumber 에서 처리하기 불가능하다고 판단해 처리했습니다..!

사용자에게는 제안사항으로 뒤로가기 버튼을 제공해, 리워드 사용의 enter-phone-number로 이동할 수 있는 버튼을 제공합니다.

그래도 빠른 적립을 위해 몇 가지를 고안해보았습니다.

### background refetch를 없앴습니다.

사장님의 적립 플로우 상 background refetch가 얼마나 일어날까? 하는 생각이 있었습니다.

따라서 background refetch를 삭제했습니다.

### retry를 false처리했습니다. 
기존의 경우 에러가 발생하는 경우 4번정도 시도를 해보고 안되면 에러 페이지를 표시합니다.

그 동안 사용자는 로딩 인디케이터를 보고 있는데 사장님 같은 경우는 빠른 적립 플로우가 필요하므로 안될경우 4번정도 다시 요청을 시도할 것 없이 즉각적으로 에러를 보여주고, 그에 대한 해결책을 빠르게 제공하는게 중요하다고 생각했습니다.

따라서 retry를 없애는 대신 에러에 대해 어떻게 동작할지 제안해주는 화면을 고안해보았습니다.

아래는 404에러 발생시 사용자에게 뒤로가는 동작을 제안하는 화면입니다. 이외의 다른 서버오류는 refetch할 수 있는 동작을 제공합니다.

캡처는 해당 부분만 보이도록 화면 전체 사이즈에 안맞게 캡처한 점 양해 부탁드립니다
|404 에러 화면 | 기타 에러 화면|
|--|--|
|<img alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/6260f9b5-279c-4c5d-9187-d75c3b50ec01">|<img alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/9b83e48a-666e-4e97-a077-564a1f584b92">|

### 로딩 화면
컴포넌트를 분리해 전체화면이 아닌 데이터 fetch하는 부분만 해당 컴포넌트로 대체하게 만들었습니다.
<img width="789" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/842c2b44-a5be-437b-9409-25201ac6b4f6">

## 리뷰어에게...

## 관련 이슈

closes #878 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-10-26 07:57 UTC, kangyeongmin requested changes
윤생 수고하셨슴미다~

리뷰 화긴 후에 재요청 주세요!!

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +    navigate(-1);
오와 이렇게도 쓸수 잇군요?!

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +  // TODO: 내카페의 고객이 아닌 고객의 리워드를 조회할 경우 ErrorMessage를 띄어줌
isNotFoundUser 함수의 사용처를 봤는데, TODO에 적힌 사항의 로직에 해당하는 것 같은데 맞나요?? 
맞다면 삭제되어야할 것 같아요~

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +        <div>고객 정보 불러오는 중...</div>
문구 대신 <LoadingSpinner/> 를 사용해보면 어떨까요? 훨씬 더 직관적일것 같아서요~

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +      {reward.data.rewards.map(({ id, name }: Reward) => (
data는 useQuery에서 select옵션으로 뽑아서 써주는 것이 어떨까요?

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +const RewardItemList = ({ cafeId, customerId }: RewardItemListProps) => {
한 줄 띄면 더 좋을 것 같아요~

2023-10-26 07:57 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/index.tsx
> +  const location = useLocation() as RewardPageState;
interface로 state의 type을 좁혀주더라도, `as`를 써주게 되면 'CustomerPhoneNumber'가 아닌 state가 전달되어도 html의 사용처(location.state.id)에 도달할 때까지 아무런 오류를 뱉어내지 못할것 같습니다.

타입단언보다 타입가드를 활용해보면 어떨까요?

2023-10-27 00:50 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +    navigate(-1);
네! 기존 JS History API에서 go랑 사용하는 느낌이 비슷하더라고요!

2023-10-27 00:58 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +  // TODO: 내카페의 고객이 아닌 고객의 리워드를 조회할 경우 ErrorMessage를 띄어줌
오 맞습니다~! 체크 감사합니다 :)

2023-10-27 00:58 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +  // TODO: 내카페의 고객이 아닌 고객의 리워드를 조회할 경우 ErrorMessage를 띄어줌
어 맞습니다~! 감사합니다!

2023-10-27 01:35 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +        <div>고객 정보 불러오는 중...</div>
훨씬 이쁘네요~~ :)

2023-10-27 01:40 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/components/RewardItemList/index.tsx
> +      {reward.data.rewards.map(({ id, name }: Reward) => (
불필요한 프로퍼티 나열을 해주지 않아서 좋은 것 같아요! 필요한 내용만 뽑아쓸수도 있었고요! 감사합니다:)

2023-10-27 02:08 UTC, 2yunseong commented on frontend/src/pages/Admin/RewardPage/index.tsx
> +  const location = useLocation() as RewardPageState;
타입단언을 통해 선언하더라도 `state`에 지정한 타입이 아니면 타입에러를 발생시킵니다.
예를들어 위의 `CustomerPhoneNumber` 타입은 `id`, `nickname`, `phoneNumber` 속성을 가지는데요, 해당 속성외의 속성을 사용하려 접근하면 타입 에러를 일으킵니다.

타입가드도 좋은 방법이라고 생각하는데요, 해당 코드에서는 `location.state`의 타입을 개발자가 인지만 하면 된다고 판단하였습니다.

설령 타입가드를 사용하더라도 넘겨주는 곳은 `any`이므로 안전성 측면에서 둘다 비슷비슷하다 생각이 들어 코드가 좀 더 간결하고 직관적인 타입 단언 쪽을 채택했습니다..!

2023-10-27 02:29 UTC, kangyeongmin commented on frontend/src/pages/Admin/RewardPage/index.tsx
> +  const location = useLocation() as RewardPageState;
> 1. 해당 코드에서는 location.state의 타입을 개발자가 인지
> 2. 사용하더라도 넘겨주는 곳은 any이므로 안전성 측면에서 둘다 비슷비슷

그런 관점에서도 볼 수 있겠군요.
윤생이 의도하신 부분 이해했습니다 😊

2023-10-27 02:29 UTC, kangyeongmin approved these changes
윤생~ 리뷰에 대해 적극적으로 소통해주셔서 감사합니다.

수고하셨어요!!!

2023-10-27 04:03 UTC, merged