[BE] feat: 전화번호로 고객을 조회한다
woowacourse-teams/2023-stamp-crush pull request #90
Opened 2023-07-16 01:08 UTC by yenawee

## 주요 변경사항

- 전화번호로 고객을 조회하는 API 를 작성했습니다

```javascript
{
	"customer": [
		{
			"id": 1,
			"nickname": "윤생1234",
			"phoneNumber": "01023456778"
		}
	]
}
```

가 명세였으나 

```javascript
[
       {
		"id": 1,
		"nickname": "윤생1234",
		"phoneNumber": "01023456778"
	}
]
```

형식으로 반환하게 구현했습니다 (key 값을 customer 라고 이름을 붙여주려면 Response 의 필드에 List<CustomerResponse> 가 들어가는 Response 를 하나 더 구현해야 해서 불필요하다고 느껴졌습니다)

## 리뷰어에게...

- 코드를 작성하다보니 전화번호에 맞는 Customer 가 있으면 해당 Customer만 보내주고 없으면 인증이 안되었다고 봐도 될 것 같아CustomerNotFoundException 인 에러를 던지는 편이 낫지 않을지 의견을 제시합니다
(현재 주석처리 해둔 코드의 반환타입을 CustomerResponse 로 하고, Customer 를 못찾았을때 해당 커스텀 예외를 던지는 방향)
- Header의 Authorization 부분에 Owner 의 인증 정보가 들어오고 Owner 가 아니면 고객 조회를 못하는 것을 추가로 구현해야 합니다
- 인수 테스트 작성 시 테스트 격리가 어려워서 우선 deleteAll() 메서드를 사용했습니다

## 관련 이슈

closes #79 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 07:56 UTC, eunkeeee commented
7명이 정한 API라서 구현할 때는 우선 따르는 것도 좋을 것 같아요!

2023-07-16 08:01 UTC, eunkeeee requested changes

2023-07-16 08:01 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/CustomerController.java
> +@RestController
```suggestion
@RequiredArgsConstructor
@RestController
```

2023-07-16 08:01 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/CustomerController.java
> +@RestController
이 어노테이션 클래스 단에 붙이면 아래 생성자 삭제할 수 있어요!

2023-07-16 08:03 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +//    }
이거 저번에 엄청 오랫동안 말이 나왔던건데 이렇게 하기로 결정 났었슴다
나도 첨에는 에러 파였는데

1. API 관점에서 봤을 때 조회를 하는 것 뿐이라 고객이 존재하지 않는 것을 에러 상황이라고 볼지가 애매함
2. 빈 리스트를 받았을 때 어떻게 처리할지에 대해서는 프론트엔드 단에서 customer가 존재하지 않으면, 신규 임시 고객 생성하기로 했었음.

2023-07-16 13:11 UTC, jundonghyuk requested changes
안녕하세요 제나 ! 리뷰어 하디입니다 !

제가 리뷰어라고 칭하니까 왜인지 어색하네요.

코드 잘 봤습니다 !

군데군데 남겨놨으니 확인 부탁드려요 ㅎ_ㅎ

2023-07-16 13:11 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +            return customers.stream().map(CustomerResponse::from).collect(Collectors.toList());
이 부분이 잘 이해가 안가는데요 ! `findByphoneNumber`를 해서 예외가 터지는 상황이 존재하나요 ? (진짜몰라서 여쭤보는 겁니다!)

2023-07-16 13:11 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
혹시 이게 어떤 뜻일까요 ?
뒤 4자리 번호만 저장하겠다는 뜻일까요 ?

저희가 전화번호를 입력해 쿠폰적립을 하려면 11자리의 전화번호를 모두 저장해야한다고 생각하는데요 !
어떤 뜻이 담겨져있을까요 ?

2023-07-16 13:11 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +        assertThat(customers).containsExactly(CustomerResponse.from(customer));
위의 검증이 실패하면 밑에것은 실행이 안될 것 같은데요 !
어떤방법이 있을까용?

2023-07-16 13:11 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
저는 회원을 생성하기 전에 이 전화번호를 가진 회원이 이미 있는지 확인할 것 같아요 !
저희는 같은 전화번호로 여러 회원을 생성하면 안되기 때문에, 중요하다고 생각하는데요 !

저희의 어플리케이션은 그 누구도 믿으면 안된다고 생각합니다 !
실수로 앞에서 이미 회원이 있는데 회원가입을 시키는 잘못된 요청을 보낼수도있고요 !

그래서 회원을 한번 조회해보고 있으면 예외를 던지고, 없으면 그제서야 가입을 시킬 것 같아요 !

2023-07-16 13:33 UTC, youngh0 approved these changes
안녕하세요 제나!
깔쌈한 코드 멋있네요. 이미 다른 분들이 피드백 해주셔서 저는 어프루브 해도 될 것 같네요.. 
고생하셨습니다 ㅎㅎ

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/user/Customer.java
> +@NoArgsConstructor(access = PROTECTED)
오 이거 좋네요..! 👍

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
> +    //    Optional<Customer> findByPhoneNumber(String phoneNumber);
혹시 PR에 명시해주신 주석이 이 부분일까요??

현재 명세는 없으면 빈 리스트 반환이라 우선은 빈 리스트를 반환하고 추후 회의해서 결정났을 때 바꿔도 늦지 않을 것 같습니다!!

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/CustomerResponse.java
> +@EqualsAndHashCode
equals도 어노테이션으로 지원해주는군요.. 어노테이션 장인이시네요 ㅎㅎ

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/CustomerResponse.java
> +        return new CustomerResponse(customer.getId(), customer.getNickname(), customer.getPhoneNumber());
정팩메 좋네여~

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +            return customers.stream().map(CustomerResponse::from).collect(Collectors.toList());
제가 알기론 조회 결과가 없으면 빈 리스트가 반환됩니다!

그래서 try...catch는 제거해도 문제 없을듯 합니다!!

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
nickname이라 뒤 4자리로 하신 것 같아요!

2023-07-16 13:33 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
오 저도 동의합니다!

2023-07-16 13:33 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +//        Customer customer2 = new RegisterCustomer("제나2", "01012345678", "jena2", "12234");
사용하지 않는 주석 제거해주시면 감사하겠습니다! 🙇‍♂️

2023-07-16 23:39 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
아하 닉네임으로 받는군요 죄송......ㅋㅋ

2023-07-17 05:23 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/controller/CustomerController.java
> +        return ResponseEntity.ok().body(customers);
저희 기존 API 가 배열이 value 가 되는 형식이었는데 굳이 다시 배열을 객체로 감싸야 하나 ? 라는 생각이 들어서 그냥 배열을 반환하게 구현했었습니다! 

정한 API 명세에 맞게 반환해야 하기도 하고 customer 배열 외에 추가 필드가 추가되어서 반환되어야 할때를 대비해서 확장성이 좋게 key:value 로 반환해주는 것이 좋을 거 같습니다 !!

2023-07-17 05:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +            return customers.stream().map(CustomerResponse::from).collect(Collectors.toList());
그러네요... 빈 리스트가 반환되네요.. try catch 제거했습니다 !

2023-07-17 05:35 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +        assertThat(customers).containsExactly(CustomerResponse.from(customer));
assertSoftly 로 바꿧습니다 !

2023-07-17 05:43 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/repository/user/CustomerRepository.java
> +    //    Optional<Customer> findByPhoneNumber(String phoneNumber);
List 로 받는게 현재 API 명세를 구현하는데 더 수월해서 우선 List\<Customer\> 로 받는 코드만 남겨뒀습니다 !

2023-07-17 06:12 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
회원 조회 시 있으면 예외처리 추가했습니다 ~!

2023-07-17 06:20 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +//    }
이거는 API 명세 정할때도 많은 논의가 있었는데 제가 코드를 짜다보니 미심쩍은 부분이 있었어서 좀 헷갈렸던 부분이 있는거같아요
(CustomerRepository 의 findByPhoneNumber 가 최대 1개의 고객을 반환할텐데 그럼 Optional\<Customer\> 가 반환값이 되어야하지 않나 ? 라는)

그리고 데이터베이스에서 조회를 못해왔을때 에러가 발생해서 캐치해줘야 하는줄 알았어요 ㅎㅎ....

사실 빈 배열로 반환해도, 에러를 던져줘도 프론트에서 캐치하고 임시 고객 생성 API 를 던져줘야 하는 흐름은 동일하니 빈배열을 반환하는 API 명세대로 구현했습니다 !! ( 그때도 많은 논의를 하고 결정한거니까!! )

2023-07-17 06:21 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerResponse.java
> +@EqualsAndHashCode
이거 검색해봤는데 확실하게 나오는게 없어서.... 더 찾아봐야할거같습니다..
확실히 아무 생각없이 어노테이션을 사용하면 안되는 게 이런 부분에서 드러나네요 🥲

2023-07-17 07:10 UTC, eunkeeee requested changes

2023-07-17 07:10 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/CustomerController.java
> +    public ResponseEntity<CustomersResponse> findCustomer(@RequestParam("phone-number") String phoneNumber) {
이 API 테스트해보고 싶은데, 더미 데이터 하나만 넣어주시면 좋을 것 같아요 

![스크린샷 2023-07-17 오후 4 04 17](https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/7474e19a-a3ee-4e53-b78d-651a745c1a86)

2023-07-17 07:10 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        List<Customer> customers = customerRepository.findByphoneNumber(phoneNumber);
리스트 사이즈가 0일 때 예외 로직 필요할 것 같아요
그대로 jpa 에러 404로 나가고 있어요. 한번 커스텀으로 감싸면 좋을 것 같습니다

2023-07-17 07:10 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        if (!customerRepository.findByphoneNumber(phoneNumber).isEmpty()) {
이부분 메서드로 분리해도 좋을 것 같아요!

2023-07-17 07:10 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
무슨 로직인지 알기 좀 어려워서, 

4는 상수로 이름 줘서 분리하고,
nickname 만드는 메서드도 적절히 분리하면 좋을 것 같습당

2023-07-17 07:12 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +        assertSoftly(softAssertions -> {
assertSoftly는 뭔가요???

2023-07-17 07:48 UTC, eunkeeee approved these changes

2023-07-17 07:49 UTC, jundonghyuk approved these changes

2023-07-17 07:50 UTC, youngh0 approved these changes

2023-07-17 07:55 UTC, merged

2023-07-17 12:40 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/acceptance/CustomerIntegrationTest.java
> +        assertSoftly(softAssertions -> {
여러 assert 구문 있을 때 하나 실패해도 다른 assert 구문들 실행하게 하게 해주는 아이입니다 ~

2023-07-17 12:40 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/service/CustomerService.java
> +        String nickname = phoneNumber.substring(phoneNumber.length() - 4);
상수 분리는 했는데 nickname 메서드 한줄인데 따로 분리해야 할까욥 ㅠㅠ