[FE] feat: 쿠폰 리스트 ui 변경
woowacourse-teams/2023-stamp-crush pull request #906
Opened 2023-10-27 08:07 UTC by kangyeongmin

## 주요 변경사항

### 쿠폰 펼치기 

https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/5b9764ff-4542-4322-b70b-a72edcc9238e

### 즐겨찾기 모으기
https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/129e962b-25b8-4920-87b0-46b790022b36

### 즐겨찾기 토글 기능
- 즐겨찾기 토글 기능을 낙관적 업데이트를 하고 있었습니다. 그런데, 즐겨찾기 토글 상태와 관련하여 싱크가 안맞아 1초 깜빡임이 생기는 현상이 생겨 낙관적 업데이트를 안하고 요청이 가고 기다렸다가 새로 데이터를 get해오는 방식으로 변경되었습니다. 

## 리뷰어에게...

## 관련 이슈

closes #886

## 체크리스트

- [ ] `reviewers` 설정
- [ ] `label` 설정
- [ ] `milestone` 설정

2023-10-27 08:30 UTC, yenawee commented
라잇라잇
카페 이름이랑 스탬프개수정보는 이제 메인페이지에서 안보이는거에여?? 🥲
보이면 좋겟는디 ....

(스탬프크러쉬 1기의 제안)

2023-10-27 08:42 UTC, kangyeongmin commented
> 라잇라잇 카페 이름이랑 스탬프개수정보는 이제 메인페이지에서 안보이는거에여?? 🥲 보이면 좋겟는디 ....
> 
> (스탬프크러쉬 1기의 제안)

보일 수가 엄서요 ㅜ

여러개의 쿠폰을 넘나들기 위해서 바뀐 ui인데,
여러개의 쿠폰이 있을때는 하나의 쿠폰을 특정하기가 어렵더라구요..

@yenawee 카페의 정보를 메인에서 어떻게 보여줄지에 대한 아이디어가 있으시면 알려주세요!!

2023-10-27 08:52 UTC, yenawee commented
> > 라잇라잇 카페 이름이랑 스탬프개수정보는 이제 메인페이지에서 안보이는거에여?? 🥲 보이면 좋겟는디 ....
> 
> > 
> 
> > (스탬프크러쉬 1기의 제안)
> 
> 
> 
> 보일 수가 엄서요 ㅜ
> 
> 
> 
> 여러개의 쿠폰을 넘나들기 위해서 바뀐 ui인데,
> 
> 여러개의 쿠폰이 있을때는 하나의 쿠폰을 특정하기가 어렵더라구요..
> 
> 
> 
> @yenawee 카페의 정보를 메인에서 어떻게 보여줄지에 대한 아이디어가 있으시면 알려주세요!!

글쿤요 
하지만 바뀐 ui 도 이뻐용
즐겨찾기 모아보기가 되니까 확실히 즐겨찾기의 쓸모가 있어졌네요 ㅎㅎ

근데 상세정보 페이지에 (현재 스탬프 개수) / (맥스 스탬프 개수) 이 정보가 추가됏으면 좋겟어요 메인에서 못보니까!!

그리고 스탬프 적립 개수가 일정 퍼센트 이상이 되면 느낌표같은거 띄워줘도 조을거같네용 (옛날에 얘기 다 나왓던거긴하죠🤣🤣)

2023-10-28 12:27 UTC, 2yunseong requested changes
라잇 고생하셨습니다~!

개인적으로는 낙관적업데이트를 살리고 싶어서 왜 지연이 될까 고민을 해보았어요
코드 남겨 두었으니 한번 확인 해주시기 바랍니다!

2023-10-28 12:27 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/hooks/usePostIsFavorites.ts
> +const usePostIsFavorites = (closeModal: () => void) => {
만약 낙관적 업데이트를 살리고 싶다면,, 고려사항을 늘려보면 어떨까요?
저번에는 잘 몰라서 리뷰에서 놓쳤는데 지금 setQueryData가 return 하는 값이 undefined라 무언가 이슈가 있는 것 같아요. 공식문서를 참고해 코드를 작성해보았는데, 한번 체크 부탁드려요!

```ts
const usePostIsFavorites = (closeModal: () => void, currentIndex: number) => {
  const queryClient = useQueryClient();

  return useMutation(postIsFavorites, {
    onSuccess: () => {
      // closeModal()은 이제 성공/실패 여부와 상관없이 Mutate 이후에 모달을 닫습니다.
      // closeModal();
    },
    onMutate: async () => {
      // refetch를 막습니다.
      await queryClient.cancelQueries({ queryKey: ['coupons'] });
      // 기존의 query를 스냅샷 합니다.
      const snapshotCouponRes = queryClient.getQueryData<CouponRes>(['coupons']);
      // 존재하지 않는다면, 에러를 발생합니다. 즐겨찾기 시 당연히 coupons query가 존재하므로 아마 도달하지 않는 코드이며 타입가드를 위해 작성합니다.
      if (!snapshotCouponRes) {
        throw new Error('Query가 존재하지 않습니다.');
      }
      queryClient.setQueryData<CouponRes>(['coupons'], (prev) => {
        if (!prev) return snapshotCouponRes;
        // 선택된 쿠폰의 favorite를 변경합니다. 다만, 불변성을 지키지 않아 조금 위험하긴 합니다..
        // setState와 사용법이 비슷합니다.
        prev.coupons[currentIndex].cafeInfo.isFavorites =
          !prev.coupons[currentIndex].cafeInfo.isFavorites;
        // 반환한 값으로 QueryData를 세팅합니다.
        return prev;
      });
      // 여기서 반환한 값은 낙관적 업데이트가 실패했을 때 되돌리는 용도로 사용됩니다.
      return { snapshotCouponRes };
    },
    onError: (err, res, context) => {
      // 에러발생 시, (post 실패시) 값을 이전 값으로 되돌립니다.
      queryClient.setQueryData(['coupons'], context?.snapshotCouponRes);
    },
    onSettled: () => {
      // 에러 상황이든 성공이든, 새로운 값을 fetch해 업데이트 합니다.
      queryClient.invalidateQueries({ queryKey: ['coupons'] });
    },
  });
};
```

2023-10-28 12:27 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/hooks/usePostIsFavorites.ts
> +const usePostIsFavorites = (closeModal: () => void) => {
이럴 경우 플로우는 다음과 같이 예상됩니다.

1. 사용자가 favorite 요청을 누른다. (즐겨찾기 버튼)
2. 어찌 되었든(성공/실패) 지금 가지고 있는 favorites와 반대되는 값으로 queryData를 변경한다.
3. 그리고 모달은 mutate호출 이후에 바로 닫는다.
4-1. POST 실패시, 이전에 snapshot으로 저장해둔 값을 context를 통해 불러, 이전 값으로 되돌린다.
4-2. POST 성공 시, 아무동작도 하지않는다.
5. 이후 `onSettled` (쿼리요청 성공/실패 이후 호출하는 함수) 에서 새로운 값을 fetch해 실제 서버 상태와 연동시킨다.

### 참고 문서
[useMutation](https://tanstack.com/query/v4/docs/react/reference/useMutation)
[Optimisic Update](https://tanstack.com/query/v4/docs/react/guides/optimistic-updates)

2023-10-28 12:27 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/index.tsx
> +    console.log('coupons: ', coupons);
console!

2023-10-29 06:05 UTC, kangyeongmin commented on frontend/src/pages/Customer/CouponList/hooks/usePostIsFavorites.ts
> +const usePostIsFavorites = (closeModal: () => void) => {
윤생~ 제가 설명을 빈약하게 드린것 같습니다. 
윤생이 보내주신 코드로 확인을 해보았는데, 똑같은 현상이 발생해요.

https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/a1a3d242-4da8-49db-970c-88b8d4c6e8c2

영상 후반부에 보시면 마지막 쿠폰을 즐겨찾기 해제할 때, 깜빡임이 발생합니다.
깜빡임이 발생하는 것은 undefined와 관계없이 현재 로직상의 문제인 것일 수도 있어요 ㅜ

로직: 배열의 index로 target을 찾아감. 배열의 길이가 계속 달라져서 쿠폰마다 index가 계속 달라짐.

```javascript
const useGetCoupons = (isCollected: boolean) => {
  return useQuery({
    queryKey: ['coupons'],
    queryFn: getCoupons,
    select: (data) => {
      if (isCollected)
        return data.coupons.filter((coupon) => coupon.cafeInfo.isFavorites && coupon);
      return data.coupons;
    },
  });
};
```
즐겨찾기 변경 로직은 select로 뽑아낸 data상에서 이루어져야 하는데,
낙관적 업데이트 상에서 getQueryData로 가져온 데이터는 select된거 상관없이 캐싱된 데이터 전체를 다 뽑아오더라구요.

그래서 쿠폰리스트에 존재하는 index 1번상의 쿠폰을 즐겨찾기 해제/등록 하려고 할때,
낙관적업데이트를 적용하면 다른 index 상의 쿠폰을 즐겨찾기 해제/등록시킨뒤 
화면에 보였다가 서버상의 정보와 다르니 화면에서 사라짐으로써 깜빡임이 발생합니다.

낙관적업데이트를 적용해야하는 경우는 
1. 서버상의 응답이 너무 느릴 때, 
2. 사용자의 과도한 서버요청이 예상될 때
라고 생각합니다. 
이전에, 낙관적 업데이트를 적용한 이유는 즐겨찾기 해제/등록 시에 alert를 만들지 않았기 때문인데요.
현재는 alert도 존재하고, 테스트 해봤을 때 서버와의 요청도 즉각적으로 반영되는 것을 확인할 수 있더라구요!

2023-10-29 06:10 UTC, kangyeongmin commented on frontend/src/pages/Customer/CouponList/hooks/usePostIsFavorites.ts
> +const usePostIsFavorites = (closeModal: () => void) => {
따라서, 즐겨찾기 해제/등록 정보를 서버와의 싱크를 맞추며 화면에 보여주는 것이 안전하고, 깜빡임도 발생하지 않기 때문에 낙관적 업데이트를 제거하였던 것이었습니다!!

2023-10-29 06:32 UTC, 2yunseong commented on frontend/src/pages/Customer/CouponList/hooks/usePostIsFavorites.ts
> +const usePostIsFavorites = (closeModal: () => void) => {
이런 이유가 있었군요! 라잇의 말씀대로 낙관적 업데이트를 빼도 되겠다는 생각이 듭니다 ㅎㅎ
고생하셨습니다!

2023-10-29 06:33 UTC, 2yunseong approved these changes

2023-10-29 06:44 UTC, 2yunseong requested changes
다음 동작에서 스크롤이 안먹는 에러가 나타납니다! 확인 부탁드려요.
1. 쿠폰을 4장이상(뷰포트를 넘어가는)가진다.
2. 쿠폰 펼치기 이후 최하단으로 스크롤 한다.
3. 쿠폰 펼치기를 off한다.
<img width="349" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/56749516/2ecee82d-766b-4ca0-82c8-74b3199c2776">

2023-10-30 06:26 UTC, kangyeongmin commented
윤생이 발견해준 버그를 해결했습니다!
쿠폰 펼치기를 off 하면 scroll을 원위치로 되돌리는 로직을 추가했어요.

제나의 의견을 반영하여
쿠폰리스트 메인에서 현재 쿠폰의 적립률을 볼수 있게 progressBar을 추가했습니다.
<img width="312" alt="스크린샷 2023-10-30 오후 3 26 04" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/b410cfae-4298-4d91-97c1-ebd155ed4a3c">
<img width="313" alt="스크린샷 2023-10-30 오후 3 26 16" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/62367797/8d5b5383-2f6f-4640-a8d5-071782f54fa9">

2023-10-30 06:32 UTC, 2yunseong approved these changes
잘 동작하는 것 확인했습니다~! 고생 많으셨습니다!

2023-10-31 08:03 UTC, merged