[BE] feat: 카페의 고객 목록 조회, 현재 스탬프 쌓고 있는 쿠폰 정보 조회 구현
woowacourse-teams/2023-stamp-crush pull request #93
Opened 2023-07-16 07:05 UTC by youngh0

## 주요 변경사항

- Coupon의 stamp개수를 쉽게 조회하기 위해 Stamp와 양방향 연관관계를 설정했습니다.
- 해당 기능이 고객 정보, 쿠폰 정보, 스탬프 정보를 모두 반환하는 기능이라 패키지 구조를 고민해봤습니다.
    - 대부분의 정보를 조회하기 위해선 Coupon을 중심으로 join이 발생했기 때문에 coupon패키지로 정했습니다.
- 기존 엔티티에서 Coupon과 CouponPolicy연관관계가 없어서 이를 추가했습니다.

## 리뷰어에게...

- Coupon이 Customer, CouponPolicy, CouponDesign, Cafe와 연관관계가 있어서 테스트하기 위한 사전 데이터를 추가하는 코드가 상당히 길어졌습니다..
    - 그래서 이 연관관계를 꼭 객체로 해야하는지에 대해서 한 번 얘기해보면 좋을 것 같습니다! id로 풀 수도 있다고 하더라구요. 관련 세미나 영상 링크 걸어놓겠습니다. 영상이 길긴한데 보면 도움이 많이 될 것 같아요 ㅎ
    - [우아한 객체지향 세미나](https://www.youtube.com/watch?v=dJ5C4qRqAgA&t=3956s)
- `현재 스탬프 쌓고 있는 쿠폰 정보 조회 구현`에서 해당 쿠폰이 이전 정책인지 알려주는 `isPrevious`를 구하기 위해 노력해봤는데, 현재 저희 ERD구조에서는 시간이 조금 걸릴 것 같아서 일단 false로 고정했습니다.
    - 해당 부분은 시간이 조금 더 필요할 것 같아요..
- Controller에서 외부로 반환하는 DTO의 경우 제대로 동작하는지 확인해보기 위해선 관련 엔티티에 모든 정보를 다 넣어야하기 때문에 우선 service에서 반환된 DTO를 그대로 반환하게 했습니다.. 이건 모든 코드를 합치고 더미데이터를 넣든가 연관관계를 약하게 풀고 나서 수정하겠습니다..!

closes #72 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 13:58 UTC, jundonghyuk requested changes
안녕하세요 레오 ~ 리뷰어 하디입니다 ..!

코드 전체적으로 잘봤습니다. 약간의 통계느낌이 나는 메서드들을 잘 구현해주신것 봤습니다 ! 대다내요

개별적으로 코멘트 남겼습니다 ~_~

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +        return ResponseEntity.ok(couponService.findCouponsByCafe(cafeId));
서비스 반환값을 바로 응답값으로 주셨군요 !
저도 고민을 많이 했습니다..! 사실 서비스반환타입과 컨트롤러 응답타입을 따로 가져야가야하는지에 대해 불편함을 아직까지 못느껴서 저도 공감을 합니다..

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<List<CustomerUsingCouponResponseDto>> readCustomerUsingCouponByCafe(@PathVariable Long customerId, @RequestParam Long cafeId, @RequestParam boolean active) {
리스트를 객체로 감싸지 않고 바로 반환하면 어떤 문제점이 생길 수 있을까요 ????

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +        Cafe cafe = cafeRepository.findById(cafeId).orElseThrow(() -> new NoSuchElementException("존재하지 않는 카페 입니다."));
`.`은 저는 개행을 하는 편인데 길지만 않다면 이어쓰는 타입이신가요 ???(궁금)
`.` 같은 경우에 어떤기준으로 개행을 하시나요 ?  (Ex 스트림)

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +        Map<Customer, List<Coupon>> couponsByCustomer = getCouponsByCustomer(cafe);
Customer기준으로 그룹화하여 맵을 반환하는것 같은데, `getCouponsByCustomer`라는 네이밍이 저는 뭔가 와닿지 않네용
`mapCouponsByCustomer`와 같은 것은 혹시 어떠신가요 ?

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                visitCount += coupon.calculateVisitCount();
한 쿠폰내에서만 `createdAt`의 중복되지 않은 값으로만 방문횟수를 세고있는데요!
만약 쿠폰이 (8/10)에서 스탬프를 3개찍어 (10/10) + (1/10)이 되었을 때 서로 다른 쿠폰간에도 방문횟수가 중복되는 경우가 있다고 생각하는데 어떻게 생각하시나요 ?

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                firstVisitDate = coupon.compareVisitTime(firstVisitDate);
메서드명으로 기능을 예측하기 쉽지 않겠어요.
주석이 없었으면 해석하기 어려웠을 것 같습니다.

`compareCreatedAtAndReturnBefore`등과 같은 네임은 어떠세요? 쿠폰 내부에서는 `createdAt`으로 비교를 하는데, 사실 그것이 방문일자라는 것은 `Coupon`에서는 몰라도된다고 생각합니다. 저희가 부여한 의미같아여 
어떻게 생각하시나요 ?

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                ))
`Coupon`과 `customerId`를 받아 `of`라는 명칭의 정적팩토리 메서드를 사용하는 것에대해 어떻게 생각하시나요 ?
저는 `Dto`가 도메인을 알고있는 것은 괜찮다고 생각해서요 ! 레오의 의견을 듣고싶습니다.

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerInfoResponseDto.java
> +@Getter
`@ToString`은 롬복을 사용하고, `Equals&hashCode`는 직접 정의해주신 이유가 있을까요 ?

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    private List<Stamp> stamps = new ArrayList<>();
`fetch = EAGER`로 걸어주신 이유가 있을까요 ?

2023-07-16 13:58 UTC, jundonghyuk commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +    }
given, when, then으로 나누어져있으면 보기더 편리할 것 같아요 이 테스트가 아니라 전체적인 얘기입니다 ㅎㅎㅎㅎ

2023-07-16 15:32 UTC, yenawee requested changes
쿠폰 도메인 상당히 어렵네요 ....?

고생하셨습니다 레오....!

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +        return ResponseEntity.ok(couponService.findCouponsByCafe(cafeId));
저도..

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<List<CustomerUsingCouponResponseDto>> readCustomerUsingCouponByCafe(@PathVariable Long customerId, @RequestParam Long cafeId, @RequestParam boolean active) {
저는 조회 메서드 이름에서는 find 나 get 을 선호하는거같아요 ! (바꿔야한다는 말 X)

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerInfoResponseDto.java
> +    public CafeCustomerInfoResponseDto(Long id,
롬복 생성자 어노테이션을 애용합시당 ㅎㅎ

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomersResponseDto.java
> +    private final List<CafeCustomerInfoResponseDto> customers;
객체 선언 후 한줄 띄고 변수 선언해주기 컨벤션 ..!

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CustomerUsingCouponResponseDto.java
> +    @JsonFormat(pattern = "yyyy:MM:dd")
어노테이션 있는 필드는 한칸 띄워주기 컨벤션!!

2023-07-16 15:32 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Stamp.java
> +    public void registerCoupon(Coupon coupon) {
연관관계 메서드 👏

2023-07-16 15:32 UTC, yenawee commented on backend/src/test/java/com/stampcrush/backend/application/coupon/CouponServiceTest.java
> +class CouponServiceTest {
쿠폰 도메인 맡아서 테스트하기 어려웠겠네요 레오.....
고생많았슴니다....🥺

2023-07-17 07:05 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/dto/CafeCustomerInfoResponseDto.java
> +@Getter
존재를 몰랐어요..

2023-07-17 07:18 UTC, eunkeeee requested changes

2023-07-17 07:18 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<CafeCustomersResponseDto> readCustomersByCafe(@PathVariable Long cafeId) {
용어통일하면 좋을 것 같아요
find, read ...

2023-07-17 07:18 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<List<CustomerUsingCouponResponseDto>> readCustomerUsingCouponByCafe(@PathVariable Long customerId, @RequestParam Long cafeId, @RequestParam boolean active) {
제이슨 약속한 모양이 안나올거에요...!

2023-07-17 07:18 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<List<CustomerUsingCouponResponseDto>> readCustomerUsingCouponByCafe(@PathVariable Long customerId, @RequestParam Long cafeId, @RequestParam boolean active) {
저도 find 동의
get은 완전 Getter처럼 로직 없는 경우에만 사용합니당!

2023-07-17 07:18 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/coupon/Coupon.java
> +    private List<Stamp> stamps = new ArrayList<>();
Fetch eager은 안하는게 더 좋을 것 같슴ㅁ니다...! 
Cascade ALL로 하는게 이 경우에 문제가 될 일은 없을까요..?!!

2023-07-17 07:50 UTC, eunkeeee approved these changes

2023-07-17 07:51 UTC, jundonghyuk approved these changes

2023-07-17 07:58 UTC, yenawee approved these changes

2023-07-17 07:59 UTC, merged

2023-07-17 10:03 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/api/CouponController.java
> +    public ResponseEntity<List<CustomerUsingCouponResponseDto>> readCustomerUsingCouponByCafe(@PathVariable Long customerId, @RequestParam Long cafeId, @RequestParam boolean active) {
확장성이 떨어지는데 제가 놓쳤네요 감삼다 ㅎㅎ

2023-07-17 10:07 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +        Cafe cafe = cafeRepository.findById(cafeId).orElseThrow(() -> new NoSuchElementException("존재하지 않는 카페 입니다."));
개행하는데 놓쳤어요. 감사합니다 ㅎㅎ

2023-07-17 10:07 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +        Map<Customer, List<Coupon>> couponsByCustomer = getCouponsByCustomer(cafe);
아주 좋은 네이밍이군요 수정했습니다.

2023-07-17 10:08 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                visitCount += coupon.calculateVisitCount();
이 부분은 같이 논의가 필요해 보이네요.. ERD구조를 변경하거나, stamp적립 로직을 고정시켜야 할 것 같아요

2023-07-17 10:10 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/coupon/CouponService.java
> +                firstVisitDate = coupon.compareVisitTime(firstVisitDate);
너무 좋아요 하디씨

2023-07-18 01:32 UTC, eunkeeee reviewed
코드에 있는 주석을 없애고 메서드 분리 등등으로 좀더 가독성 높이면 좋을 것 같아요!