[BE] feat: 사장님은 쿠폰의 디자인과 정책을 수정할 수 있다.
woowacourse-teams/2023-stamp-crush pull request #94
Opened 2023-07-16 07:46 UTC by eunkeeee

## 주요 변경사항

- 사장님의 쿠폰 디자인, 정책 수정 기능 구현

## 리뷰어에게...

- 아직 테스트 관련해서 제대로 정하지 않아서, 월요일에 함께 테스트 관련 이야기 하고 제대로 동작하는지 제대로 확인 후에 merge하는 편이 좋을 것 같습니다. 
- Request 형태에서 필요한 Request DTO가 너무 많아져서, 많은 부분을 `inner class`로 구현했습니다. 
    - 이 부분 때문에 코드에 클래스 이름 사이 .이 너무 많이 찍히게 되었는데, 너무 혼란스러우면 inner class 모두 해제하는 쪽으로 리팩터링해도 좋을 것 같습니다. 
    - DTO 관련해서도 이 부분 정하면 좋을 것 같아요! 

## 관련 이슈

closes #89 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 14:41 UTC, youngh0 requested changes
안녕하세요 깃짱
리뷰 달았습니다! 코드가 어썸하네요. 

주말동안 고생하셨습니다~~

2023-07-16 15:44 UTC, yenawee requested changes
쿠폰 디자인 정책 수정 너무 어렵네요....! 깃짱 구현하느라 너무 고생많았어요......

전체적으로 
1. 롬복 생성자 
2. Optional 사용시 present() 로 값 확인 후 get() 이 아니라 orElseThrow 사용하기
3. Dto 복잡성

만 체크하면 좋을거같습니다!
Dto 복잡성은 근데 쿠폰 정책에 얽힌 객체들이 많아서.... 어렵네여..

2023-07-16 15:44 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/request-http.http
> +POST localhost:8080/coupon-setting?cafe-id=1
.http 👏

2023-07-17 05:52 UTC, jundonghyuk approved these changes
코드 잘봤습니다 ..!

2023-07-17 05:52 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
> +    public void softDelete() {
저도 제나의 생각에 동의합니다 !

2023-07-17 05:53 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/CouponSettingController.java
> +        couponSettingService.modifyCouponSettings(cafeId, couponSettingDto);
`CouponSetting`이라는 말이 `CouponDesign`, `CouponPolicy`를 모두 포함하는 말입니다!
디자인도 같이 바뀐다고 명시하려면 setting이 더 좋을 것 같아요!

2023-07-17 05:54 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/request/CouponSettingModifyRequest.java
> +    @RequiredArgsConstructor
안붙여도 적용이 됩니까!

2023-07-17 05:55 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/request/CouponSettingModifyRequest.java
> +    @RequiredArgsConstructor
inner class는 안붙이니까 바로 컴파일 에러가 나네요.
내부 메서드랑은 다르게 클래스라서 별도로 붙여야 하는 것 같아요

2023-07-17 05:56 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/controller/request/CouponSettingModifyRequest.java
> +    public CouponSettingDto toCouponSettingDto() {
그쵸 ㅎㅎ 보따리상처럼 주로 컨트롤러에서 다 풀어서 서비스 dto로 넘겨야하니, 한번 dto 내부에서 변환하면 좋을 것 같아요 🚨

2023-07-17 05:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/CafeCouponDesign.java
> +    public void softDelete() {
제나 아니고 영호입니다. @youngh0 가 서운해요

2023-07-17 06:00 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/entity/cafe/CafePolicy.java
> +    public void softDelete() {
ㅇㅋ

2023-07-17 06:01 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/initializer/CouponSettingDataInitializer.java
> +
좋죠~

2023-07-17 06:06 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CouponSettingService.java
> +        softDeletePreviousSettings(cafe);
오호홓 칭찬 감사합니다

2023-07-17 06:07 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/service/CouponSettingService.java
> +                false,
@youngh0 

맞슴다...! IDE로 볼 때는 이해가 가는데 이건 진짜 어렵네요 ㅋㅋ
Deleted.FALSE 이런식으로 enum으로 정하는 것도?

2023-07-17 07:58 UTC, jundonghyuk approved these changes

2023-07-17 07:58 UTC, yenawee approved these changes

2023-07-17 08:00 UTC, youngh0 approved these changes

2023-07-17 08:01 UTC, merged