[BE] feat: 카페 생성 및 조회 기능을 구현한다
woowacourse-teams/2023-stamp-crush pull request #95
Opened 2023-07-16 12:20 UTC by jundonghyuk

## 주요 변경사항
- 카페 등록
- 카페 조회

## 리뷰어에게...
- `Controller` -> `Service`로 넘어갈 때 `ownerId`가 `1L`로 하드코딩되어 넘어가는 경우가 있습니다.
어떻게든 카페 사장에 관련된 정보로 카페를 찾아야 했기에 넣어둔겁니다 ! 아마 인증과정이 있으면 추후 바뀌게 될 것 같습니다.

- 카페 등록을 할 때 샘플이미지, 기본정책을 넣어주는 것을 많이 고민했습니다. 샘플이미지 안에 있는 정보를 복사하여 카페와 연관된 테이블에 `insert`해주었습니다. 현재 저희의 방식이 `저장공간`을 많이 잡아먹는 방법인 것은 인지하고 있습니다. 하지만 이게 직관적이고 구현하기 쉬우며 추후 저희가 리팩토링할 때 고민해볼 수 있는 좋은 포인트라고 생각합니다 ㅎㅎㅎㅎ (예를들어, 이미지 full path를 저렇게 하나의 문자열로 저장하는게 나은가?에 대한 고민같은것이지요!)
- 충돌이 덜 나게끔 다른 분들이 이미 구현하신 부분은 그냥 가져왔습니다 !
- `Service`의 반환타입과 `Controller`의 반환타입을 분리하는 것에 대해 고민을 좀 더 해보겠습니다 !(좋은 글이나 정보있으면 첨부 부탁드립니다 ㅎㅎ)
- `CafeService`에 `createCafe`의 메서드가 길이가 긴것을 볼 수 있는데요...ㅎㅎ
`Dto`를 통해 `Domain`객체를 만들 때 `Domain`이 `Dto`를 의존하면, 쉽게 만들 수 있었지만 더 변경이 자주 일어날 것 같은 `Dto`를 도메인이 의존하는 것은 위험하다고 생각하여 일일이 다 풀어서 넘겼습니다 !
또한, 카페를 등록할 때 다음과 같은 과정이 일어나는데요.
1. 카페를 등록한다
2. 등록한 카페에 기본정책을 등록시킨다.
3. 샘플 앞면, 뒷면(10개인것만), 스탬프 이미지를 들고온다.
4. 등록한 카페에 샘플이미지를 등록시킨다.

등등 많은 플로우가 겹쳐져 있어서 메서드의 길이가 조금 기네요 ! 
잘 부탁드리겠습니다 !

## 관련 이슈

closes #91 #92 

## 체크리스트

- [x] `reviewers` 설정
- [x] `label` 설정
- [x] `milestone` 설정

2023-07-16 14:18 UTC, eunkeeee commented on backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
> +    @Autowired
옴마야 오토와이얼드 엄청많네요 ㅋㅋㅌㅋㅌㅋ

2023-07-16 15:31 UTC, youngh0 requested changes
안녕하세요 ㅎㅎ

코드가 좋네요 ㅎ_ㅎ 이번 PR은 조회보단 insert의 성격이 강해서 로직 상 리뷰할건 없어 보여서 제 생각 몇 자 적어봤습니다.

주말동안 매우 고생 많으셨습니다~

2023-07-16 15:31 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeFindResult.java
> +    public static CafeFindResult from(Cafe cafe) {
dto와 도메인 간 의존 관련 내용이 PR본문에 있어서 리뷰 답니다 ㅎㅎ

사실 dto생성이 정말 귀찮은 작업이라 이렇게 정팩메를 통해 parameter로 도메인을 받아서 만들면 귀찮음을 줄일 수 있어서 좋다고 생각해요!!

관련해서 찾아보니까 dto-mapper-pattern이란게 있더라구요. 별도의 Mapper클래스를 작성하는건데 현재 저희는 동일한 dto가 여러 군데에서 쓰이지 않기 때문에 Mapper까지는 투머치가 아닌가라는 생각이 들긴 하네요!

어쨌든 핵심은 해당 패턴에서도 보면 dto를 생성할 때 도메인을 parameter로 받아서 만드는 예제코드를 볼 수가 있습니다!
링크도 같이 남겨둘게요 ㅎㅎ[밸덩](https://www.baeldung.com/java-dto-pattern)

2023-07-16 15:31 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        cafeRepository.save(cafe);
문득 든 생각인데, 어차피 cafe가 owner를 알고 있기 때문에 `businessRegistrationNumber`를 cafe에서 몰라도 어차피 owner를 통해 조회가능 할 것 같단 생각이 드네요.

중요한 사안은 아니니 나중에 얘기해보죠 ㅎㅎ

2023-07-16 15:31 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        cafePolicyRepository.save(CafePolicy.createDefaultCafePolicy(cafe));
카페를 등록할 때 리워드가 NO인 정책을 저장시키는게 괜찮을지 조금 고민되네요.

한 번 Cafe와 CouponPolicy가 꼭 객체 참조로 이루어져야 하는지 고민해봐도 좋을듯 합니다! 제가 보던 우아한 객체지향 세미나 영상이 있는데 빨리 다 보고 고민해볼게요!

2023-07-16 15:31 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/entity/sample/SampleBackImage.java
> +    @OneToMany(mappedBy = "sampleBackImage")
SampleBackImage와 SampleStampCoordinate둘 다 연관관계 편의 메서드가 없는 것 같아요!

추가적으로, cascade설정도 고려해보면 좋을 것 같아요!

2023-07-16 15:31 UTC, youngh0 commented on backend/src/test/java/com/stampcrush/backend/application/cafe/CafeServiceTest.java
> +    @Autowired
ㅋㅋㅋㅋㅋㅋ Autowired웅장하네요. 테스트 짜느라 고생하셨습니다👍

2023-07-16 15:38 UTC, youngh0 commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeFindResult.java
> +    public static CafeFindResult from(Cafe cafe) {
[https://www.amitph.com/spring-entity-to-dto/](https://www.amitph.com/spring-entity-to-dto/)
다른 글도 하나 남깁니다 ㅎㅡㅎ

2023-07-16 15:56 UTC, yenawee requested changes
쿠폰 못지 않게 카페도 많은 것들과 연관되어있었군요... Sample 들이 복병이었네요 ..!

고생많았어요 하디 

전체적으로 롬복 생성자 어노테이션 활용해주면 조을거같아요
다른 부분은 레오가 리뷰를 너무 잘남겨주었어서..👍

2023-07-16 15:56 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +                1L,
header 에 Owner 의 credential 이 어떻게 들어갈지 결정을 빨리 해야할 필요성이 있군요 ..! Owner 인증이 필요한 메서드들이 많아서리....

2023-07-16 15:56 UTC, yenawee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        return ResponseEntity.created(URI.create("/cafes" + cafeId)).build();
"/cafes/" + cafeId ㅎㅎ

2023-07-17 06:14 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        cafeRepository.save(cafe);
사업자 등록번호는 카페에 등록되는것 아닌가용 ㅇ?ㅇ 

디테일하게 설명해주세여 !

2023-07-17 06:14 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        cafePolicyRepository.save(CafePolicy.createDefaultCafePolicy(cafe));
음 기본리워드에 대한 얘기가 없었어서 일단 제맘대로 스트링으로 박긴했습니다만..ㅠㅠ

2023-07-17 06:45 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +                1L,
ㅇㅈ

2023-07-17 06:58 UTC, eunkeeee requested changes
리뷰가 너무 많아졌네요! 죄송 ㅎㅎㅎㅎㅎ
코드 잘 봤습니당!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        CafeCreate cafeCreate = new CafeCreate(
Request DTO -> Service DTO 변환은 Request DTO 내부 로직으로 넣는거 어떨까요!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        return ResponseEntity.created(URI.create("/cafes/" + cafeId)).build();
```suggestion
        return ResponseEntity
                .created(URI.create("/cafes/" + cafeId))
                .build();
```

엔터 쳐주는거 어떤가요 
좀더 가독성 좋을 것 같은데
(깃짱의 개취일수도)

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        Cafe cafe = new Cafe(
이거 좀 더 깔끔한 방법은 없을라나요....! 
필드가 많아서 그런지 어질어질하네요

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        Cafe cafe = new Cafe(
CafeCreateDto 내부에서 변환 로직을 만드는건 별론가요!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +@Transactional
아래에서 readonly true를 별도로 걸거면, 클래스 단 말고 메서드 단별로 달아도 좋을 것 같아요!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/dto/response/CafeFindResponse.java
> +public class CafeFindResponse {
이름추천... CafeQueryResponse

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/dto/response/CafeFindResponse.java
> +public class CafeFindResponse {
빠인드가 더 좋으면 빠인드도 괜찮은거같아요

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        SampleStampImage defaultSampleStampImage = findDefaultSampleStampImage();
아래에 예외처리가 있긴 하지만, 저희가 더미데이터를 넣어줄 것이기 때문에 안넣을 경우까지 고려해야 할까 싶습니다! 
나중에는, 그냥 디폴트를 정해놓고, 그걸 딱 찾아서 넣어주는 것도 좋을 것 같아요 모두 찾고 첫번째꺼를 보내주는것보다는!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        List<CafeFindResult> cafeFindResults = cafeService.findAllCafes(1L);
나중에는 header로 들어올 정보를 아직은 그냥 직접 적어넣은 건가요?

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeFindResult.java
> +public class CafeFindResult {
CafeDto로 해도 괜찮을 것 같은 내용인 것 같아요!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeCreate.java
> +public class CafeCreate {
얘도 CafeDto로 그냥 써도 괜찮을 것 같은 내용인데요!

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        List<Cafe> cafes = cafeRepository.findAllByOwnerId(ownerId);
좀 더 객체지향적으로 가려면 OwnerId가 아니라 owner 객체 그대로 조회하는 게 더 좋을 것 같아요

2023-07-17 06:58 UTC, eunkeeee commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        List<Cafe> cafes = cafeRepository.findAllByOwnerId(ownerId);
비슷한 경우 테스트해봤는데 아이디로 할 때나 객체 그대로 할 때나 쿼리는 동일하게 나가더라고요! 
혹시 고칠거면 그래도 쿼리로 조인이나 셀렉트 한 번 더 나가나 확인해봤으면 좋겠습니다!

2023-07-17 07:59 UTC, yenawee approved these changes

2023-07-17 08:04 UTC, youngh0 approved these changes

2023-07-17 08:05 UTC, merged

2023-07-17 14:43 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        return ResponseEntity.created(URI.create("/cafes/" + cafeId)).build();
혹시 `create`만 개행을 하시는 편이신가요 ? 아니면 모두 하시는편이신가요 ?

2023-07-17 14:46 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +        Cafe cafe = new Cafe(
`CafeCreateDto`는 내부에 `ownerId`를 가지고 있으나, `Cafe`는 `owner`를 가져야해서 변환하기는 어려울 것 같습니다 ㅠㅠ
`private method`라도 따로 뺴는게 나을까요 ?

2023-07-17 14:48 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/CafeService.java
> +@Transactional
저는 메서드에 `@Transactional`을 붙이는걸 까먹을까봐 클래스 딴에 기본으로 걸어두고 읽기전용 메서드는 따로 `readOnly` 옵션을 걸어 해결하고 있습니다.....!!
취향차이인가요 ?

2023-07-17 14:49 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/dto/response/CafeFindResponse.java
> +public class CafeFindResponse {
오늘 통일 하였습니다 ~_~

2023-07-17 14:52 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/api/cafe/CafeApiController.java
> +        List<CafeFindResult> cafeFindResults = cafeService.findAllCafes(1L);
네넵 어떤식으로든 해당 `Owner`에 대한 `Cafe`를 찾아야했기에 그냥 `pk`라고 가정하고 `1L`을 하드 코딩해서 넣어놨습니다.

추후에 변경이 꼭 필요한 곳입니다.

2023-07-17 14:53 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeFindResult.java
> +public class CafeFindResult {
오늘 회의 후 통일!

2023-07-17 14:53 UTC, jundonghyuk commented on backend/src/main/java/com/stampcrush/backend/application/cafe/dto/CafeCreate.java
> +public class CafeCreate {
통일!